### PR TITLE
fix: variable expansion on buildargs that only have one env

### LINKED ISSUE #3684: Build Args refering to another build are not expanded
**Describe the bug**
If I use an okteto build environment as a build arg the build arg is not getting the correct value. I expect that this build arg uses the okteto env var that I provided

**To Reproduce**

1. Create the following Dockerfile:
```Dockerfile
FROM alpine

ARG KEY
RUN echo testing: $KEY
```
1. Create the following okteto manifest:
```yaml
build:
  test:
    context: .
    args:
      KEY: hello
  test-2:
    context: .
    args:
      KEY: $OKTETO_BUILD_TEST_IMAGE
    depends_on:
      - test
```
1. Run `okteto build --progress plain -f okteto.yml --no-cache`
1. See that the `$OKTETO_BUILD_TEST_IMAGE` is not propagated

**Expected behavior**
I want that the build arg gets into the image

### LINKED ISSUE #3686: `OKTETO_` env vars extended too early making manifest not work
See: https://community.okteto.com/t/docker-image-no-longer-receiving-okteto-build-arg/841

Image

### PR DESCRIPTION
**Pull request by jLopezbarb**
# Proposed changes

Fixes #3686 
Fixes #3684

- Update dependency
- Add unit tests covering a value with a single env var
- Add unit test for getting the build hash with a single env var
- If the value is a single env var on serializer don't expand it

## Tests done
- Using #3684 reproduction steps. Check that the variable is printed inside buildkit
- Check that the build hash changes with different values of the build env var

### CODE REVIEW

**Review by andreafalzetti — APPROVED** [review]

File: pkg/model/dev.go [hunk 1]
```diff
@@ -141,7 +141,11 @@ type BuildArg struct {
 }
 
 func (v *BuildArg) String() string {
-	return fmt.Sprintf("%s=%s", v.Name, v.Value)
+	value, err := ExpandEnv(v.Value, true)
+	if err != nil {
+		return fmt.Sprintf("%s=%s", v.Name, v.Value)
+	}
+	return fmt.Sprintf("%s=%s", v.Name, value)
```
Comment (AdrianPedriza) [inline pkg/model/dev.go:148]:
```suggestion
	value, err := ExpandEnv(v.Value, true)
	if err != nil {
		value = v.Value
	}
	
	return fmt.Sprintf("%s=%s", v.Name, value)
```

**Review by AdrianPedriza — APPROVED** [review]

**Review by AdrianPedriza — APPROVED** [review]

File: pkg/model/dev.go (hunk 1 above)
Comment (AdrianPedriza) [reply pkg/model/dev.go:148]: minor suggestion
