### PR TITLE
Execute "up.shutdown" when exiting "okteto up"

### LINKED ISSUE #938: `okteto down` doesn't kill the syncthing process in MacOS
Taken from #934:

If I run `okteto  up` using the vscode command palette from the very beginning, a clean system, everthing works like a charm, however, there were tow syncthing process in the mac system. After `okteto down`, sometimes the processes would not be killed and remained in the system. 

If I killed these 'syncthing' processes, and then `oketeto up` again, everything would work fine, otherwise, the erro `syncthing local=true not responding after 15s` would occur.

I tried the same thing in ubuntu 20.04,  things were different.

After `okteto up`, mac syncthing processes:

```
ps aux | grep syncthing
enderson         13917  10.7  0.2  4485496  14180 s002  R+    8:41上午   0:01.75 /Users/enderson/.okteto/syncthing -home /Users/enderson/.okteto/default/hello-world -no-browser -verbose -logfile /Users/enderson/.okteto/default/hello-world/syncthing.log -log-max-old-files=0
enderson         14070   2.1  0.0  4287756    760 s001  S+    8:43上午   0:00.01 grep syncthing
enderson         13901   0.0  0.1  4425824   6928 s002  S+    8:41上午   0:00.12 /Users/enderson/.okteto/syncthing -home /Users/enderson/.okteto/default/hello-world -no-browser -verbose -logfile /Users/enderson/.okteto/default/hello-world/syncthing.log -log-max-old-files=0
```

ubuntu syncthing processes:
```
root       23323  0.0  0.4 120940 13488 ?        Sl   08:45   0:00 /var/okteto/bin/syncthing -home /var/syncthing -gui-address 0.0.0.0:8384 -verbose
root       23340  5.8  1.1 122476 36336 ?        Sl   08:45   0:01 /var/okteto/bin/syncthing -home /var/syncthing -gui-address 0.0.0.0:8384 -verbose
sake       23372  0.0  0.3 122528 12268 pts/2    Sl+  08:45   0:00 /home/sake/.okteto/syncthing -home /home/sake/.okteto/default/hello-world -no-browser -verbose -logfile /home/sake/.okteto/default/hello-world/syncthing.log -log-max-old-files=0
sake       23527  4.4  0.8 122656 26516 pts/2    Sl+  08:45   0:00 /home/sake/.okteto/syncthing -home /home/sake/.okteto/default/hello-world -no-browser -verbose -logfile /home/sake/.okteto/default/hello-world/syncthing.log -log-max-old-files=0
sake       24022  0.0  0.0  12112  2840 pts/0    R+   08:45   0:00 grep --color=auto syncthing
```

After `okteto down`, mac syncthing processes:

```
ps aux | grep syncthing
enderson         13917   0.0  0.1  4485512   4432   ??  T     8:41上午   0:02.20 /Users/enderson/.okteto/syncthing -home /Users/enderson/.okteto/default/hello-world -no-browser -verbose -logfile /Users/enderson/.okteto/default/hello-world/syncthing.log -log-max-old-files=0
enderson         13901   0.0  0.0  4425824   2708   ??  T     8:41上午   0:00.14 /Users/enderson/.okteto/syncthing -home /Users/enderson/.okteto/default/hello-world -no-browser -verbose -logfile /Users/enderson/.okteto/default/hello-world/syncthing.log -log-max-old-files=0
enderson         14329   0.0  0.0  4268300    704 s001  S+    8:51上午   0:00.00 grep syncthing
```

Ubuntu syncthing processes:
```
ps aux | grep syncthing
sake       29510  0.0  0.0  12112   732 pts/0    S+   08:52   0:00 grep --color=auto syncthing
```

So it seems `okteto down` kill the syncthing process on Ubuntu, however, failed kill syncthing process on mac.

So after I killing the processes manually, everything works fine.

So maybe this issue is a bug in macOS, for `okteto down` cannot properly kill the syncthing process.

### PR DESCRIPTION
**Pull request by pchico83**
Signed-off-by: Pablo Chico de Guzman <pchico83@gmail.com>

Fixes #938

### CODE REVIEW

File: pkg/syncthing/process.go [hunk 1]
```diff
@@ -30,7 +30,9 @@ func terminate(pid int) error {
 		return err
 	}
 
-	defer proc.Wait() // nolint: errcheck
+	if wait {
+		defer proc.Wait() // nolint: errcheck
```
Comment (pchico83) [inline pkg/syncthing/process.go:34]: @rberrelleza this is to avoid the `wait` when finishing an `okteto up` execution. Otherwise, we are adding a 6-7s delay. I think it is safe not to wait in this case. We do wait when running `Stop(force=true)` at the beginning of the `okteto up` sequence

Comment (rberrelleza) [reply pkg/syncthing/process.go:34]: I think we added this wait to prevent the case where you do down, up, and okteto tries to pick up an older pod no?

Comment (rberrelleza) [reply pkg/syncthing/process.go:34]: oh wait, this is at the syncthing level, not the okteto up leve.
