### PR TITLE
Forward to services when using ssh mode

### LINKED ISSUE #1086: When using ssh port-forwarding, the notation "port:service-name:port" does not work
**Describe the bug**
Using ssh port-forward breaks the port forwarding to other services other than the dev container.

### PR DESCRIPTION
**Pull request by rberrelleza**
Fixes #1086

### CODE REVIEW

File: cmd/up/up.go [hunk 1]
```diff
@@ -610,34 +610,10 @@ func (up *upContext) forwards() error {
 		return err
 	}
 
-	if up.Dev.RemoteModeEnabled() {
-		if err := up.Forwarder.Add(model.Forward{Local: up.Dev.RemotePort, Remote: up.Dev.SSHServerPort}); err != nil {
-			return err
-		}
-	}
-
```
Comment (rberrelleza) [inline cmd/up/up.go:618]: this is all dead code

**Review by pchico83 — APPROVED** [review]
