### PR TITLE
Fixed bug of memory requests/reservations

### LINKED ISSUE #3383: K8S resources.requests.memory from docker-compose is not being set
**Describe the bug**
If you set in docker-compose the `resources.requests.cpu` value it will never map the `resources.requests.memory` value to the k8s resource.

We have detected this because a Community question: https://community.okteto.com/t/how-to-configure-k8s-resources-limits-requests-from-docker-compose-yml/604

**To Reproduce**

1. Use movies-with-docker-compose repo
2. Add to one of the services the resources requests (cpu and memory)
3. Check that the pod created resource has the memory set with the default value

**Expected behavior**
The result pod should have the memory value you are setting

### PR DESCRIPTION
**Pull request by mnevadom**
Fixes #3383 

Tested with the two `resources` options allowed: 

```
deploy: 
      resources:
          limits:
            cpus: "2"
            memory: "5Gi"
          reservations:
            cpus: 11m
            memory: 60Mi
```

and 

```
resources:
    limits:
      cpu: "2"
      memory: "5Gi"
    requests:
      cpu: 11m
      memory: 60Mi
```

We should add to the docs the two options, since we just have the second one and docker-compose allows the first one too: 

https://www.okteto.com/docs/reference/compose/#resources-object-optional

### CODE REVIEW

File: pkg/cmd/stack/translate.go [hunk 1]
```diff
@@ -667,8 +667,8 @@ func translateResources(svc *model.Service) apiv1.ResourceRequirements {
 		if svc.Resources.Requests.Memory.Value.Cmp(resource.MustParse("0")) > 0 {
 			if result.Requests == nil {
 				result.Requests = apiv1.ResourceList{}
-				result.Requests[apiv1.ResourceMemory] = svc.Resources.Requests.Memory.Value
 			}
+			result.Requests[apiv1.ResourceMemory] = svc.Resources.Requests.Memory.Value
```
Comment (jLopezbarb) [inline pkg/cmd/stack/translate.go:671]: Could we add a test for this function? These are the use cases that we need to test:
- `svc.Resources` not defined by the user
- `svc.Resources.Limits` defined:
  - `svc.Resources.Limits.CPU` defined
  - `svc.Resources.Limits.CPU` not defined
  - `svc.Resources.Limits.Memory` defined
  - `svc.Resources.Limits.Memory` not defined
- `svc.Resources.Requests` defined:
  - `svc.Resources.Requests.CPU` defined
  - `svc.Resources.Requests.CPU` not defined
  - `svc.Resources.Requests.Memory` defined
  - `svc.Resources.Requests.Memory` not defined

Comment (AgustinRamiroDiaz) [reply pkg/cmd/stack/translate.go:671]: :point_up: Yes please. Javi's description is great to do some table tests

**Review by jLopezbarb — APPROVED** [review]

**Review by ifbyol — APPROVED** [review]
