### PR TITLE
Load context resource only instead of the whole file while loading ctx

### LINKED ISSUE #2728: Warning unmarshall messages are shown two times
**Describe the bug**
If a okteto yaml/compose file/pipeline manifest has a warning while unmarshalling the message will appear two times (one before the context initialisation and another one after it). It's weird to see the same warning several times
Captura de pantalla 2022-05-30 a las 12 35 53

**To Reproduce**

1. Create this manifest:
```
name: test
image: okteto/golang:1
command: bash
labels:
  - as:as
sync:
- .:/usr/src/app
forward:
- 2345:2345
- 8080:8080
autocreate: true
```
2. Run okteto up 

**Expected behavior**
I wanted to see only one warning message

**Desktop (please complete the following information):**

- OS: macOs
- Version 2.3.0

**Additional context**
This is due to how we read context. We need to load the same file two times, one to extract the namespace and context (contextresource) and another one to get the manifest struct.  We should be loading only the contextresource instead of reading the whole file and extracting the context resource from the struct.

### PR DESCRIPTION
**Pull request by jLopezbarb**
Fixes #2728 

## Proposed changes
- When reading a context resource only read the namespace and context and skip the unmarshalling of the rest of the file
- Created package discovery to look for okteto manifest/compose files/okteto pipelines/k8s manifests/helm charts.
- Created package filesystem with functions related to filesystem(I needed to create it because a cyclic import).

### CODE REVIEW

File: pkg/model/stack.go [hunk 1]
```diff
@@ -35,22 +37,6 @@ import (
 var (
 	errBadStackName = "must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character"
 	//DefaultStackManifest default okteto stack manifest file
```
Comment (ifbyol) [inline pkg/model/stack.go:39]: I think this comment doesn't apply anymore

File: pkg/model/stack.go [hunk 2]
```diff
@@ -712,15 +698,19 @@ func LoadStack(name string, stackPaths []string, validate bool) (*Stack, error)
 	var resultStack *Stack
 
 	if len(stackPaths) == 0 {
-		stack, err := inferStack(name)
+		dir, err := os.Getwd()
+		if err != nil {
+			return nil, err
+		}
```
Comment (ifbyol) [inline pkg/model/stack.go:704]: This might have side effects regarding the working directory change we do when loading the manifest in okteto deploy

**Review by ifbyol — COMMENTED** [review]
Can we run the integration tests of this branch before merging it to master?

File: pkg/model/contextresource.go [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+
+	"github.com/okteto/okteto/pkg/discovery"
+	oktetoErrors "github.com/okteto/okteto/pkg/errors"
+	"github.com/okteto/okteto/pkg/filesystem"
+	yaml "gopkg.in/yaml.v3"
+)
+
+// ContextResource provides the context and namespace to operate within a manifest
+type ContextResource struct {
+	Context   string
```
Comment (jmacelroy) [inline pkg/model/contextresource.go:27]: The setters for these have some logic that helps provide a guard. Given that they should probably not be exported. Can you check if anyone is using this. If they are setting it without the setter then it may be we have a bug and if they are getting it then we need to add a getter.

Comment (jmacelroy) [reply pkg/model/contextresource.go:27]: For marshaling within this package
``` 
// For private/package consumption due to yaml marshalling requirements.
type contextResource struct {
    Context string
    Namespace string
}

// For public consumption due to the requirement of a logical setter.
type ContextResource struct {
    context string
    namespace string
}
```

Comment (jLopezbarb) [reply pkg/model/contextresource.go:27]: That is something that needs to be addressed but I think this PR is big enough to add more changes. Changing that requires changing all `cmd/context` and their references so the number of touched files can go up to 30 files more. Could we do it as part of the `removing model` refactor?

**Review by jmacelroy — APPROVED** [review]

**Comment by jLopezbarb** [comment]
> Can we run the integration tests of this branch before merging it to master?

They have already run [here](https://app.circleci.com/pipelines/github/okteto/okteto/7849/workflows/36eddc9f-dacc-45d5-9aaf-bd00c57806f0)

File: pkg/model/stack.go (hunk 2 above)
Comment (ifbyol) [reply pkg/model/stack.go:703]: This scares me a bit since `LoadStack` could have different result executing it before and after the change we do in the working directory. We rely too much on `os.Getwd` I think it doesn't affect as the previous `inferStack` function was relying also in the current working directory but we should be careful with that.

**Review by ifbyol — APPROVED** [review]
My comment about the side effect for relying in the working directory is something that is also happening in the current code and it is something that should be part of this ticket: https://github.com/okteto/okteto/issues/2855
