### PR TITLE
trigger a new context store write

### LINKED ISSUE #3387: a new context cannot be initialize exclusively with envs
**Describe the bug**
if I don't have an okteto context store file but have the necessary envs to use a context, I get an error `okteto context store is corrupted. Delete the folder '%s' and try again` because I don't have the okteto context store file. 

**To Reproduce**

1. Remove okteto context file (or rename it)
2. Set `OKTETO_TOKEN` and `OKTETO_URL` envs
3. Execute `okteto deploy` using okteto/movies 

**Expected behavior**
If I have the necessary envs set to use a new context any okteto command that make use of the okteto context should be able to be exec

### PR DESCRIPTION
**Pull request by AdrianPedriza**
# Proposed changes

Fixes #3387

### CODE REVIEW

File: cmd/context/use.go [hunk 1]
```diff
@@ -93,6 +93,11 @@ Or a Kubernetes context:
 
 func (c *ContextCommand) Run(ctx context.Context, ctxOptions *ContextOptions) error {
 	ctxStore := okteto.ContextStore()
+	if len(ctxStore.Contexts) == 0 {
+		// if the context store has no context stored, set flag to save
```
Comment (jLopezbarb) [inline cmd/context/use.go:97]: Can we specify that this is just when the command is not a context one, for example (build deploy up)

**Review by jLopezbarb — APPROVED** [review]

File: cmd/context/use.go (hunk 1 above)
Comment (AdrianPedriza) [reply cmd/context/use.go:97]: sure!

**Review by jLopezbarb — APPROVED** [review]
