### PR TITLE
wrap exec command on a shell to run multiple commands

### LINKED ISSUE #685: `okteto exec` fails to execute chained commands
**Describe the bug**
Running a  command with `&&` or `||` fails in the context of `okteto exec`

**To Reproduce**
1. `okteto exec "mkdir foo && cd foo && ls -la"`

**Expected behavior**
Command should execute successfully

**Desktop (please complete the following information):**
 - Version 1.7.1

### PR DESCRIPTION
**Pull request by rberrelleza**
Fixes #685

### CODE REVIEW

File: cmd/exec.go [hunk 1]
```diff
@@ -78,9 +78,12 @@ func Exec() *cobra.Command {
 
 func executeExec(ctx context.Context, dev *model.Dev, args []string) error {
 
+	wrapped := []string{"sh", "-c"}
```
Comment (rberrelleza) [inline cmd/exec.go]: @pchico83 do you see any potential side effects on this approach?

Comment (pchico83) [reply cmd/exec.go]: not having `sh`, but we already have that problem everywhere

Comment (rberrelleza) [reply cmd/exec.go]: true. we need to document that for now.
