### PR TITLE
fix: preview output json

### LINKED ISSUE #3860: "okteto preview endpoints $NAME -ojson" produces invalid json
**Describe the bug**

**To Reproduce**
1. Set a secret in Okteto
2. Create a local environment variable with the same name
3. execute "okteto preview endpoints $NAME -ojson

Output will be something like this:
```
!  $AWS_SECRET_ACCESS_KEY secret is being overridden by a local environment variable by the same name.
 !  $AWS_ACCESS_KEY_ID secret is being overridden by a local environment variable by the same name.
[
  {
    "url": "https://todo-list-pr-getting-started-4.ramiro.okteto.dev",
    "private": false
  }
]
```

**Expected behavior**
the output should be valid JSON 

**Desktop (please complete the following information):**

- OS: macos
- Version 2.18.0

### PR DESCRIPTION
**Pull request by jLopezbarb**
# Proposed changes

Fixes #3860 

- Save the logs that should appear while initializing the context
- Print them as information messages on the log file if the ouptut is json

## Before and after:

| Before | After |
|--------|-------|
| Captura de pantalla 2023-07-31 a las 13 53 24  | Captura de pantalla 2023-07-31 a las 13 54 19 |

## Reproduction steps
1. Set Secret `KEY` on okteto cloud settings
2. Create a local environment variable `$KEY` with different value
3. Run `okteto preview deploy issue-USERNAME --scope personal --branch master --repository https://github.com/okteto/movies`
4. execute "okteto preview endpoints issue-USERNAME -ojson

### CODE REVIEW

File: cmd/preview/endpoints.go [hunk 1]
```diff
@@ -46,11 +48,19 @@ func Endpoints(ctx context.Context) *cobra.Command {
 				return err
 			}
 
+			jsonContextBuffer := bytes.NewBuffer([]byte{})
+			if output == "json" {
```
Comment (andreafalzetti) [inline cmd/preview/endpoints.go:52]: I know it's not part of the scope of the bug reported but I was wondering:

We support two output formats: `json` and `md` (besides the default one which would be something like: `plaintext` or `text`)

Would it make sense to slightly adjust this change to also fix `md`? I imagine the `md` output is useful to be injected in a Markdown document, but at the moment it would also output and inject the logs, making the feature kind of broken.

My proposal would be change this condition to be `if output != "text" {..}` and add `text` as valid output format.

I actually think we should add `plaintext` or `text` to all output flags, I've created an [issue about it](https://github.com/okteto/okteto/issues/3805) some time ago

Comment (andreafalzetti) [reply cmd/preview/endpoints.go:52]: I don't want to block the PR, the change works and LGTM. If we can squeeze the change good, or I can create a follow-up issue (I didn't because I think the change could be very tiny, let me know!)

**Review by andreafalzetti — APPROVED** [review]

File: cmd/preview/endpoints.go (hunk 1 above)
Comment (AdrianPedriza) [reply cmd/preview/endpoints.go:52]: IMO I think it is safe and has the sense to address your suggestion in this PR 👍

File: cmd/preview/endpoints.go
Comment (AdrianPedriza) [inline cmd/preview/endpoints.go:1]: should we move output validation at the beginning of the command instead run logic related to output before validating it?

File: cmd/preview/endpoints.go (hunk 1 above)
Comment (jLopezbarb) [reply cmd/preview/endpoints.go:52]: It'd be great to extend them but I'll address in another PR. In fact there is a [current issue](https://github.com/okteto/okteto/issues/3859) for the md

File: cmd/preview/endpoints.go
Comment (jLopezbarb) [reply cmd/preview/endpoints.go:1]: I wouldn't do it as part of this PR to have an specific context when reviewing the code later on. 
I do think that's something we need to do in the future not just on this command but all the commands that shows tables or other outputs that are not the typical ones

File: cmd/preview/endpoints.go (hunk 1 above)
Comment (andreafalzetti) [reply cmd/preview/endpoints.go:52]: sounds good to me, already approved, so feel free to ship it 🚢
