### PR TITLE
Fix: error message missing filename

### LINKED ISSUE #2627: error message is missing file name
**Describe the bug**
The error message is missing the file name is looking for
image

**To Reproduce**

1. Create a repo with only a Dockerfile
2. Run okteto up

**Expected behavior**
I was expecting the error message to include a file name

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.2.1

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

### PR DESCRIPTION
**Pull request by AdrianPedriza**
Signed-off-by: adripedriza <adripedriza@gmail.com>

Fixes #2627

## Proposed changes

- use DefaultManifest const if a dev file has not been provided

### CODE REVIEW

File: cmd/utils/dev.go [hunk 1]
```diff
@@ -367,6 +367,9 @@ func AskForOptions(options []string, label string) (string, error) {
 
 //AskIfOktetoInit asks if okteto init should be executed
 func AskIfOktetoInit(devPath string) bool {
+	if devPath == "" {
+		devPath = DefaultManifest
```
Comment (jmacelroy) [inline cmd/utils/dev.go:371]: Is that the name of the one we'll create if the user selects "y".

Comment (jLopezbarb) [reply cmd/utils/dev.go:371]: Yes, When we call `okteto init` without adding the file it will create it with the name of `DefaultManifest`

**Review by jLopezbarb — APPROVED** [review]
