### PR TITLE
redeploy stack with 0 downtime

### LINKED ISSUE #3083: I want to redeploy my stack without downtime
**Describe the bug**
If I redeploy my `okteto stack` I want to have 0 downtimes but since the deployments created have the recreate update strategy, I can't 

**To Reproduce**

1. Copy the following `docker-compose.yml`
```yaml
services:
  app:
    image: python:alpine
    entrypoint: python -m http.server 8080
    ports:
      - 8080:8080
```
2. Run okteto deploy
3. Change the entrypoint to `python -m http.server 8081`
4. Run okteto deploy to redeploy
5. See that the pod is recreated

**Expected behavior**
I want to have 0 downtime while redeploying a compose/stack

**Desktop (please complete the following information):**

- Version 2.6.0

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

# Proposed changes

Fixes #3083

- Change from recreate strategy to rolling update

# Concerns

This change can generate new quota issues that we cannot detect if the command is not executed with the `--wait` flag.
Captura de Pantalla 2022-09-16 a las 10 45 10

### CODE REVIEW

**Comment by AgustinRamiroDiaz** [comment]
@jLopezbarb would we always hit twice the deployments at some point? Maybe if we know how much resources we got at the "spike" we could prevent quota issues

Also, I don't see any change for statefulsets and maybe it's for the best:
"When using [Rolling Updates](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates) with the default [Pod Management Policy](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies) (OrderedReady), it's possible to get into a broken state that requires [manual intervention to repair](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#forced-rollback)"
Taken from https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations

**Review by ifbyol — COMMENTED** [review]
Would it make sense to allow a new property in the stack to specify how to replace the deployment and keep the current behavior by default?

File: pkg/cmd/stack/translate_test.go [hunk 1]
```diff
@@ -346,7 +347,7 @@ func Test_translateStatefulSet(t *testing.T) {
 	if !reflect.DeepEqual(vct.Spec, volumeClaimTemplateSpec) {
 		t.Errorf("Wrong statefulset volume claim template: '%v'", vct.Spec)
 	}
-
+	assert.Equal(t, result.Spec.UpdateStrategy.Type, appsv1.RollingUpdateStatefulSetStrategyType)
```
Comment (ifbyol) [inline pkg/cmd/stack/translate_test.go:350]: Is the rolling update the default for statefulsets? I don't see a change for statefulsets but we are adding this check

Comment (jLopezbarb) [reply pkg/cmd/stack/translate_test.go:350]: Yes, we already have it as the default one for sfs

**Comment by jLopezbarb** [comment]
> Would it make sense to allow a new property in the stack to specify how to replace the deployment and keep the current behavior by default?

Maybe by adding an annotation to the service, we can change the redeploy strategy. But I think we should stick to rolling update as the default one since it's the most common scenario that people want to achieve

**Comment by ifbyol** [comment]
> > Would it make sense to allow a new property in the stack to specify how to replace the deployment and keep the current behavior by default?
> 
> Maybe by adding an annotation to the service, we can change the redeploy strategy. But I think we should stick to rolling update as the default one since it's the most common scenario that people want to achieve

It is the most common scenario in a **production** environment. Talking about a dev environment scenario, a small downtime should be acceptable. Also, this is a change of behavior and it might have impact on the quotas, so that's why I mention a more conservative approach of keeping current behavior

**Comment by jLopezbarb** [comment]
> > > Would it make sense to allow a new property in the stack to specify how to replace the deployment and keep the current behavior by default?
> > 
> > 
> > Maybe by adding an annotation to the service, we can change the redeploy strategy. But I think we should stick to rolling update as the default one since it's the most common scenario that people want to achieve
> 
> It is the most common scenario in a **production** environment. Talking about a dev environment scenario, a small downtime should be acceptable. Also, this is a change of behavior and it might have impact on the quotas, so that's why I mention a more conservative approach of keeping current behavior

After discussing with @pchico83 we decided to go with the approach of annotation on each service or set an environment variable to get the behaviour on every service (these changes only affect deployments and statefulset from compose).

The annotation should be `dev.okteto.com/upgrade` with the available options being `rolling` for rolling update and `recreate`.

The environment is `OKTETO_UPGRADE_POLICY` with the same available options as before.

The annotation will take precedence over the environment variable, that way a user can have all its services with a default upgrade policy with the environment variable and another upgrade policy for specific services

File: pkg/cmd/stack/translate_test.go (hunk 1 above)
Comment (jLopezbarb) [reply pkg/cmd/stack/translate_test.go:350]: I don't know where I checked but I don't see it know, so I will add it too

Comment (ifbyol) [reply pkg/cmd/stack/translate_test.go:350]: It is important to not change the current behavior for sfs

Comment (jLopezbarb) [reply pkg/cmd/stack/translate_test.go:350]: Checked that the default behavior is rolling update, so we still have the same behavior

**Comment by jLopezbarb** [comment]
I changed a little bit the implementation that was suggested [in the previous comment](https://github.com/okteto/okteto/pull/3109#issuecomment-1252433982).

I had to add `onDelete` to the list of possible update strategy, so the available values are `rolling` and `onDelete` for `statefulsets` and `rolling` and `recreate` for `deployments`.

I decided to change the initial annotation from `dev.okteto.com/upgrade` to `dev.okteto.com/update` to keep consistency with the k8s naming convention and the environment variable from `OKTETO_UPGRADE_POLICY` to `OKTETO_COMPOSE_UPDATE_STRATEGY` since the variable is only going to be used on the compose/stack and used the word update strategy to keep consistency with the previous annotation. WDYT?

cc: @pchico83 @ifbyol

**Comment by pchico83** [comment]
> onDelete

@jLopezbarb makes sense. But let's use `on-delete` as the value, it's the format we use in every annotation value

**Comment by ifbyol** [comment]
Ok, sounds good! 👍

**Review by teresaromero — APPROVED** [review]
