### PR TITLE
Return user friendly error if secret file is not found

### LINKED ISSUE #2033: Show an user friendly message when a secret is not found
**Describe the bug**
We should show a user-friendly secret when the file mentioned in okteto.yml is not avaiable.

**To Reproduce**

1. Add a`secret` to your okteto.yaml , with a file that doesn't exist
2. Run` okteto up` 

- Version 1.14.8

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

image

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #2033

## Proposed changes
- Return user friendly error when secret file not found
-

### CODE REVIEW

File: pkg/model/serializer.go [hunk 1]
```diff
@@ -634,7 +634,7 @@ func (l Lifecycle) MarshalYAML() (interface{}, error) {
 func checkFileAndNotDirectory(path string) error {
 	fileInfo, err := os.Stat(path)
 	if err != nil {
-		return err
+		return fmt.Errorf("'%s' not found. Please make sure the file exists", path)
```
Comment (pchico83) [inline pkg/model/serializer.go:637]:
```suggestion
		return fmt.Errorf("File '%s' not found. Please make sure the file exists", path)
```

**Review by pchico83 — APPROVED** [review]
