### PR TITLE
fix: panic on non existen svc

### LINKED ISSUE #2705: Deployment of a non-existent service results in a panic.
**Describe the bug**
When deploying using a compose file, from okteto/compose-getting-started, running the deploy command and providing a service name that does not exist results in a panic.
```
➜  compose-getting-started git:(master) ~/okt/okteto/bin/okteto deploy --wait --build -v one=first notreal
 i  Using jmacelroy @ staging.okteto.dev as context
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x5ce7448]

goroutine 1 [running]:
github.com/okteto/okteto/pkg/cmd/stack.addDependentServices({0x6aeaa98, 0xc000124000}, 0xc001698840, {0xc000437ea0, 0x1, 0x5}, {0x6b03e10, 0xc0001cac00})
        github.com/okteto/okteto/pkg/cmd/stack/deploy.go:785 +0x1e8
github.com/okteto/okteto/pkg/cmd/stack.AddDependentServicesIfNotPresent({0x6aeaa98?, 0xc000124000?}, 0xc001942570?, {0xc000437ea0?, 0xc0013df3b8?, 0x4011825?}, {0x6b03e10?, 0xc0001cac00?})
        github.com/okteto/okteto/pkg/cmd/stack/deploy.go:769 +0x38
github.com/okteto/okteto/cmd/deploy.setDeployOptionsValuesFromManifest({0x6aeaa98, 0xc000124000}, 0xc000273a40, {0xc0000580f4, 0x28}, {0x6b03e10, 0xc0001cac00})
        github.com/okteto/okteto/cmd/deploy/deploy.go:480 +0x385
github.com/okteto/okteto/cmd/deploy.(*DeployCommand).RunDeploy(0xc0016775e0, {0x6aeaa98, 0xc000124000}, 0xc000273a40)
        github.com/okteto/okteto/cmd/deploy/deploy.go:275 +0x3b7
github.com/okteto/okteto/cmd/deploy.commandRunner.deployCommand({0xc000273a40?, {0x6aeaa98?, 0xc000124000?}}, 0xc0013dfc30?, {0xc000437ea0, 0x1, 0x5})
        github.com/okteto/okteto/cmd/deploy/deploy.go:211 +0x875
github.com/spf13/cobra.(*Command).execute(0xc001519900, {0xc000437e50, 0x5, 0x5})
        github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00120c280)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        github.com/okteto/okteto/main.go:136 +0x9a9
➜  compose-getting-started git:(master)
``` 

**Expected behavior**
The error should be handled gracefully and the user should be notified that we are unable to determine which service to deploy with the existing manifest or cli inputs.

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #2705

## Proposed changes
- Validate svcs to deploy before getting dependant svcs

### CODE REVIEW

**Review by teresaromero — APPROVED** [review]

File: pkg/cmd/stack/deploy.go [hunk 1]
```diff
@@ -777,7 +777,7 @@ func validateServicesToDeploy(ctx context.Context, s *model.Stack, options *Stac
 	return nil
 }
 
-func validateDefinedServices(s *model.Stack, servicesToDeploy []string) error {
+func ValidateDefinedServices(s *model.Stack, servicesToDeploy []string) error {
```
Comment (ifbyol) [inline pkg/cmd/stack/deploy.go:780]: Add a comment to the new exported function please

**Review by ifbyol — APPROVED** [review]
