### PR TITLE
Fix dev selector typo

### LINKED ISSUE #2778: typo in prompt when running okteto down
**Describe the bug**
If you run `okteto down` the prompt lists all dev containers but it says to select the container you want to "activate".

**To Reproduce**

1. Start a container
2. Run `okteto down`

**Expected behavior**
The prompt should say select the dev container you want to "deactivate". Another UX improvement could be if it lists down **only** the active containers instead of listing all containers.

**Desktop (please complete the following information):**

- OS: macOS
- Version: Okteto CLI 2.3.3

**Additional context**
Screenshot 2022-06-10 at 12 17 49 PM

### PR DESCRIPTION
**Pull request by teresaromero**
Fixes #2778 

## Proposed changes

- Separate selection logic from GetDevFromManifest. This function will though an error (ErrNoDevSelected) if devName is empty and manifest has multiple devs defined.
- new SelectDevFromManifest fallback function when err is ErrNoDevSelected, where label is a param that represents the question of the selector

### CODE REVIEW

**Review by jLopezbarb — APPROVED** [review]

File: cmd/utils/dev_test.go [hunk 1]
```diff
@@ -310,6 +310,29 @@ func Test_GetDevFromManifest(t *testing.T) {
 			dev:     &model.Dev{},
 			err:     nil,
 		},
+		{
+			name: "manifest has one dev section and user intrudices empty devName",
```
Comment (jLopezbarb) [inline cmd/utils/dev_test.go:314]:
```suggestion
			name: "manifest has one dev section and user introduces empty devName",
```

File: cmd/utils/dev_test.go [hunk 2]
```diff
@@ -310,6 +310,29 @@ func Test_GetDevFromManifest(t *testing.T) {
...
+				Dev: model.ManifestDevs{
+					"test": &model.Dev{},
+				},
+			},
+			devName: "",
+			dev:     &model.Dev{},
+			err:     nil,
+		},
+		{
+			name: "manifest has several dev section user introduces emtpy devName",
```
Comment (jLopezbarb) [inline cmd/utils/dev_test.go:325]:
```suggestion
			name: "manifest has several dev section user introduces empty devName",
```

File: cmd/utils/dev.go [hunk 3]
```diff
@@ -162,19 +168,24 @@ func GetDevFromManifest(manifest *model.Manifest, devName string) (*model.Dev, e
...
 		}
+		options = append(options, k)
+	}
+	return nil, oktetoErrors.UserError{
+		E:    fmt.Errorf(oktetoErrors.ErrDevContainerNotExists, devName),
+		Hint: fmt.Sprintf("Available options are: [%s]", strings.Join(options, ", ")),
 	}
+}
+
+func SelectDevFromManifest(manifest *model.Manifest, label string) (*model.Dev, error) {
```
Comment (ifbyol) [inline cmd/utils/dev.go:188]: Can you include a comment in this exported function, please?

**Review by ifbyol — COMMENTED** [review]
@rlamana @RinkiyaKeDad Can you review the text for the elector on each situation, please?

File: cmd/doctor.go [hunk 4]
```diff
@@ -65,7 +66,13 @@ func Doctor() *cobra.Command {
 			}
 			dev, err := utils.GetDevFromManifest(manifest, devName)
 			if err != nil {
-				return err
+				if !errors.Is(err, utils.ErrNoDevSelected) {
+					return err
+				}
+				dev, err = utils.SelectDevFromManifest(manifest, "Select the development container you want download logs:")
```
Comment (RinkiyaKeDad) [inline cmd/doctor.go:72]:
```suggestion
				dev, err = utils.SelectDevFromManifest(manifest, "Select which development container's logs to download:")
```

File: cmd/down.go [hunk 5]
```diff
@@ -78,7 +79,13 @@ func Down() *cobra.Command {
 				}
 				dev, err := utils.GetDevFromManifest(manifest, devName)
 				if err != nil {
-					return err
+					if !errors.Is(err, utils.ErrNoDevSelected) {
+						return err
+					}
+					dev, err = utils.SelectDevFromManifest(manifest, "Select the development container you want to deactivate:")
```
Comment (RinkiyaKeDad) [inline cmd/down.go:85]:
```suggestion
					dev, err = utils.SelectDevFromManifest(manifest, "Select which development container to deactivate:")
```

File: cmd/exec.go [hunk 6]
```diff
@@ -191,15 +192,17 @@ func getDevFromArgs(manifest *model.Manifest, args []string) (*model.Dev, error)
...
+	}
+
+	dev, err := utils.GetDevFromManifest(manifest, devName)
+	if err != nil {
+		if !errors.Is(err, utils.ErrNoDevSelected) {
 			return nil, err
 		}
-	} else {
-		dev, err = utils.GetDevFromManifest(manifest, args[0])
+		dev, err = utils.SelectDevFromManifest(manifest, "Select the development container where you want to exec:")
```
Comment (RinkiyaKeDad) [inline cmd/exec.go:205]:
```suggestion
		dev, err = utils.SelectDevFromManifest(manifest, "Select which development container to exec:")
```

File: cmd/push.go [hunk 7]
```diff
@@ -98,7 +99,13 @@ func Push(ctx context.Context) *cobra.Command {
 			}
 			dev, err := utils.GetDevFromManifest(manifest, devName)
 			if err != nil {
-				return err
+				if !errors.Is(err, utils.ErrNoDevSelected) {
+					return err
+				}
+				dev, err = utils.SelectDevFromManifest(manifest, "Select the development container where you want to push:")
```
Comment (RinkiyaKeDad) [inline cmd/push.go:105]:
```suggestion
				dev, err = utils.SelectDevFromManifest(manifest, "Select which development container to push to:")
```

File: cmd/restart.go [hunk 8]
```diff
@@ -58,7 +59,13 @@ func Restart() *cobra.Command {
 			}
 			dev, err := utils.GetDevFromManifest(manifest, devName)
 			if err != nil {
-				return err
+				if !errors.Is(err, utils.ErrNoDevSelected) {
+					return err
+				}
+				dev, err = utils.SelectDevFromManifest(manifest, "Select the development container you want to restart:")
```
Comment (RinkiyaKeDad) [inline cmd/restart.go:65]:
```suggestion
				dev, err = utils.SelectDevFromManifest(manifest, "Select which development container to restart:")
```

File: cmd/status.go [hunk 9]
```diff
@@ -62,7 +63,13 @@ func Status() *cobra.Command {
 			}
 			dev, err := utils.GetDevFromManifest(manifest, devName)
 			if err != nil {
-				return err
+				if !errors.Is(err, utils.ErrNoDevSelected) {
+					return err
+				}
+				dev, err = utils.SelectDevFromManifest(manifest, "Select the development container you want to get sync status:")
```
Comment (RinkiyaKeDad) [inline cmd/status.go:69]:
```suggestion
				dev, err = utils.SelectDevFromManifest(manifest, "Select which development container's sync status is needed:")
```

File: cmd/up/up.go [hunk 10]
```diff
@@ -262,7 +262,13 @@ func Up() *cobra.Command {
 
 			dev, err := utils.GetDevFromManifest(oktetoManifest, upOptions.DevName)
 			if err != nil {
-				return err
+				if !errors.Is(err, utils.ErrNoDevSelected) {
+					return err
+				}
+				dev, err = utils.SelectDevFromManifest(oktetoManifest, "Select the development container you want to activate:")
```
Comment (RinkiyaKeDad) [inline cmd/up/up.go:268]:
```suggestion
				dev, err = utils.SelectDevFromManifest(oktetoManifest, "Select which development container to activate:")
```

**Review by RinkiyaKeDad — COMMENTED** [review]
I've added suggestions for the messages. 

Another thing I was thinking was that we could just change all the messages to "Select a development container:" - since the user running the command would know from the command itself what exactly they are selecting the container for. What do you all think?

**Comment by teresaromero** [comment]
> I've added suggestions for the messages.
> 
> Another thing I was thinking was that we could just change all the messages to "Select a development container:" - since the user running the command would know from the command itself what exactly they are selecting the container for. What do you all think?

Thnks for the suggestions! I've fixed the strings accordingly. 

Regarding the message, i think adding the action that is being performed, although the user knows from the command, is more descriptive.

**Review by ifbyol — APPROVED** [review]
