### PR TITLE
switch to personal namespace if previous namespace is missing

### LINKED ISSUE #3334: Can't switch to previous context with non existent / deleted namespace
**Describe the bug**
When using `okteto context` or `okteto context use CONTEXT_NAME`, I can't switch back to an Okteto Cluster context that points to a non existent or deleted namespace.

That namespace may have been created from a CLI instance and deleted from somewhere else, such as a different CLI instance or Okteto UI.

I need to run `okteto context delete CONTEXT_NAME` to delete the context and `okteto context` or `okteto context use CONTEXT_NAME` to create it again.

**To Reproduce**

1. Use `okteto context` or `okteto context use CONTEXT_NAME` to switch to an Okteto Cluster context.
2. Create a namespace with `okteto namespace` or `okteto namespace create NAMESPACE_NAME`.
3. Switch to a different context (any type) with `okteto context` or `okteto context use CONTEXT_NAME`.
4. Delete the namespace created in the 2nd step from a different CLI instance or Okteto UI.
5. Try to switch back to the context used in the 1st step with `okteto context` or `okteto context use CONTEXT_NAME`
6. See the error (attached below).

**Expected behavior**
I expect a warning about the namespace not being found and switch by default to my personal namespace.

**Desktop (please complete the following information):**

- OS: macOS arm64
- Version 2.11.0

**Additional context**

Error:

```
% okteto context
 ✓  Context 'https://cloud.okteto.com' selected
 x  Namespace 'foo-jpf-okteto' not found on context 'https://cloud.okteto.com'
    Please verify that the namespace exists and that you have access to it.
```

### PR DESCRIPTION
**Pull request by miniscruff**
# Proposed changes

Fixes #3334

Add a new value to context options indicating if the command originated from `ctx` or `ns`.
If switching context, and we do not have access to the previous namespace, switch to our personal one instead of crashing.

### CODE REVIEW

File: cmd/context/create.go [hunk 1]
```diff
@@ -172,8 +172,19 @@ func (c *ContextCommand) UseContext(ctx context.Context, ctxOptions *ContextOpti
 			return err
 		}
 
-		if !hasAccess {
-			return oktetoErrors.UserError{E: fmt.Errorf("namespace '%s' not found on context '%s'", ctxOptions.Namespace, ctxOptions.Context),
+		// if using a new context, our cached namespace may have been removed
+		// so swap over to the personal namespace instead of erroring
+		if !hasAccess && !ctxOptions.FromNamespace {
+			oktetoLog.Success(
```
Comment (jLopezbarb) [inline cmd/context/create.go:178]: Could you provide a screenshoot of how this looks like?

I guess we should be using `oktetoLog.Warning` here, but I want to see how it looks like

Comment (miniscruff) [reply cmd/context/create.go:178]: Sure, here is the before and after.
image

Comment (miniscruff) [reply cmd/context/create.go:178]: I can swap over logging levels if you want

Comment (AgustinRamiroDiaz) [reply cmd/context/create.go:178]: Yeah I agree with @jLopezbarb , I think we should show a `Warning` or `Info` here

File: cmd/context/create.go [hunk 2]
```diff
@@ -172,8 +172,19 @@ func (c *ContextCommand) UseContext(ctx context.Context, ctxOptions *ContextOpti
 			return err
 		}
 
-		if !hasAccess {
-			return oktetoErrors.UserError{E: fmt.Errorf("namespace '%s' not found on context '%s'", ctxOptions.Namespace, ctxOptions.Context),
+		// if using a new context, our cached namespace may have been removed
+		// so swap over to the personal namespace instead of erroring
+		if !hasAccess && !ctxOptions.FromNamespace {
```
Comment (AgustinRamiroDiaz) [inline cmd/context/create.go:177]: can we simplify the boolean logic here? maybe something like:
```
if !hasAccess {
  if ctxOptions.FromNamespace {
    // Return error here
  }
  // Handle default here
}
```

File: cmd/context/options.go [hunk 3]
```diff
@@ -31,6 +31,7 @@ type ContextOptions struct {
 	Show                  bool
 	Save                  bool
 	IsCtxCommand          bool
+	FromNamespace         bool
```
Comment (AgustinRamiroDiaz) [inline cmd/context/options.go:34]: I find this tied to the cobra command and very specific and hard to reuse. What do you think about using a `DefaultNamespace string` property instead? That way it has an independent meaning from the command and can be reused.

Then in the error message we'd say "Couldn't access namespace ..., defaulting to ..."

**Review by AgustinRamiroDiaz — COMMENTED** [review]
Thanks for your contribution! Code looks good overall :rocket:

File: cmd/context/create.go (hunk 1 above)
Comment (jLopezbarb) [reply cmd/context/create.go:178]: I think we should replace it with a warning message. I think that using success hides the meaning of the message, which is that the user should know why we are redirecting him to his personal namespace. WDYT?

File: cmd/context/options.go (hunk 3 above)
Comment (jLopezbarb) [reply cmd/context/options.go:34]: @AgustinRamiroDiaz This option is to know if the command is executed from the namespace command instead of the context one. It's the same as `IsCtxCommand`, `show` or `save`. 

If we use `DefaultNamespace` with the name of the personal namespace only when it's a namespace command it's not obvious and will be reused in a wrong way. 

We'd need to rethink how the `namespace` and `context` command are written but right now there is no plans to do it, so the least intrusive way to do it I think is this one. WDYT?

**Comment by AgustinRamiroDiaz** [comment]
@miniscruff we should also handle the `FromNamespace` context option in https://github.com/okteto/okteto/blob/259e9f674e0178cfc83a75fb59845dc40164afab/cmd/context/use.go#L84

File: cmd/context/options.go (hunk 3 above)
Comment (AgustinRamiroDiaz) [reply cmd/context/options.go:34]: hmmm yeah that's a good point. I felt like we could improve it but you are right, it'll get misused if the name is `DefaultNamespace`. I still feel that it's not a good abstraction, but to change it we'd need to rethink the whole command to have more composable pieces instead of one big command.

I still think that we should rename it since in the comment below we'd be using it in the context command too

Comment (jLopezbarb) [reply cmd/context/options.go:34]: We could name it `checkIfHasAccessToNamespace` or something like this. WDYT?

Comment (miniscruff) [reply cmd/context/options.go:34]: Yea that makes sense, let me change that around

**Comment by miniscruff** [comment]
> 



> @miniscruff I think we should also handle the `FromNamespace` context option in
> 
> https://github.com/okteto/okteto/blob/259e9f674e0178cfc83a75fb59845dc40164afab/cmd/context/use.go#L84

Right, we would also need to check it if you supplied the namespace, in which case backing off would be appropriate, gotcha.

File: cmd/context/options.go (hunk 3 above)
Comment (miniscruff) [reply cmd/context/options.go]: I used `CheckNamespaceAccess`, let me know if that works

File: cmd/context/create.go (hunk 2 above)
Comment (miniscruff) [reply cmd/context/create.go]: Done

File: cmd/context/create.go (hunk 1 above)
Comment (miniscruff) [reply cmd/context/create.go]: Done

File: cmd/context/options.go (hunk 3 above)
Comment (jLopezbarb) [reply cmd/context/options.go]: That's perfect

**Review by AgustinRamiroDiaz — APPROVED** [review]
Changes look good! Deferring merge to @jLopezbarb

**Review by jLopezbarb — APPROVED** [review]
