### PR TITLE
Copy using io.Copy instead of os.Rename

### LINKED ISSUE #731: download syncthing fails if /tmp is in a different partition
```
time="2020-02-29T18:15:51+01:00" level=info msg="failed to download syncthing, retrying: failed to move /tmp/880728758/syncthing-linux-amd64-v1.3.4/syncthing to /home/$USER/.okteto/syncthing: rename /tmp/880728758/syncthing-linux-amd64-v1.3.4/syncthing /home/$USER/.okteto/syncthing: invalid cross-device link" action=d9ad0f48-a753-49fd-a536-ea70042249fa version=1.7.4
```

### PR DESCRIPTION
**Pull request by rberrelleza**
Fixes #731

### CODE REVIEW

File: pkg/model/utils_test.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+	}
+
+	defer os.RemoveAll(dir)
+
+	p := filepath.Join(dir, "exists")
+	if FileExists(p) {
+		t.Errorf("fail to detect non-existing file")
+	}
+
+	if err := ioutil.WriteFile(p, []byte("hello-world"), 600); err != nil {
```
Comment (golangcibot) [inline pkg/model/utils_test.go]: SA9002: file mode '600' evaluates to 01130; did you mean '0600'? (from `staticcheck`)

Comment (golangcibot) [inline pkg/model/utils_test.go]: SA9002: file mode '600' evaluates to 01130; did you mean '0600'? (from `staticcheck`)

**Comment by feitian124** [comment]
thanks , i happen to met this issue , after upgrade it is fine now.
