### PR TITLE
Panic secret not valid

### LINKED ISSUE #3958: Panic when `secret` is not valid string
**Describe the bug**
When running `okteto build` with an invalid format for the secret string, a panic is returned

Found while testing some scenarios on okteto build command:

```
running: okteto build --progress plain --secret secret
 i  Using teresa @ - as context
 i  Building 'Dockerfile' in -:443...
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/okteto/okteto/pkg/cmd/build.parseTempSecrets({0x140015bfad0, 0x23}, 0x14001048c80)
	github.com/okteto/okteto/pkg/cmd/build/build.go:418 +0x47c
github.com/okteto/okteto/pkg/cmd/build.(*OktetoBuilder).buildWithOkteto(0x4d?, {0x103756b60, 0x1050c1320}, 0x14001048c80)
	github.com/okteto/okteto/pkg/cmd/build/build.go:132 +0x3dc
github.com/okteto/okteto/pkg/cmd/build.(*OktetoBuilder).Run(0x1400154c1a0?, {0x103756b60, 0x1050c1320}, 0x14001048c80)
	github.com/okteto/okteto/pkg/cmd/build/build.go:66 +0x150
github.com/okteto/okteto/cmd/build/v1.(*OktetoBuilder).Build(0x14001688000, {0x103756b60, 0x1050c1320}, 0x14001048c80)
	github.com/okteto/okteto/cmd/build/v1/build.go:104 +0x320
github.com/okteto/okteto/cmd/build/v2.(*OktetoBuilder).buildSvcFromDockerfile(0x14001684000, {0x103756b60, 0x1050c1320}, 0x14001570000, {0x14001552b85, 0xb}, 0x140004b83c0)
	github.com/okteto/okteto/cmd/build/v2/build.go:249 +0x274
github.com/okteto/okteto/cmd/build/v2.(*OktetoBuilder).buildService(0x103743c08?, {0x103756b60, 0x1050c1320}, 0x14001570000, {0x14001552b85, 0xb}, 0x10371ba00?)
	github.com/okteto/okteto/cmd/build/v2/build.go:224 +0xa8
github.com/okteto/okteto/cmd/build/v2.(*OktetoBuilder).Build(0x14001684000, {0x103756b60, 0x1050c1320}, 0x140004b83c0)
	github.com/okteto/okteto/cmd/build/v2/build.go:184 +0x888
github.com/okteto/okteto/cmd/build.Build.func1(0x140013eac00?, {0x140013b5800?, 0x4?, 0x10262377e?})
	github.com/okteto/okteto/cmd/build/command.go:105 +0x2cc
github.com/spf13/cobra.(*Command).execute(0x14000248780, {0x140013b57c0, 0x4, 0x4})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x560
github.com/spf13/cobra.(*Command).ExecuteC(0x1400032e500)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x318
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	github.com/okteto/okteto/main.go:156 +0x9e8

```

**To Reproduce**

1. Go to any repository, for example `go-getting-started`
1. Use the build command with the `--secret` flag and use a format not compliant
1. A panic is returned

**Expected behavior**
A clean message of error explaining the format of the secret input

**Additional context**

Found the line throwing the panic https://github.com/okteto/okteto/blob/master/pkg/cmd/build/build.go#L419 
We should check if the Split done previously has indeed valid output and not `nil`

### PR DESCRIPTION
**Pull request by teresaromero**
# Proposed changes

Fixes #3958 

When a secret string was not valid, we where throwing a panic. This PR refactors how we extract the information on the secret string, returning an error if this is not valid.

EDIT: Approach to validate the secret string has change into using the csv reader as build.ParseSecret function https://github.com/moby/buildkit/blob/a14b4e097ae1dc7514c5febd6d75f742a166ea75/cmd/buildctl/build/secret.go#L29C1-L29C1 

## How to validate

Following the steps at the issue, testing the input of secrets work as expected and throw an error instead of a panic when secret string is not valid

## CLI Quality Reminders 🔧

For both authors and reviewers:

- Scrutinize for potential regressions
- Ensure key automated tests are in place
- Build the CLI and test using the validation steps
- Assess Developer Experience impact (log messages, performances, etc)
- If too broad, consider breaking into smaller PRs
- Adhere to our [code style](https://github.com/okteto/okteto/blob/master/docs/code-style.md) and [code review](https://github.com/okteto/okteto/blob/master/docs/code-review.md) guidelines

### CODE REVIEW

**Comment by andreafalzetti** [comment]
@teresaromero could you add steps I can follow to validate the change please?

File: pkg/cmd/build/build.go [hunk 1]
```diff
@@ -457,7 +480,7 @@ func parseTempSecrets(secretTempFolder string, buildOptions *types.BuildOptions)
 		}
 
 		// replace src
-		buildOptions.Secrets[indx] = fmt.Sprintf("%ssrc=%s", splitSecret[0], tmpfile.Name())
```
Comment (AdrianPedriza) [inline pkg/cmd/build/build.go:460]: is this another bug?

**Comment by AdrianPedriza** [comment]
Captura de Pantalla 2023-09-21 a las 12 16 46
bug fixed! but a couple of things come to my mind:
- nit: could we move secrets validation before start building logic about svc? It is weird to read an error that seems to be related to the service `Error building service 'hello-world': secret should have an id` I don't know if it implies too much effort.
- nit: should we return a UserError with a hint about supported format (`id=mysecret,src=/local/secret`)? In the example we are saying that secrets needs and `id` but it also needs an `src` field

**Review by AdrianPedriza — APPROVED** [review]
LGTM but I've a couple of suggestions/doubts but not blockers

File: pkg/cmd/build/build.go (hunk 1 above)
Comment (teresaromero) [reply pkg/cmd/build/build.go:460]: the variables use to form the string are changed now. for grabbing the ID i not use secretID so i changed the string format for the template too. this is part of the bug fix

File: pkg/cmd/build/build.go [hunk 2]
```diff
@@ -405,19 +405,42 @@ func GetVolumesToInclude(volumesToInclude []model.StackVolume) []model.StackVolu
 	return result
 }
 
+// parseSecretFromString returns id and src from the given secret string
+// format should be id=<name>,src=<source file>
+// if no id or src if found, error is returned
```
Comment (andreafalzetti) [inline pkg/cmd/build/build.go:410]:
```suggestion
// if no id or src is found, error is returned
```

**Review by andreafalzetti — APPROVED** [review]

**Comment by teresaromero** [comment]
@andreafalzetti @AdrianPedriza i've updated the PR with a refactor on how to parse and validate the secrets.

File: pkg/cmd/build/build.go [hunk 3]
```diff
@@ -405,60 +410,74 @@ func GetVolumesToInclude(volumesToInclude []model.StackVolume) []model.StackVolu
...
+			key, value, found := strings.Cut(field, "=")
+			if !found {
+				return fmt.Errorf("secret format error")
 			}
 
-			// save expanded to temp file
-			_, err = writer.Write([]byte(fmt.Sprintf("%s\n", srcContent)))
-			if err != nil {
-				return fmt.Errorf("unable to write to temp file: %s", err)
+			if key == "src" || key == "source" {
```
Comment (andreafalzetti) [inline pkg/cmd/build/build.go:433]: Should this be `&&`?

File: pkg/cmd/build/build.go [hunk 4]
```diff
@@ -130,8 +132,11 @@ func (ob *OktetoBuilder) buildWithOkteto(ctx context.Context, buildOptions *type
 	defer os.RemoveAll(secretTempFolder)
```
Comment (andreafalzetti) [inline pkg/cmd/build/build.go:132]: I know it's not part of the change but perhaps it could be a quick win, if we make the folder name random too, we allow running multiple builds using the `--secret` flag. At the moment if I start two builds in parallel using `--secret`, the first that completes will wipe out the `.secret` folder

File: pkg/cmd/build/build.go (hunk 3 above)
Comment (teresaromero) [reply pkg/cmd/build/build.go:433]: its source or src indicating the source of the secret, i guess is OR since the two wont be able to exist at the same time

**Comment by AdrianPedriza** [comment]
I guess that if I run following steps to repro `okteto build --progress plan --secret secret` is correct to obtain
Captura de Pantalla 2023-09-26 a las 10 46 46
Nothing related with secrets parsing error, right? because is not allow use flags in that case. So I think is good..?
On the other hand one thing weird for me is that we are not displaying the hint:
Captura de Pantalla 2023-09-26 a las 10 48 25

**Comment by teresaromero** [comment]
> I guess that if I run following steps to repro `okteto build --progress plan --secret secret` is correct to obtain

This is correct as the secrets are either aet at the manifest or for single service as cmd flag...

the second one i am missing the hint.... 🤔 

the code is returning userError..

```
`	if err := replaceSecretsSourceEnvWithTempFile(afero.NewOsFs(), secretTempFolder, buildOptions); err != nil {
		return oktetoErrors.UserError{
			E:    err,
			Hint: "secret should have the format 'id=mysecret,src=/local/secret' where source exists as local file",
		}
	}`
```

why does the hint not show?

File: pkg/cmd/build/build.go (hunk 4 above)
Comment (teresaromero) [reply pkg/cmd/build/build.go:132]: I think this should be filed into an improvement issue. This can clash with how this feature works so lets file an issue. Can you add it?

File: pkg/cmd/build/build_test.go [hunk 5]
```diff
@@ -590,37 +590,221 @@ func removeFile(s string) error {
 	return nil
 }
 
-func Test_parseTempSecrets(t *testing.T) {
-	secretDir := t.TempDir()
-	tmpTestSecretFile, err := os.CreateTemp(secretDir, "")
+func Test_replaceSecretsSourceEnvWithTempFile(t *testing.T) {
+	t.Parallel()
```
Comment (andreafalzetti) [inline pkg/cmd/build/build_test.go:594]: Should we move `t.Parallel()` in the sub-test?

**Comment by AdrianPedriza** [comment]
> > I guess that if I run following steps to repro `okteto build --progress plan --secret secret` is correct to obtain
> 
> This is correct as the secrets are either aet at the manifest or for single service as cmd flag...
> 
> the second one i am missing the hint.... 🤔
> 
> the code is returning userError..
> 
> ```
> `	if err := replaceSecretsSourceEnvWithTempFile(afero.NewOsFs(), secretTempFolder, buildOptions); err != nil {
> 		return oktetoErrors.UserError{
> 			E:    err,
> 			Hint: "secret should have the format 'id=mysecret,src=/local/secret' where source exists as local file",
> 		}
> 	}`
> ```
> 
> why does the hint not show?

I guess something out of the scope of the issue is happening. We have an issue to focus on that https://github.com/okteto/okteto/issues/3996 so it is OK

**Review by AdrianPedriza — APPROVED** [review]

**Review by jLopezbarb — APPROVED** [review]
