### PR TITLE
Syncthing running on its own stateful set

### LINKED ISSUE #217: Redirect syncthing and okteto init logs to a file to not pollute app pod logs
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**
Add any other context about the problem here (e.g cnd.yml, k8s manifests, logs)

### PR DESCRIPTION
**Pull request by pchico83**
Closes #217 #271 #264

### CODE REVIEW

File: pkg/k8s/code/crud.go [hunk 1]
```diff
@@ -0,0 +1,71 @@
+package code
```
Comment (rberrelleza) [inline pkg/k8s/code/crud.go]: code?

File: pkg/k8s/code/crud.go [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+	"github.com/okteto/okteto/pkg/model"
+
+	appsv1 "k8s.io/api/apps/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/client-go/kubernetes"
+)
+
+var devTerminationGracePeriodSeconds int64
+
+//Deploy creates or updates a database
```
Comment (rberrelleza) [inline pkg/k8s/code/crud.go]: I think this docstring should say something different?

File: pkg/k8s/code/crud.go [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+		if err := create(ss, c); err != nil {
+			return err
+		}
+	}
+	return nil
+}
+
+func exists(ss *appsv1.StatefulSet, c *kubernetes.Clientset) bool {
+	ss, err := c.AppsV1().StatefulSets(ss.Namespace).Get(ss.Name, metav1.GetOptions{})
+	if err != nil {
```
Comment (rberrelleza) [inline pkg/k8s/code/crud.go]: I've seen a Get on deployments return a 'not-found' error instead of an empty name. do we need to check for that here as well?

File: pkg/k8s/code/crud.go [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+	log.Infof("code statefulset '%s' updated", ss.Name)
+	return nil
+}
+
+// Destroy destroys a database
+func Destroy(dev *model.Dev, c *kubernetes.Clientset) error {
+	log.Infof("destroying code statefulset '%s' ...", dev.Name)
+	sfsClient := c.AppsV1().StatefulSets(dev.Namespace)
+	if err := sfsClient.Delete(dev.Name, &metav1.DeleteOptions{GracePeriodSeconds: &devTerminationGracePeriodSeconds}); err != nil {
+		if strings.Contains(err.Error(), "not found") {
```
Comment (rberrelleza) [inline pkg/k8s/code/crud.go]: I think this is missing a `!` in the condition?

File: pkg/k8s/code/translate.go [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+)
+
+func translate(dev *model.Dev) *appsv1.StatefulSet {
+	initContainer := translateInitContainer(dev)
+
+	reqMem, _ := resource.ParseQuantity("64Mi")
+	reqCPU, _ := resource.ParseQuantity("50m")
+	limMem, _ := resource.ParseQuantity("256Mi")
+	limCPU, _ := resource.ParseQuantity("200m")
+	ss := &appsv1.StatefulSet{
```
Comment (rberrelleza) [inline pkg/k8s/code/translate.go]: Why statefulspec vs deployment? (or even a pod directly)

File: pkg/k8s/code/translate.go [hunk 6]
```diff
@@ -0,0 +1,164 @@
...
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      dev.Name,
```
Comment (rberrelleza) [inline pkg/k8s/code/translate.go]: I think we should prefix it with okteto, so it's obvious we created it.

File: pkg/k8s/code/crud.go (hunk 1 above)
Comment (pchico83) [reply pkg/k8s/code/crud.go]: any other idea? 
it is the package that creates the remote synthing stateful set, and manages it

File: pkg/k8s/code/translate.go (hunk 5 above)
Comment (pchico83) [reply pkg/k8s/code/translate.go]: it is for pods that do now play well with restarts, and they usually mount volumes. it is a better fit for this case.

File: pkg/k8s/code/translate.go (hunk 6 above)
Comment (pchico83) [reply pkg/k8s/code/translate.go]: ok

File: pkg/k8s/code/crud.go (hunk 1 above)
Comment (pchico83) [reply pkg/k8s/code/crud.go]: moved to `/syncthing/k8s/`
