### PR TITLE
fix: nil pointer when okteto manifest is created

### LINKED ISSUE #2628: got a nilref when creating a new manifest
**Describe the bug**
image

**To Reproduce**

1. Clone https://github.com/rberrelleza/angular-ngrx-nx-realworld-example-app/
2. Run okteto up
3. Say `y` on the stignore step

**Desktop (please complete the following information):**

- OS: macOS
- Version 2.2.1

### PR DESCRIPTION
**Pull request by AdrianPedriza**
Fixes #2628

## Proposed changes

- Set default values in manifest.dev to avoid nil pointer
- update local folder path to use a rel path if an abs path is given

### CODE REVIEW

**Review by AgustinRamiroDiaz — APPROVED** [review]
Which property was raising the nilref? Can we change so it's not a pointer?

File: cmd/up/up.go [hunk 1]
```diff
@@ -376,6 +374,23 @@ func LoadManifestWithInit(ctx context.Context, k8sContext, namespace, devPath st
...
+		manifest.Context = okteto.Context().Name
+	}
+	manifest.IsV2 = true
+	for devName, d := range manifest.Dev {
+		if err := d.SetDefaults(); err != nil {
+			return nil, err
+		}
+		d.Name = devName
+		d.Namespace = manifest.Namespace
+		d.Context = manifest.Context
```
Comment (ifbyol) [inline cmd/up/up.go:391]: Not sure if possible, but should we check if they have a different value than the one in the manifest?

**Review by ifbyol — APPROVED** [review]
