### PR TITLE
'okteto login showUrl' shows url, instead open browser

### LINKED ISSUE #615: okteto login does not open browser or shows url
**Describe the bug**
`okteto login` in wsl does not open a browser and does not show the url. 

**To Reproduce**
1. run `okteto login`
2. wait and nothing happens, eventually timeout

**Expected behavior**
Should open a browser or show the url to login. That could be pasted in browser.

**Desktop (please complete the following information):**
 - Windows 10, wsl2

**Additional context**

### PR DESCRIPTION
**Pull request by kivi**
Fixes #615
also outputs the login url on cli, because on wsl2 a browser did not open and login timed out..

## Proposed changes
- typing `okteto login [url]`
Results into:

> Authentication will continue in your default browser
> You can also open a browser and navigate to the following address: https://cloud.okteto.com/github/authorization-code?redirect=someEncodedRedirectUrl
>  ✓  Logged in as loginname
>     Run `okteto namespace` to switch your context and download your Kubernetes credentials.
> 
>

### CODE REVIEW

File: cmd/login.go [hunk 1]
```diff
@@ -20,22 +20,28 @@ import (
 
 //Login starts the login handshake with github and okteto
 func Login() *cobra.Command {
+	showUrl := false
 	cmd := &cobra.Command{
 		Use:   "login [url]",
```
Comment (kivi) [inline cmd/login.go]: Maybe some improvement in usage could be helpful? But how would that look like?
`Use:   "login [url|'showUrl']",`

File: cmd/login.go [hunk 2]
```diff
@@ -61,9 +67,10 @@ func Login() *cobra.Command {
 
 			authorizationURL := buildAuthorizationURL(handler.baseURL, handler.state, port)
 			fmt.Println("Authentication will continue in your default browser")
-			if err := open.Start(authorizationURL); err != nil {
-				fmt.Printf("Please open a browser and navigate to the following address:\n")
-				fmt.Println(authorizationURL)
+			if showUrl {
```
Comment (kivi) [inline cmd/login.go]: simple if condition1 or condition2 could help. But did not work with my lack of knowledge of Go.

File: cmd/login.go (hunk 1 above)
Comment (rberrelleza) [reply cmd/login.go]: I think we should always show the URL and not have the option. This is a pattern that other CLIs use as well.

File: cmd/login.go [hunk 3]
```diff
@@ -138,6 +145,11 @@ func randToken() string {
 	return base64.StdEncoding.EncodeToString(b)
 }
 
+func showAuthorizationURL() {
```
Comment (rberrelleza) [inline cmd/login.go]: this function is missing the parameter.
```suggestion
func showAuthorizationURL(authorizationURL string) {
```

File: cmd/login.go [hunk 4]
```diff
@@ -138,6 +145,11 @@ func randToken() string {
...
+	fmt.Printf("Please open a browser and navigate to the following address:\n")
```
Comment (rberrelleza) [inline cmd/login.go]:
```suggestion
	fmt.Printf("You can also open a browser and navigate to the following address:\n")
```

File: cmd/login.go (hunk 1 above)
Comment (kivi) [reply cmd/login.go]: alrights. sound better.

File: cmd/login.go [hunk 5]
```diff
@@ -61,10 +61,9 @@ func Login() *cobra.Command {
 
 			authorizationURL := buildAuthorizationURL(handler.baseURL, handler.state, port)
 			fmt.Println("Authentication will continue in your default browser")
-			if err := open.Start(authorizationURL); err != nil {
-				fmt.Printf("Please open a browser and navigate to the following address:\n")
-				fmt.Println(authorizationURL)
-			}
+			open.Start(authorizationURL)
+			fmt.Printf("You can also open a browser and navigate to the following address: ")
```
Comment (kivi) [inline cmd/login.go]: I removed the new line. Looks better to me, but we can add that newline if it helps.

File: cmd/login.go [hunk 6]
```diff
@@ -61,10 +61,9 @@ func Login() *cobra.Command {
 
 			authorizationURL := buildAuthorizationURL(handler.baseURL, handler.state, port)
 			fmt.Println("Authentication will continue in your default browser")
-			if err := open.Start(authorizationURL); err != nil {
-				fmt.Printf("Please open a browser and navigate to the following address:\n")
-				fmt.Println(authorizationURL)
-			}
+			open.Start(authorizationURL)
```
Comment (golangcibot) [inline cmd/login.go]: Error return value of `open.Start` is not checked (from `errcheck`)

Comment (kivi) [reply cmd/login.go]: Thanks bot! @rberrelleza, how to check that on my local computer, before I commit&push. Do your have a link for a tutorial by chance?

Comment (rberrelleza) [reply cmd/login.go]: Run `make lint` . You need to have `golangci-lint` available in your $PATH (https://github.com/golangci/golangci-lint#install).

We don't have a doc on this, I'll update the contributor guide to include it.

**Comment by rberrelleza** [comment]
Thanks for the contribution!
