### PR TITLE
Remove git credentials from debug logs

### LINKED ISSUE #3560: remove git credentials from logs
**Describe the bug**
If I run a command using `-l=debug`, logs will display git credentials. In order to debug issues is not safe to display this information with them. This credential are in the repo URL -> https://github.com/okteto/okteto/blob/master/pkg/devenvironment/name.go#L85

### PR DESCRIPTION
**Pull request by teresaromero**
# Proposed changes

Fixes #3560 

In order to display de repo url without user information, new method attached to `Repository` and use it for displying the logs.

### CODE REVIEW

**Review by andreafalzetti — APPROVED** [review]
LGTM

File: pkg/repository/repository.go [hunk 1]
```diff
@@ -89,3 +89,18 @@ func (r Repository) IsEqual(otherRepo Repository) bool {
 func cleanPath(path string) string {
 	return strings.TrimSuffix(strings.TrimPrefix(path, "/"), ".git")
 }
+
+// GetAnonymizedRepo returns a clean repo url string without sensible information
+func (r Repository) GetAnonymizedRepo() string {
```
Comment (pchico83) [inline pkg/repository/repository.go:94]: would be possible to overwrite the `String()` method? or would it have other side effects? if it's possible, we would make sure the credentials are never printed

Comment (teresaromero) [reply pkg/repository/repository.go:94]: you mean url.URL.String() in this package? the url prop for Repository is private so it will need a method to expose it, not sure i understand the benefits

Comment (pchico83) [reply pkg/repository/repository.go:94]: The current solution is error-prone in the sense that it's very easy to print `url.URL.String()` for a new developer and expose the credentials. If `Repository` has a `String` method that masks the credentials, no one will be able to print the credentials. Ideally, that means `URL` will be private

Comment (teresaromero) [reply pkg/repository/repository.go:94]: `Repository` struct has already private url, so this is the only method exposing the url, and removing the user information if it has.

I will take a look and make some changes

Comment (teresaromero) [reply pkg/repository/repository.go:112]: updated code with changes

File: pkg/devenvironment/name.go [hunk 2]
```diff
@@ -82,12 +82,12 @@ func (n NameInferer) InferNameFromDevEnvsAndRepository(ctx context.Context, repo
 		optsRepo := repository.NewRepository(repoURL)
 		cmapRepo := repository.NewRepository(repo)
 		if !optsRepo.IsEqual(cmapRepo) {
-			oktetoLog.Infof("configmap %s with repo %s doesn't match with found repo %s", cmap.Name, repo, repoURL)
+			oktetoLog.Infof("configmap %s with repo %s doesn't match with found repo %s", cmap.Name, cmapRepo.GetAnonymizedRepo(), repoURL)
```
Comment (pchico83) [inline pkg/devenvironment/name.go:85]: I was thinking more about something like:
```
oktetoLog.Infof("configmap %s doesn't match with found repo %s", cmap, repoURL)
```
and configmap would have a `String()` method that shows what's needed, for example, the configmap name, repo URL and okteto manifest path, without credentials.
But take it as a suggestion, whatever works better for you

**Review by pchico83 — APPROVED** [review]

File: pkg/repository/repository.go [hunk 3]
```diff
@@ -38,13 +38,31 @@ type repositoryInterface interface {
...
-// NewRepository creates a repository controller
-func NewRepository(path string) Repository {
-	repoUrl, err := giturls.Parse(path)
+type repositoryURL struct {
+	url.URL
+}
+
+// String is a custom implementation for the url where User is removed
+func (r repositoryURL) String() string {
+	r.URL.User = nil
```
Comment (AdrianPedriza) [inline pkg/repository/repository.go:47]: it is safe to do it? if we remove the user from the repo could not be affected future uses about the repository object ? could we work with a copy for this case ?

Comment (teresaromero) [reply pkg/repository/repository.go]: makes sense, updating the PR

Comment (teresaromero) [reply pkg/repository/repository.go]: @AdrianPedriza i've added a test for this function

**Review by AdrianPedriza — APPROVED** [review]
