### PR TITLE
fix: visual bug

### LINKED ISSUE #2821: Minor output issue when selecting the current context again
**Describe the bug**
If you launch okteto context and realized that the current context is the one you wanted and you select it again, the output of the selected context shows the URL of the context but also the `*` symbol that was there to indicate the current context. The `*` shouldn't be there and is a bit confusing:

Screenshot 2022-06-21 at 00 29 09

- Version 2.4.0

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

# Proposed changes

Fixes #2821

- Clean the name(remove the *) after selecting the  context

## Screenshots
Captura de pantalla 2022-09-05 a las 13 39 19

Captura de pantalla 2022-09-05 a las 13 39 27

### CODE REVIEW

**Review by teresaromero — APPROVED** [review]

File: cmd/utils/selector.go [hunk 1]
```diff
@@ -275,8 +275,7 @@ func (s *OktetoSelector) run(initialPosition int) (string, error) {
 		return "", err
 	}
 
-	items, idx := l.Items()
-	item := items[idx]
+	item := strings.TrimSpace(strings.TrimSuffix(s.Items[l.Index()].Name, " *"))
```
Comment (AgustinRamiroDiaz) [inline cmd/utils/selector.go:278]: Wouldn't it be better to not save it with the `*`? We could change the `run` function to not modify the selector Items

Comment (jLopezbarb) [reply cmd/utils/selector.go:278]: We need it to show what's the actual one, and we can't change the behavior of the function
