### PR TITLE
remote output fixes

### LINKED ISSUE #3456: `okteo deploy --remote` output isn't indented properly
**Describe the bug**
When I run `okteto deploy --remote` the output loses the indentation and adds warning icons that doesn't happen with `okteto deploy` local execution.

**To Reproduce**

1. Clone the branch `debug` of https://github.com/okteto/movies-with-helm
1. Run `okteto deploy --remote`
1. The first lines look like this:
```
!  history.go:56: [debug] getting history for release movies
!  upgrade.go:142: [debug] preparing upgrade for movies
...
```
1. The final lines look like this:
```
# Source: movies/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: movies
labels:
helm.sh/chart: movies-0.1.0
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/instance: movies
app.kubernetes.io/version: "1.0.0"
annotations:
dev.okteto.com/generate-host: "true"
spec:
rules:
- http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: frontend
port:
number: 80
- path: /api
pathType: Prefix
backend:
service:
name: api
port:
number: 8080
NOTES:
Success! Your application will be available shortly.
```

**Expected behavior**
The first lines look like this (same output than original command):

```
history.go:56: [debug] getting history for release movies
upgrade.go:142: [debug] preparing upgrade for movies
...
```

and the final lines look like this:

```
# Source: movies/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies
  labels:
    helm.sh/chart: movies-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: movies
    app.kubernetes.io/version: "1.0.0"
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080

NOTES:
Success! Your application will be available shortly.
```

**Additional context**
Double check the output is the same in the Okteto UI, with the same indentation, metadata, and warning symbols.

### PR DESCRIPTION
**Pull request by AdrianPedriza**
## Acceptance criteria
- [x] do not show a warning icon in command output if local deploy doesn't display it
- [x] do not log twice error if stage fails
- [x] add indentation in the UI if the command output has it
# Proposed changes
- do not print as warning errors from command output when using json displayed (the one used in remote deploys)
- do not `trim()` command log
- avoid adding a log in the buffer if it has already been added

## Test scenarios to not log twice same error

Fixes #3456 
- [x] deploy locally works fine using CLI

#### CLI
| Before | After |
|--------|-------|
|  Captura de Pantalla 2023-04-11 a las 14 14 40 | Captura de Pantalla 2023-04-11 a las 14 16 21 |

#### UI 
| Before | After |
|--------|-------|
| Captura de Pantalla 2023-04-12 a las 13 12 15 | Captura de Pantalla 2023-04-12 a las 13 29 59|

- [x] deploy remotely works fine using CLI
#### CLI
| Before | After |
|--------|-------|
| Captura de Pantalla 2023-04-11 a las 14 22 50 | Captura de Pantalla 2023-04-11 a las 14 32 21|

**NOTE: currently master branch already presents a CLI output without `Load manifest` stage**
#### UI 
| Before | After |
|--------|-------|
| Captura de Pantalla 2023-04-11 a las 14 31 17 | Captura de Pantalla 2023-04-11 a las 14 32 48|

- [x] deploy locally works fine using UI

#### UI 
| Before | After |
|--------|-------|
| Captura de Pantalla 2023-04-12 a las 14 09 24| Captura de Pantalla 2023-04-12 a las 14 09 58|

- [x] deploy remotely works fine using UI

#### UI 
| Before | After |
|--------|-------|
| Captura de Pantalla 2023-04-12 a las 14 11 16|Captura de Pantalla 2023-04-12 a las 14 11 39|

## Test scenarios to indent in UI
done in https://github.com/okteto/app/pull/6204

### CODE REVIEW

File: cmd/deploy/cfghandler.go [hunk 1]
```diff
@@ -72,7 +71,6 @@ func (ch *defaultConfigMapHandler) updateConfigMap(ctx context.Context, cfg *api
 		return err
 	}
 	if errMain != nil {
-		oktetoLog.AddToBuffer(oktetoLog.ErrorLevel, errMain.Error())
```
Comment (AdrianPedriza) [inline cmd/deploy/cfghandler.go:75]: log buffer already has this error added. If we add again the error we will see it duplicate

File: cmd/deploy/deploy.go [hunk 2]
```diff
@@ -332,12 +332,14 @@ func (dc *DeployCommand) RunDeploy(ctx context.Context, deployOptions *Options)
 	}
 
 	err = deployer.deploy(ctx, deployOptions)
+	if _, ok := deployer.(*remoteDeployCommand); ok {
```
Comment (AdrianPedriza) [inline cmd/deploy/deploy.go:335]: we need to check if exec is remote or not. If deploy has been executed in remote means the following logic has been already executed in remote machine so we will set err = nil to not log twice command error

File: cmd/deploy/deploy.go [hunk 3]
```diff
@@ -332,12 +332,14 @@ func (dc *DeployCommand) RunDeploy(ctx context.Context, deployOptions *Options)
...
+		err = nil
+	}
 	if err != nil {
 		if err == oktetoErrors.ErrIntSig {
 			return nil
 		}
 		err = oktetoErrors.UserError{E: err}
-		oktetoLog.AddToBuffer(oktetoLog.InfoLevel, err.Error())
```
Comment (AdrianPedriza) [inline cmd/deploy/deploy.go:340]: error has been already added to log buffer

File: cmd/deploy/deploy_test.go [hunk 4]
```diff
@@ -306,7 +305,7 @@ func TestCreateConfigMapWithBuildError(t *testing.T) {
 	err := c.RunDeploy(ctx, opts)
 
 	// we should get a build error because Dockerfile does not exist
-	assert.Error(t, err)
+	assert.True(t, strings.Contains(err.Error(), oktetoErrors.InvalidDockerfile))
```
Comment (jLopezbarb) [inline cmd/deploy/deploy_test.go:308]: Can we use `assert.ErrorIs`?

File: cmd/deploy/deploy.go (hunk 2 above)
Comment (jLopezbarb) [reply cmd/deploy/deploy.go:335]: If we return it as no error how is the main pipeline knowing that the remote deployment is failing?

**Review by jLopezbarb — COMMENTED** [review]
Could we run e2e test on this branch? I think we might break some scenarios

File: cmd/deploy/deploy.go (hunk 2 above)
Comment (AdrianPedriza) [reply cmd/deploy/deploy.go:335]: being main pipeline, why I would like to know that is failing? shouldn't the remote handle its own errors?

File: cmd/deploy/deploy_test.go (hunk 4 above)
Comment (AdrianPedriza) [reply cmd/deploy/deploy_test.go:308]: I think that `oktetoErrors.InvalidDockerfile` is not properly wrapped so that method doesn't work :/

File: cmd/deploy/deploy.go (hunk 2 above)
Comment (AdrianPedriza) [reply cmd/deploy/deploy.go:335]: need to check it, draft status in the meantime

**Review by jLopezbarb — APPROVED** [review]
