### PR TITLE
autocreate fail if app with the same name exists

### LINKED ISSUE #2075: `autocreate: true` should fail if the deployment exists but it wasn't created by `okteto up`
**Describe the bug**
This should fail. If not, it can lead to inconsistent states, for example:

```
- autocreate: true
- okteto up
- okteto stack deploy
- okteto up
```

```
 x  Couldn't activate your development container
    Deployment.apps "vote-okteto" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"stack.okteto.com/name":"compose-getting-started", "stack.okteto.com/service":"vote"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #2075

## Proposed changes
- Check if okteto is deployed bu okteto up and fail if not
-

### CODE REVIEW

File: cmd/up/activate.go [hunk 1]
```diff
@@ -63,6 +63,10 @@ func (up *upContext) activate() error {
 		return err
 	}
 
+	if v, ok := app.ObjectMeta().Annotations[model.OktetoAutoCreateAnnotation]; !ok || v != model.OktetoUpCmd {
+		return fmt.Errorf("resource '%s' already exists. Please consider changing the name of autocreate", up.Dev.Name)
```
Comment (rberrelleza) [inline cmd/up/activate.go:67]: what do we mean by `changing the name of autocreate`?

Comment (rberrelleza) [inline cmd/up/activate.go:67]: I thin it would be better to leave the error as resource %s doesn't exist, and then add an `info` like: "use a different name in your okteto.yaml, or remove the autocreate property"

**Review by ifbyol — APPROVED** [review]
