### PR TITLE
Return user friendly error preview name conflict

### LINKED ISSUE #1676: Display a user-friendly error when a preview env already exists
**Describe the bug**
I tried to deploy a preview environment using the name of an existing preview env, but a different scope. I got `conflict` as the error. It would be useful to have a more descriptive error.

**To Reproduce**

1. okteto preview deploy preview-rberelleza
2.okteto preview deploy preview-rberelleza --scope=global

**Expected behavior**
An error explaining that a preview environment already exists with that name

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- Version [e.g. 22]1.13.2

**Additional context**
image

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #1676

## Proposed changes

- Display a better error when there is a name conflict on preview
-

### CODE REVIEW

File: pkg/okteto/preview.go [hunk 1]
```diff
@@ -99,13 +99,20 @@ func DeployPreview(ctx context.Context, name, scope, repository, branch, sourceU
...
+			return "", translatePreviewAPIErr(err, name)
 		}
 	}
 
 	return body.PreviewEnviroment.ID, nil
 }
 
+func translatePreviewAPIErr(err error, name string) error {
+	if err.Error() == "conflict" {
+		return fmt.Errorf("preview '%s' already exists with a different scope. Please try other name", name)
```
Comment (rberrelleza) [inline pkg/okteto/preview.go:111]:
```suggestion
		return fmt.Errorf("preview '%s' already exists with a different scope. Please use a different name", name)
```

**Review by rberrelleza — APPROVED** [review]

**Review by pchico83 — APPROVED** [review]
