### PR TITLE
Fix failure in clusters that forbid running as root

### LINKED ISSUE #1673: Failure in clusters that forbid running as root.
**Describe the bug**
The deployment fails in clusters that forbid containers running as root.  
The init container has no securityContext defined, no way to define it and the okteto/bin image run as root by default.

**To Reproduce**

* Configure your cluster to forbid running as root (via PodSecurityPolicy, OPA Gatekeeper, Kyverno etc.)
* Run:
``` 
 # okteto up -f 'okteto.yaml' --remote '22100' --loglevel=warn
⠇ Pulling image "okteto/bin:latest"... W0727 17:11:08.402899   94027 transport.go:260] Unable to cancel request for *exec.roundTripper
W0727 17:11:08.427946   94027 transport.go:260] Unable to cancel request for *exec.roundTripper
 x  couldn't activate your development container
    Error: container has runAsNonRoot and image will run as root
``` 

**Expected behavior**
No error

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.2 LTS
- Version 1.13.1

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

*okteto.yaml*
```
name: test
namespace: test
image: okteto/golang:1.16
autocreate: true
workdir: /okteto
command: ["bash"]
securityContext:
  runAsUser: 1000
  runAsGroup: 2000
  fsGroup: 3000
sync:
  - .:/usr/src/app
forward:
  - 2345:2345
  - 8080:8080
resources:
  requests:
    cpu: "250m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
initContainer:
  image: okteto/bin:latest
  resources:
    requests:
      cpu: 30m
      memory: 30Mi
    limits:
      cpu: 30m
      memory: 30Mi
```

### PR DESCRIPTION
**Pull request by jLopezbarb**
Fixes #1673

## Proposed changes

- Add security context defined on the manifest
-

### CODE REVIEW

File: pkg/k8s/apps/translate.go [hunk 1]
```diff
@@ -139,7 +139,7 @@ func translate(t *model.Translation, c *kubernetes.Clientset, isOktetoNamespace
 		TranslateOktetoDevSecret(&t.K8sObject.GetPodTemplate().Spec, t.Name, rule.Secrets)
 		if rule.IsMainDevContainer() {
 			TranslateOktetoBinVolumeMounts(devContainer)
-			TranslateOktetoInitBinContainer(rule.InitContainer, &t.K8sObject.GetPodTemplate().Spec)
+			TranslateOktetoInitBinContainer(rule, &t.K8sObject.GetPodTemplate().Spec)
 			TranslateOktetoInitFromImageContainer(&t.K8sObject.GetPodTemplate().Spec, rule)
```
Comment (pchico83) [inline pkg/k8s/apps/translate.go:143]: Should we do it for `TranslateOktetoInitFromImageContainer` too?

Comment (jLopezbarb) [reply pkg/k8s/apps/translate.go:143]: It's already implemented here: 
https://github.com/okteto/okteto/blob/948c2ec9026214875dbd7e803f64c84821e005bc/pkg/k8s/apps/translate.go#L634

**Review by pchico83 — APPROVED** [review]
