### PR TITLE
Deploy build parallel

### LINKED ISSUE #2174: Check images in the build section in parallel
**Describe the bug**
`okteto deploy` checks if the images defined in the `build` section are already built. This check is done sequentially for each image, introducing a delay at the beginning of the command execution:
https://github.com/okteto/okteto/blob/64075c69c63336f876a4fa42d96eb4ef08efb841/cmd/deploy/deploy.go#L223

We should optimize this code and do all these checks in parallel.

In order to to that, we can use wait groups, channels and goroutines.

### PR DESCRIPTION
**Pull request by teresaromero**
Fixes #2174 

## Proposed changes

- When checking if an image has to be build when `okteto deploy`, this checks are done with a go-routine.
- if images has to be build, then they will be build sequentially  after.

### CODE REVIEW

File: cmd/deploy/deploy.go [hunk 1]
```diff
@@ -212,48 +213,42 @@ func (dc *DeployCommand) RunDeploy(ctx context.Context, deployOptions *Options)
...
-				} else if err != nil {
-					return fmt.Errorf("error checking image at registry %s: %v", opts.Tag, err)
-				} else {
-					oktetoLog.Success("Skipping build for image for service %s found: %s", service, opts.Tag)
-					if err := setManifestEnvVars(service, imageWithDigest); err != nil {
-						return err
-					}
+			for {
+				svc, ok := <-toBuild
+				if svc == "" || !ok {
```
Comment (ifbyol) [inline cmd/deploy/deploy.go:243]: Shouldn't we do the break only if there are no more elements (`!ok`)? Could it happen that some serviceToBuild is sent as empty `svc == ""` but there are still some more elements in the channel? In that case, maybe we should do a continue if `svc == "" && ok`

File: cmd/deploy/deploy.go [hunk 2]
```diff
@@ -212,48 +213,42 @@ func (dc *DeployCommand) RunDeploy(ctx context.Context, deployOptions *Options)
...
-					continue
-				} else if err != nil {
-					return fmt.Errorf("error checking image at registry %s: %v", opts.Tag, err)
-				} else {
-					oktetoLog.Success("Skipping build for image for service %s found: %s", service, opts.Tag)
-					if err := setManifestEnvVars(service, imageWithDigest); err != nil {
-						return err
-					}
+			for {
+				svc, ok := <-toBuild
```
Comment (ifbyol) [inline cmd/deploy/deploy.go:242]: I think you can iterate directly over the channel as you don't need a `select` statement and you are closing the channel. I think you could do:

```
for svc := range toBuild {
}
```

File: cmd/deploy/deploy.go [hunk 3]
```diff
@@ -212,48 +213,42 @@ func (dc *DeployCommand) RunDeploy(ctx context.Context, deployOptions *Options)
...
 
 		oktetoLog.Information("Checking to build services at manifest")
-		if deployOptions.Manifest.Build != nil {
-
-			for service, mOptions := range deployOptions.Manifest.Build {
-				buildOptions := build.BuildOptions{OutputMode: oktetoLog.GetOutputFormat()}
-				if mOptions.Name == "" {
-					mOptions.Name = deployOptions.Name
+		if deployOptions.Build {
+			// force build of all services
```
Comment (jLopezbarb) [inline cmd/deploy/deploy.go:217]: Could we encapsulate this into a function?

File: cmd/deploy/deploy.go (hunk 1 above)
Comment (teresaromero) [reply cmd/deploy/deploy.go:243]: it should break if `!ok` so the `srv == ""` condition is no longer applicable, as this will be only when the channel is closed and is not returning anything. the toBuild channel only returns when the image has to be build so i cant think of anycase where it returns an empty string within the channel being open. thnks!

File: cmd/deploy/deploy.go (hunk 2 above)
Comment (teresaromero) [reply cmd/deploy/deploy.go:242]: i saw the first comment first... haha i think this is a better approach, so i will change the code for this option

File: cmd/deploy/deploy.go (hunk 3 above)
Comment (teresaromero) [reply cmd/deploy/deploy.go]: yes we can!
