### PR TITLE
Jlopezbarb/syncthing removing console instead of okteto process e2e

### LINKED ISSUE #3177: Running "okteto up" twice without proper termination causes logout in Ubuntu
**Describe the bug**
Running okteto up twice causes my session to be logged out. I have found a specific scenario to reproduce it but it has happened to me without the given scenario also.

**To Reproduce**

Run "okteto up" in a project
Terminate terminal 
Run "okteto up" in a same project again
When "Activating your development container" is displayed I'm logged out of my session

**Expected behavior**
 Should start project again

**Desktop (please complete the following information):**

- OS: Ubuntu 
- Version: 22.04

**Additional context**
From auth.log I can see:
```
Oct 19 16:29:58 mihkel-ThinkPad-X1-Extreme-Gen-4i polkitd(authority=local): Unregistered Authentication Agent for unix-session:12 (system bus name :1.703, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Oct 19 16:29:59 mihkel-ThinkPad-X1-Extreme-Gen-4i gdm-password]: pam_unix(gdm-password:session): session closed for user mihkel
Oct 19 16:29:59 mihkel-ThinkPad-X1-Extreme-Gen-4i systemd-logind[1130]: Session 12 logged out. Waiting for processes to exit.
Oct 19 16:29:59 mihkel-ThinkPad-X1-Extreme-Gen-4i systemd-logind[1130]: Removed session 12.
```

Running okteto cli 2.8.1

### PR DESCRIPTION
**Pull request by jLopezbarb**
Fixes #3177

## Proposed changes

- It seems that ubuntu has another process PID to detect if the process is not an okteto process
- Getting the parent should finish whenever we reach the okteto command.
- We need to maintain previous code to make it work on Windows

### CODE REVIEW

**Comment by AgustinRamiroDiaz** [comment]
Why are we using names instead of ids? is it to not store the reference?

File: pkg/syncthing/syncthing.go [hunk 1]
```diff
@@ -878,6 +878,10 @@ func getParent(p *process.Process) (*process.Process, error) {
 		oktetoLog.Infof("parent name is the same: %s", name)
 		return getParent(parent)
 	}
+	if !strings.Contains(pName, "okteto") {
+		oktetoLog.Infof("okteto parent not found: %s", name)
+		return getParent(parent)
```
Comment (AgustinRamiroDiaz) [inline pkg/syncthing/syncthing.go:883]: Maybe the name should change to `getOktetoAncestor`

Comment (jLopezbarb) [reply pkg/syncthing/syncthing.go:883]: I'm changing the whole PR to make it safer deleting process

File: pkg/syncthing/syncthing.go [hunk 2]
```diff
@@ -878,6 +878,10 @@ func getParent(p *process.Process) (*process.Process, error) {
 		oktetoLog.Infof("parent name is the same: %s", name)
 		return getParent(parent)
 	}
+	if !strings.Contains(pName, "okteto") {
```
[the remark this answers is not in the document]
Comment (jLopezbarb) [reply pkg/syncthing/syncthing.go:881]: We are getting parents until we get something different than `syncthing` which was supposed to be the `okteto` process. It seems that there are some OS that instead of syncthing being depending on okteto it depended on the okteto parent (which was the terminal) and was terminating the terminal process instead of okteto

File: pkg/syncthing/syncthing.go [hunk 3]
```diff
@@ -833,54 +832,17 @@ func (s *Syncthing) HardTerminate() error {
...
 			oktetoLog.Infof("error terminating syncthing %d with wait: %s", p.Pid, err.Error())
 		}
-		if parent != nil && parent.Pid != int32(pid) {
-			oktetoLog.Infof("pid: %s / name: %s / cmd: %s", p.Pid, p.Name, p.Cmdline)
-			if err := terminate(parent, true); err != nil {
-				oktetoLog.Infof("error terminating syncthing %d with wait: %s", p.Pid, err.Error())
-				continue
-			}
-		}
+
```
Comment (jLopezbarb) [inline pkg/syncthing/syncthing.go:839]: This code is moved to wait until the okteto notices that there is another process running

File: cmd/up/forwards.go [hunk 4]
```diff
@@ -91,24 +90,8 @@ func (up *upContext) sshForwards(ctx context.Context) error {
...
-		if err := up.Forwarder.Add(f); err != nil {
-			return err
-		}
-	}
-
-	for _, r := range up.Dev.Reverse {
-		if err := up.Forwarder.AddReverse(r); err != nil {
-			return err
-		}
+	if err := addToForwarder(up); err != nil {
```
Comment (jLopezbarb) [inline cmd/up/forwards.go:93]: We need to wait until the other process free the ports

File: cmd/up/forwards.go [hunk 5]
```diff
@@ -129,6 +112,67 @@ func (up *upContext) sshForwards(ctx context.Context) error {
 	return nil
 }
 
+func addToForwarder(up *upContext) error {
+	ticker := time.NewTicker(1 * time.Second)
+	to := time.NewTicker(up.Dev.Timeout.Resources)
+	var forwardErr error
+	alreadyAdded := map[int]bool{}
```
Comment (jLopezbarb) [inline cmd/up/forwards.go:119]: needed to store if it's already added to not add them twice (that's another error)

File: cmd/up/forwards.go [hunk 6]
```diff
@@ -129,6 +112,67 @@ func (up *upContext) sshForwards(ctx context.Context) error {
 	return nil
 }
 
+func addToForwarder(up *upContext) error {
+	ticker := time.NewTicker(1 * time.Second)
+	to := time.NewTicker(up.Dev.Timeout.Resources)
+	var forwardErr error
```
Comment (jLopezbarb) [inline cmd/up/forwards.go:118]: need to store the error if the timeout finish we need to return a proper error to the user

File: go.mod [hunk 7]
```diff
@@ -218,6 +218,8 @@ require (
 	sigs.k8s.io/yaml v1.2.0 // indirect
 )
 
+require github.com/spf13/afero v1.9.2
```
Comment (jLopezbarb) [inline go.mod:221]: Added to mock filesystem calls

**Comment by jLopezbarb** [comment]
@pchico83 The only problem that I've found while testing this is that killing the okteto process is faster (previous method, not working for `ubuntu`) than letting okteto know that it has been replaced by another one. I've done some tests and the time to destroy the old dev container is around 30s vs almost instantaneous (since we were removing the process). We need to wait until the other process is finished in order to create the forwarder, it will fail with port is already taken error if we don't wait.

On the other side, even if it takes more time to start the new okteto, the error displayed on the older okteto process is more verbose:

### _**Old behavior**_
Captura de Pantalla 2022-11-03 a las 13 19 23

### _**New behavior**_

Captura de Pantalla 2022-11-03 a las 15 25 51

**Comment by pchico83** [comment]
> @pchico83 The only problem that I've found while testing this is that killing the okteto process is faster (previous method, not working for `ubuntu`) than letting okteto know that it has been replaced by another one. I've done some tests and the time to destroy the old dev container is around 30s vs almost instantaneous (since we were removing the process). We need to wait until the other process is finished in order to create the forwarder, it will fail with port is already taken error if we don't wait.
> 
> On the other side, even if it takes more time to start the new okteto, the error displayed on the older okteto process is more verbose:
> 
> ### _**Old behavior**_
> Captura de Pantalla 2022-11-03 a las 13 19 23
> 
> ### _**New behavior**_
> Captura de Pantalla 2022-11-03 a las 15 25 51

Let's find a faster notification channel, we could run a goroutine watching for changes in `okteto.pid`

File: cmd/up/forwards.go [hunk 8]
```diff
@@ -129,6 +112,67 @@ func (up *upContext) sshForwards(ctx context.Context) error {
 	return nil
 }
 
+func addToForwarder(up *upContext) error {
+	ticker := time.NewTicker(1 * time.Second)
+	to := time.NewTicker(up.Dev.Timeout.Resources)
```
Comment (pchico83) [inline cmd/up/forwards.go:117]: Let's use a 10s timeout. Otherwise, if the port is taken by other app, we would fail very late

File: cmd/up/up.go [hunk 9]
```diff
@@ -570,6 +573,14 @@ func (up *upContext) activateLoop() {
 		if up.isRetry || isTransientError {
 			oktetoLog.Infof("waiting for shutdown sequence to finish")
 			<-up.ShutdownCompleted
+			pidFromFile, err := up.pidController.get()
+			if err != nil {
+				oktetoLog.Infof("error getting pid: %w")
+			}
+			if pidFromFile != strconv.Itoa(os.Getpid()) {
+				up.Exit <- fmt.Errorf("development container has been replaced")
```
Comment (pchico83) [inline cmd/up/up.go:581]: Can we add a hint to run `okteto exec`? Also, I would say something like:
```
development container has been deactivated by another "okteto up" command
```

**Review by pchico83 — APPROVED** [review]

**Comment by jLopezbarb** [comment]
Adding a comment to show the new changes
## New changes:
- Added fsnotify as dependency to watch for file change. (Thanks @pchico83, this code is much faster than the one we had before. Great win-win feature, we will fix a very annoying bug and make UX better at the same time)
- Make the code testable
- This is how it will look like the error
Captura de Pantalla 2022-11-04 a las 14 51 44

File: cmd/up/pid.go [hunk 10]
```diff
@@ -19,32 +19,210 @@ import (
...
+				pid := pc.pidProvider.provide()
+				filePID, err := pc.get()
+				if err != nil {
+					oktetoLog.Infof("unable to get PID file at %s", pc.pidFilePath)
+					continue
+				}
+				if strconv.Itoa(pid) != filePID {
+					notifyCh <- oktetoErrors.UserError{
+						E:    fmt.Errorf("development container has been deactivated by another 'okteto up' command"),
+						Hint: "If you want to run a second terminal you can use 'okteto exec' command",
```
Comment (pchico83) [inline cmd/up/pid.go:183]:
```suggestion
						Hint: "Use ' okteto exec' to open another terminal to your development container",
```

**Review by pchico83 — APPROVED** [review]

**Review by teresaromero — APPROVED** [review]

**Review by ifbyol — APPROVED** [review]

**Comment by pchico83** [comment]
@jLopezbarb are we backporting this one? or are we waiting for the next cli release?

**Comment by jLopezbarb** [comment]
Do we want to create a new patch with this change? I'm ok back porting it and creating a new release

**Comment by pchico83** [comment]
> Do we want to create a new patch with this change? I'm ok back porting it and creating a new release

@jLopezbarb whatever you think it's better. I would say this isn't a trivial change and it should be in `master` for a while, but you are the best one to evaluate that

**Comment by jLopezbarb** [comment]
I prefer to have it in master for a while (we'll cut the next release at the end of next week), so I think it will be better to have it in master for a week and test it with all the e2e tests whenever we merge into master and with manual tests whenever we start testing the release candidate
