### PR TITLE
Force redeploys using annotations instead of image digests

### LINKED ISSUE #1138: "okteto up" reconnects with the wrong image.
**Describe the bug**
If "okteto up" reconnects because there is a deployment update, `okteto up` reuses the old image of the deployment to reconnect.

**To Reproduce**
1. Deploy a stack
2. `okteto up`
3. Change code
4. `okteto stack deploy --build`

**Expected behavior**
`okteto up` should use the new image build by `okteto stack deploy --build` if `image` is not defined in the okteto manifest.

### PR DESCRIPTION
**Pull request by pchico83**
Signed-off-by: Pablo Chico de Guzman <pchico83@gmail.com>

Fixes #1138

### CODE REVIEW

File: pkg/k8s/labels/labels.go [hunk 1]
```diff
@@ -32,6 +35,9 @@ const (
 	// DeploymentAnnotation indicates the original deployment manifest  when the development container was activated
 	DeploymentAnnotation = "dev.okteto.com/deployment"
 
+	// TimestampAnnotation indicates the timestamp of an operation
+	TimestampAnnotation = "dev.okteto.com/timestamp"
```
Comment (rberrelleza) [inline pkg/k8s/labels/labels.go:39]: can we rename this to something more descriptive dev.okteto.com/last-updated or something like that?

**Comment by rberrelleza** [comment]
will this cause `okteto up` to always trigger a new deployment?

**Comment by pchico83** [comment]
> will this cause `okteto up` to always trigger a new deployment? or it only if using --build?

only with `--build`

**Review by rberrelleza — APPROVED** [review]
