### PR TITLE
fix: deploy with build flag

### LINKED ISSUE #3097: Service not found running `okteto deploy --build`
**Describe the bug**
While performing Test Scenario 1 to the the `release-2.7-beta3` an issue was found when trying to deploy and build 

**To Reproduce**

Test Scenario 1 at the Okteto CLI checks

**Expected behavior**
The images should be built if the flag `--build` is at the deploy command

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

# Proposed changes

Fixes #3097

### CODE REVIEW

File: cmd/deploy/deploy.go [hunk 1]
```diff
@@ -611,14 +623,7 @@ func buildImages(ctx context.Context, build func(context.Context, *types.BuildOp
...
-		var stackServices map[string]bool
-
-		if stack := deployOptions.Manifest.GetStack(); stack != nil {
-			stackServices = stack.GetServicesWithBuildSection()
-		}
 
-		allServicesWithBuildSection := deployOptions.Manifest.GetBuildServices()
-		oktetoManifestBuildServices := setDifference(allServicesWithBuildSection, stackServices)
 		// servicesToBuildSet = (allServicesWithBuildSection - stackServices) + deployOptions.servicesToDeploy
 		servicesToBuildSet := setUnion(oktetoManifestBuildServices, sliceToSet(deployOptions.servicesToDeploy))
```
Comment (AgustinRamiroDiaz) [inline cmd/deploy/deploy.go:628]: Based on the new logic that I'm seeing, I think that we should apply the same here: only account for services which have a build section

File: cmd/deploy/deploy.go [hunk 2]
```diff
@@ -595,11 +595,23 @@ func (dc *DeployCommand) cleanUp(ctx context.Context) {
...
+
+	if stack := deployOptions.Manifest.GetStack(); stack != nil {
+		stackServices = stack.GetServicesWithBuildSection()
+	}
+
+	allServicesWithBuildSection := deployOptions.Manifest.GetBuildServices()
+	oktetoManifestBuildServices := setDifference(allServicesWithBuildSection, stackServices)
+
 	if deployOptions.Build {
+		finalStackIntersection := setIntersection(stackServices, sliceToSet(deployOptions.servicesToDeploy))
```
Comment (AgustinRamiroDiaz) [inline cmd/deploy/deploy.go:608]: I think this does the correct behavior, but it's complex to understand.

I'm thinking something like this might be simpler to understand:
```
...
allServicesWithBuildSection := deployOptions.Manifest.GetBuildServices()
oktetoManifestBuildServices := setDifference(allServicesWithBuildSection, stackServices)
servicesToDeployWithBuildSection := setIntersection(allServicesWithBuildSection, sliceToSet(deployOptions.servicesToDeploy))
servicesToBuildSet := setUnion(oktetoManifestBuildServices, servicesToDeployWithBuildSection)
```

Comment (teresaromero) [reply cmd/deploy/deploy.go:608]: i am not sure i am understanding this

File: cmd/deploy/deploy.go (hunk 1 above)
Comment (teresaromero) [reply cmd/deploy/deploy.go:628]: I see the only thing change here is common logic for both build and not build flag has been taken out the if/else. What do you mean with `apply the same here?`

Comment (AgustinRamiroDiaz) [reply cmd/deploy/deploy.go:628]: I think that in both cases (build forced and unforced) we should be collecting the same images. The only difference would be in the unforced build that we then filter that slice of images if they have been already built

So I think we should do here the same we are doing in the other block 

```
finalStackIntersection := setIntersection(stackServices, sliceToSet(deployOptions.servicesToDeploy))
servicesToBuildSet := setUnion(oktetoManifestBuildServices, finalStackIntersection)
```

File: cmd/deploy/deploy.go (hunk 2 above)
Comment (AgustinRamiroDiaz) [reply cmd/deploy/deploy.go:608]: If I understand this logic correctly, with Javi's change we'll build:
- `deployOptions.servicesToDeploy` that are defined in the stack and have a build section
- services with build section defined in the `okteto.yml` manifest

Since the `manifest`'s build section contains the `stack`'s build services, if there's a service from `deployOptions.servicesToDeploy` that's not in the stack, it will be in the manifest and will get built anyways. 
I think the logic is more clear if we compare everything to `allServicesWithBuildSection`. So in summary we'll build:
- `deployOptions.servicesToDeploy` that have a build section
- services with build section defined in the `okteto.yml` manifest

**Review by AgustinRamiroDiaz — APPROVED** [review]
I've created [this pr](https://github.com/okteto/okteto/pull/3100) to explain better the changes I proposed.
The only change in logic I'd do is to get the images to build the same way for both scenarios (build forced and unforced). I think it does not affect the behavior because in the unforced path we are filtering with `getServicesToBuild`, which should take away all the `servicesToDeploy` without build section
