### PR TITLE
Stream pod events to the spinner if they last for more than 1s

### LINKED ISSUE #430: Clearly log when `okteto up` fails due to scheduling constraints
`okteto up` fails with the following:

```
okteto up
Deployment [deployment] doesn't exist in namespace [namespace]. Do you want to create a new one? [y/n]: y
⠼ Provisioning your persistent volume...
x  kubernetes is taking too long to create the cloud native environment. Please check for errors and try again
```

Looking at the logs, the issue is related to scheduling issues with the syncthing pod  due to CPU constraints. The log should  be clear about it and propose actions.

### PR DESCRIPTION
**Pull request by pchico83**
Closes #430 #332

### CODE REVIEW

File: cmd/up.go [hunk 1]
```diff
@@ -356,7 +356,30 @@ func (up *UpContext) devMode(isRetry bool, d *appsv1.Deployment, create bool) (b
 		}
 	}
 
-	p, err := pods.GetDevPod(up.Context, up.Dev, up.Client, create)
+	reporter := make(chan string)
+	go func() {
+		long := false
+		message := ""
+		ticker := time.NewTicker(1000 * time.Millisecond)
```
Comment (rberrelleza) [inline cmd/up.go]:
```suggestion
		ticker := time.NewTicker(1 * time.Second)
```

File: cmd/up.go [hunk 2]
```diff
@@ -356,7 +356,30 @@ func (up *UpContext) devMode(isRetry bool, d *appsv1.Deployment, create bool) (b
...
+		for {
+			select {
+			case <-ticker.C:
+				if long && message != "" {
```
Comment (rberrelleza) [inline cmd/up.go]: I don't understand this part of the loop. Why do we log the message that we received in the other case here?

File: cmd/up.go [hunk 3]
```diff
@@ -356,7 +356,30 @@ func (up *UpContext) devMode(isRetry bool, d *appsv1.Deployment, create bool) (b
...
+					spinner.update(fmt.Sprintf("%s...", message))
+				}
+				long = true
+			case message = <-reporter:
+				if message == "" {
+					return
+				}
+				spinner.update("Activating your development environment...")
```
Comment (rberrelleza) [inline cmd/up.go]: Why do we wait until getting a message to show the  `Activating...` message?

File: pkg/k8s/pods/pod.go [hunk 4]
```diff
@@ -76,19 +78,58 @@ func loopGetDevPod(dev *model.Dev, c *kubernetes.Clientset, waitUntilDeployed bo
...
+	watchPodEvents, err := c.CoreV1().Events(dev.Namespace).Watch(opts)
+	if err != nil {
+		return nil, err
+	}
+	for {
+		select {
+		case event := <-watchPod.ResultChan():
+			pod, ok := event.Object.(*v1.Pod)
+			if !ok {
+				return nil, nil
```
Comment (rberrelleza) [inline pkg/k8s/pods/pod.go]: If we can't parse the object what happens when we return from the call? Should we send an error, or at least log what happened?

File: pkg/k8s/pods/pod.go [hunk 5]
```diff
@@ -76,19 +78,58 @@ func loopGetDevPod(dev *model.Dev, c *kubernetes.Clientset, waitUntilDeployed bo
 		return nil, err
 	}
 
-	log.Infof("pod %s with revison %s is progressing", pod.Name, d.Annotations[deploymentRevisionAnnotation])
-	if pod.Status.Phase == apiv1.PodRunning {
-		log.Infof("pod %s with revison %s is running", pod.Name, d.Annotations[deploymentRevisionAnnotation])
-		return pod, nil
+	opts := metav1.ListOptions{
```
Comment (rberrelleza) [inline pkg/k8s/pods/pod.go]: If `pod.Name` is unique, do we also need the okteto label?

File: pkg/k8s/pods/pod.go [hunk 6]
```diff
@@ -76,19 +78,58 @@ func loopGetDevPod(dev *model.Dev, c *kubernetes.Clientset, waitUntilDeployed bo
...
+		select {
+		case event := <-watchPod.ResultChan():
+			pod, ok := event.Object.(*v1.Pod)
+			if !ok {
+				return nil, nil
 			}
+			if pod.Status.Phase == apiv1.PodRunning {
+				return pod, nil
+			}
+			if pod.DeletionTimestamp != nil {
```
Comment (rberrelleza) [inline pkg/k8s/pods/pod.go]: This would mean that the pod is in process of being deleted. What happens in this case? The caller of GetDevPod will most likely get a nullref no? (since there's no error returned)

File: cmd/up.go [hunk 7]
```diff
@@ -356,7 +356,30 @@ func (up *UpContext) devMode(isRetry bool, d *appsv1.Deployment, create bool) (b
...
+		message := ""
+		ticker := time.NewTicker(1000 * time.Millisecond)
+		for {
+			select {
+			case <-ticker.C:
+				if long && message != "" {
+					spinner.update(fmt.Sprintf("%s...", message))
+				}
+				long = true
+			case message = <-reporter:
```
Comment (rberrelleza) [inline cmd/up.go]: Since we are waiting for a second, a lot of messages could come through, and we are not going to log them all.  Would it make sense to discard all the messages in the channel except for the last one when assigning to `message`?

File: cmd/up.go [hunk 8]
```diff
@@ -356,7 +356,30 @@ func (up *UpContext) devMode(isRetry bool, d *appsv1.Deployment, create bool) (b
...
+				if message == "" {
+					return
+				}
+				spinner.update("Activating your development environment...")
+				long = false
+			case <-up.Context.Done():
```
Comment (rberrelleza) [inline cmd/up.go]: Will this loop also exit when we close the `reporter` channel?

File: cmd/up.go [hunk 9]
```diff
@@ -356,7 +356,30 @@ func (up *UpContext) devMode(isRetry bool, d *appsv1.Deployment, create bool) (b
...
 
-	p, err := pods.GetDevPod(up.Context, up.Dev, up.Client, create)
+	reporter := make(chan string)
+	go func() {
+		long := false
+		message := ""
+		ticker := time.NewTicker(1000 * time.Millisecond)
+		for {
+			select {
+			case <-ticker.C:
```
Comment (rberrelleza) [inline cmd/up.go]: Do we need both the ticker and the message case? Maybe simplify it by having a single case that receives the message and then waits a second before checking again?

File: cmd/up.go (hunk 8 above)
Comment (rberrelleza) [reply cmd/up.go]: I think this loop should depend on the lifecycle of `reporter`, and don't care about `up.Context.Done`. Instead, we close the reporter when done, and that can cause this loop to be closed.

File: cmd/up.go [hunk 10]
```diff
@@ -356,7 +356,30 @@ func (up *UpContext) devMode(isRetry bool, d *appsv1.Deployment, create bool) (b
 		}
 	}
 
-	p, err := pods.GetDevPod(up.Context, up.Dev, up.Client, create)
+	reporter := make(chan string)
```
Comment (rberrelleza) [inline cmd/up.go]:
```suggestion
	reporter := make(chan string)
	defer close(reporter)
```

File: cmd/exec.go [hunk 11]
```diff
@@ -72,7 +72,7 @@ func executeExec(ctx context.Context, dev *model.Dev, args []string) error {
 		dev.Namespace = namespace
 	}
 
-	p, err := pods.GetDevPod(ctx, dev, client, false)
+	p, err := pods.GetDevPod(ctx, dev, client, false, nil)
```
Comment (rberrelleza) [inline cmd/exec.go]: I think calling this `GetDevPod` is confusing, since it calls and monitors. Maybe we can have two functions, one to get the pod and another to start the watcher?

File: pkg/k8s/pods/pod.go [hunk 12]
```diff
@@ -27,19 +28,20 @@ const (
...
 
 // GetDevPod returns the dev pod for a deployment
-func GetDevPod(ctx context.Context, dev *model.Dev, c *kubernetes.Clientset, waitUntilDeployed bool) (*apiv1.Pod, error) {
+func GetDevPod(ctx context.Context, dev *model.Dev, c *kubernetes.Clientset, waitUntilDeployed bool, reporter chan string) (*apiv1.Pod, error) {
+	defer close(reporter)
 	tries := 0
 	ticker := time.NewTicker(200 * time.Millisecond)
 	for tries < maxRetriesPodRunning {
-		pod, err := loopGetDevPod(dev, c, waitUntilDeployed)
+		pod, err := loopGetDevPod(ctx, dev, c, waitUntilDeployed, reporter)
```
Comment (rberrelleza) [inline pkg/k8s/pods/pod.go]: what about the `nil, nil` return case?

File: pkg/k8s/pods/pod.go [hunk 13]
```diff
@@ -27,19 +28,20 @@ const (
...
 	devTerminationGracePeriodSeconds int64
 )
 
 // GetDevPod returns the dev pod for a deployment
-func GetDevPod(ctx context.Context, dev *model.Dev, c *kubernetes.Clientset, waitUntilDeployed bool) (*apiv1.Pod, error) {
+func GetDevPod(ctx context.Context, dev *model.Dev, c *kubernetes.Clientset, waitUntilDeployed bool, reporter chan string) (*apiv1.Pod, error) {
+	defer close(reporter)
 	tries := 0
 	ticker := time.NewTicker(200 * time.Millisecond)
 	for tries < maxRetriesPodRunning {
```
Comment (rberrelleza) [inline pkg/k8s/pods/pod.go]: if we have a watcher pattern in `loopGetDevPod`, I don't think we should have the retries. This would complicate consuming the `reporter`.  Could we simplify everything on a single model?  Get the pod, watch until ready, return?

File: pkg/k8s/pods/pod.go [hunk 14]
```diff
@@ -76,19 +78,58 @@ func loopGetDevPod(dev *model.Dev, c *kubernetes.Clientset, waitUntilDeployed bo
...
+			if pod.DeletionTimestamp != nil {
+				return nil, nil
+			}
+		case event := <-watchPodEvents.ResultChan():
+			if reporter == nil {
+				continue
+			}
+			e, ok := event.Object.(*v1.Event)
+			if !ok {
+				return nil, nil
```
Comment (rberrelleza) [inline pkg/k8s/pods/pod.go]: I think we should log and continue.

File: pkg/k8s/pods/pod.go [hunk 15]
```diff
@@ -76,19 +78,58 @@ func loopGetDevPod(dev *model.Dev, c *kubernetes.Clientset, waitUntilDeployed bo
...
-	log.Infof("pod %s with revison %s is progressing", pod.Name, d.Annotations[deploymentRevisionAnnotation])
-	if pod.Status.Phase == apiv1.PodRunning {
-		log.Infof("pod %s with revison %s is running", pod.Name, d.Annotations[deploymentRevisionAnnotation])
-		return pod, nil
+	opts := metav1.ListOptions{
+		LabelSelector: fmt.Sprintf("%s=%s", OktetoInteractiveDevLabel, dev.Name),
+		FieldSelector: fmt.Sprintf("metadata.name=%s", pod.Name),
+	}
+
+	watchPod, err := c.CoreV1().Pods(dev.Namespace).Watch(opts)
```
Comment (rberrelleza) [inline pkg/k8s/pods/pod.go]: Do we get events even if they were created before the watcher? (e.g. what if the pod is already running by the time we run this code)
