### PR TITLE
fix: avoid use compose files if manifest is v1

### LINKED ISSUE #2575: `okteto up` fails when a `docker-compose.yaml` file is present
**Describe the bug**
Running `okteto up` with a `docker-compose.yaml` file in the same directory fails with `Error checking image at registry`

**To Reproduce**

1. Define a simple docker-compose.yaml
```yaml
x-common-args: &common-args
  HASH: "${HASH:-local}"

version: '3.8'
services:
  installer:
    image: "installer:${HASH:-local}"
    build:
      context: .
      dockerfile: build/installer.Dockerfile
  base:
    image: "base:${HASH:-local}"
    depends_on: [installer]
    build:
      context: build
      dockerfile: base.Dockerfile
  server:
    image: "server:${HASH:-local}"
    depends_on: [installer, base]
    build:
      context: components
      dockerfile: ../build/server.Dockerfile
      args:
        <<: *common-args
```
3. Define an `okteto.yaml` in the same directory
```yaml
name: server
imagePullPolicy: IfNotPresent
container: server
command: [bash]
sync:
  - .:/root
```
3. Try `okteto up`
> Error checking image at registry base:local: error getting image tag digest: GET https://index.docker.io/v2/library/base/manifests/local: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/base Type:repository]]

**Expected behavior**
The `docker-compose.yaml` would be ignored, the `okteto up` command works just fine if the `docker-compose.yaml` file is deleted

**Desktop (please complete the following information):**

- OS: macOS
- Version: 2.1.0

**Additional context**
The `docker-compose.yaml` is simply being used as a "build definition" file, so that all the docker images can be easily built using a single command: `docker-compose build`. There are no other "compose" features being used in this file. Additionally, the `base` image is used as a stage in building the `server` image.

### PR DESCRIPTION
**Pull request by AdrianPedriza**
Signed-off-by: adripedriza <adripedriza@gmail.com>

Fixes #2575

## Proposed changes

- create new method to manage manifest v1 that will not merge data from docker-compose files if present

### CODE REVIEW

File: pkg/model/manifest.go [hunk 1]
```diff
@@ -263,6 +263,51 @@ func NewDeployInfo() *DeployInfo {
...
+			}
+		}
+		manifest.Filename = path
+		return manifest, nil
+	} else if manifestPath != "" && pathExistsAndDir(manifestPath) {
+		cwd = manifestPath
+	}
+
+	var devManifest *Manifest
+	if oktetoPath := getFilePath(cwd, oktetoFiles); oktetoPath != "" {
```
Comment (jLopezbarb) [inline pkg/model/manifest.go:294]: We already have this logic in `GetManifestV2`. Can we called it `getManifestFromOktetoFile`

File: pkg/model/manifest.go [hunk 2]
```diff
@@ -263,6 +263,51 @@ func NewDeployInfo() *DeployInfo {
 	}
 }
 
+//GetManifestV1 gets a manifest from a path or search for the files to generate it
+func GetManifestV1(manifestPath string) (*Manifest, error) {
+	cwd, err := os.Getwd()
```
Comment (jLopezbarb) [inline pkg/model/manifest.go:268]: Same logic as GetManifestV2. Can you encapsulate this into a function called `loadManifestFromPathFile` or something similar?

**Review by pchico83 — APPROVED** [review]

**Review by teresaromero — APPROVED** [review]

File: pkg/model/manifest.go [hunk 3]
```diff
@@ -286,24 +299,68 @@ func GetManifestV2(manifestPath string) (*Manifest, error) {
 		}
 		manifest.Filename = path
 		return manifest, nil
-	} else if manifestPath != "" && pathExistsAndDir(manifestPath) {
+	}
+
+	return nil, nil
```
Comment (jLopezbarb) [inline pkg/model/manifest.go:304]: It's a good practice to return errors in Go according to  [Effective Go](https://golang.org/doc/effective_go.html#errors), I think that you should have `return nil, CustomErr` and then check if the error is the one that you are returning. [Go blog]( https://go.dev/blog/error-handling-and-go) also has a good understanding on how to handle errors

**Review by jLopezbarb — APPROVED** [review]
