### PR TITLE
fix: update not existing image error message

### LINKED ISSUE #2366: Confusing error when doing UP on a dev manifest with non-existent images
**Describe the bug**
For `dev` section of the manifest, if I use a non-existent image, let's say `okteto.dev/whatever` I get this confusing error during UP, telling me about arguments to use, etc...

Screenshot 2022-03-16 at 12 30 09

Output:

Screenshot 2022-03-16 at 12 36 24

**Expected behavior**
The error should be clearer describing that `The image 'okteto.dev/whatever' doesn't exist` or similar.

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #2366

## Proposed changes
- Update message if the image can not be built with the information given in build section
Captura de pantalla 2022-03-16 a las 18 16 48

### CODE REVIEW

File: cmd/up/activate.go [hunk 1]
```diff
@@ -85,6 +86,12 @@ func (up *upContext) activate() error {
 
 	if _, err := registry.GetImageTagWithDigest(up.Dev.Image.Name); err == oktetoErrors.ErrNotFound {
 		oktetoLog.Infof("image '%s' not found, building it: %s", up.Dev.Image.Name, err.Error())
+		if _, err := os.Stat(up.Dev.Image.Dockerfile); err != nil {
+			return oktetoErrors.UserError{
+				E:    fmt.Errorf("The image '%s' doesn't exist and can't be build", up.Dev.Image.Name),
```
Comment (pchico83) [inline cmd/up/activate.go:91]: @rlamana could you review the message?

**Review by pchico83 — APPROVED** [review]
