### PR TITLE
Empty cfgmap repository if not valid repo schema

### LINKED ISSUE #3228: I cannot run `okteto deploy` in a repo clone from AzureDevops Git
**Describe the bug**
I cloned my AzureDevops repo and `okteto deploy` fails with:
```
 Could not detect repo protocol
```

**Expected behavior**
We shouldn't fail parsing the git URL. The default behavior on this case should be to get the name of the current folder and don't store either the git url or the branch in the deploy configmap.

### PR DESCRIPTION
**Pull request by teresaromero**
# Proposed changes

Fixes #3228 

When parsing the `.git/config` url when cloned repo, if not recognised as `http`, https or ssh, we returned an error.
This fix allows not recognised schemas to work with okteto cli with local repositories.

Tested the scenario with repo go-gettting-started, changing the url param of the git config then run `okteto deploy`
UI output was showing a message not allowing redeploy and name for dev environment was last part of local repository url

### CODE REVIEW

File: cmd/deploy/command_configuration.go [hunk 1]
```diff
@@ -134,7 +129,14 @@ func addEnvVars(ctx context.Context, cwd string) error {
 			if err != nil {
 				return err
 			}
-			repo = repoHTTPS.String()
+			if repoHTTPS != nil {
+				repo = repoHTTPS.String()
+			} else {
+				// ir repo was parsed but hasnt got a valid schema
+				// fallback to empty repository
+				oktetoLog.Warning("retrieved local repository")
```
Comment (jLopezbarb) [inline cmd/deploy/command_configuration.go:137]: I wouldn't show a warning to the user, What do you think about logging it into the logs files with an info level?

File: cmd/deploy/command_configuration.go [hunk 2]
```diff
@@ -134,7 +129,14 @@ func addEnvVars(ctx context.Context, cwd string) error {
 			if err != nil {
 				return err
 			}
-			repo = repoHTTPS.String()
+			if repoHTTPS != nil {
+				repo = repoHTTPS.String()
+			} else {
+				// ir repo was parsed but hasnt got a valid schema
```
Comment (jLopezbarb) [inline cmd/deploy/command_configuration.go:135]:
```suggestion
				// if repo was parsed but hasnt got a valid schema
```

File: cmd/deploy/command_configuration.go [hunk 3]
```diff
@@ -178,9 +180,8 @@ func switchRepoSchemaToHTTPS(repo string) (*url.URL, error) {
 		return repoURL, nil
 	case httpsScheme:
 		return repoURL, nil
-	default:
```
Comment (jLopezbarb) [inline cmd/deploy/command_configuration.go:181]: I would keep the default and log it instead of returning the error in case we need it to debug upcoming bugs

File: cmd/deploy/command_configuration.go [hunk 4]
```diff
@@ -178,9 +180,8 @@ func switchRepoSchemaToHTTPS(repo string) (*url.URL, error) {
...
-		return nil, errUnsupportedScheme
 	}
+	return nil, nil
```
Comment (ifbyol) [inline cmd/deploy/command_configuration.go:184]: I think the goal is to don't return any error. We can return just nil in line 174 and make that the function `switchRepoSchemaToHTTPS` returns just a pointer to a URL. If there is an error parsing the URL, we just return nil.

In that way, we can simplify a bit the code because we can change the function `addEnvVars` to not return an error. This case was the only one generating that scenario

Comment (ifbyol) [reply cmd/deploy/command_configuration.go:184]: It would be something like this:

```
diff --git a/cmd/deploy/command_configuration.go b/cmd/deploy/command_configuration.go
index 6489ce2b..470e11dc 100644
--- a/cmd/deploy/command_configuration.go
+++ b/cmd/deploy/command_configuration.go
@@ -114,7 +114,7 @@ func mergeServicesToDeployFromOptionsAndManifest(deployOptions *Options) {
        }
 }

-func addEnvVars(ctx context.Context, cwd string) error {
+func addEnvVars(ctx context.Context, cwd string) {
        if os.Getenv(model.OktetoGitBranchEnvVar) == "" {
                branch, err := utils.GetBranch(cwd)
                if err != nil {
@@ -130,11 +130,12 @@ func addEnvVars(ctx context.Context, cwd string) error {
                }

                if repo != "" {
-                       repoHTTPS, err := switchRepoSchemaToHTTPS(repo)
-                       if err != nil {
-                               return err
+                       repoHTTPS := switchRepoSchemaToHTTPS(repo)
+                       if repoHTTPS == nil {
+                               repo = ""
+                       } else {
+                               repo = repoHTTPS.String()
                        }
-                       repo = repoHTTPS.String()
                }
                os.Setenv(model.GithubRepositoryEnvVar, repo)
        }
@@ -163,23 +164,22 @@ func addEnvVars(ctx context.Context, cwd string) error {
                os.Setenv(model.OktetoTokenEnvVar, okteto.Context().Token)
        }
        oktetoLog.AddMaskedWord(os.Getenv(model.OktetoTokenEnvVar))
-       return nil
 }

-func switchRepoSchemaToHTTPS(repo string) (*url.URL, error) {
+func switchRepoSchemaToHTTPS(repo string) *url.URL {
        repoURL, err := giturls.Parse(repo)
        if err != nil {
-               return nil, err
+               return nil
        }
        switch repoURL.Scheme {
        case sshScheme, httpScheme:
                repoURL.Scheme = httpsScheme
                repoURL.User = nil
-               return repoURL, nil
+               return repoURL
        case httpsScheme:
-               return repoURL, nil
+               return repoURL
        default:
-               return nil, errUnsupportedScheme
+               return nil
        }
 }

diff --git a/cmd/deploy/deploy.go b/cmd/deploy/deploy.go
index 7c457566..36c4c313 100644
--- a/cmd/deploy/deploy.go
+++ b/cmd/deploy/deploy.go
@@ -266,9 +266,7 @@ func (dc *DeployCommand) RunDeploy(ctx context.Context, deployOptions *Options)
                return err
        }

-       if err := addEnvVars(ctx, cwd); err != nil {
-               return err
-       }
+       addEnvVars(ctx, cwd)
        oktetoLog.Debugf("creating temporal kubeconfig file '%s'", dc.TempKubeconfigFile)
        if err := dc.Kubeconfig.Modify(dc.Proxy.GetPort(), dc.Proxy.GetToken(), dc.TempKubeconfigFile); err != nil {
                oktetoLog.Infof("could not create temporal kubeconfig %s", err)
```

File: cmd/deploy/command_configuration.go [hunk 5]
```diff
@@ -163,23 +160,24 @@ func addEnvVars(ctx context.Context, cwd string) error {
...
 	oktetoLog.AddMaskedWord(os.Getenv(model.OktetoTokenEnvVar))
-	return nil
 }
 
-func switchRepoSchemaToHTTPS(repo string) (*url.URL, error) {
+func switchRepoSchemaToHTTPS(repo string) *url.URL {
 	repoURL, err := giturls.Parse(repo)
 	if err != nil {
-		return nil, err
+		return nil
```
Comment (ifbyol) [inline cmd/deploy/command_configuration.go:168]: Might be interesting to include a info or debug with the error to have in our logs but not display it to the user

**Review by jLopezbarb — APPROVED** [review]

File: cmd/deploy/command_configuration.go [hunk 6]
```diff
@@ -163,23 +160,24 @@ func addEnvVars(ctx context.Context, cwd string) error {
...
 		repoURL.User = nil
-		return repoURL, nil
+		return repoURL
 	case httpsScheme:
-		return repoURL, nil
+		return repoURL
 	default:
-		return nil, errUnsupportedScheme
+		// if repo was parsed but has not a valid schema
+		oktetoLog.Info("retrieved local repository")
```
Comment (ifbyol) [inline cmd/deploy/command_configuration.go:179]: I would include the schema to know which one was detected

**Review by ifbyol — APPROVED** [review]
Minor comments about logging but it looks good!
