### PR TITLE
Fixes #1633. Look for stack manifest into .okteto folder

### LINKED ISSUE #1633: "okteto stack deploy" should look in ".okteto" folder for stack manifests
**Describe the bug**
When deploying a pipeline, it is able to find a stack in the `.okteto` folder, but the CLI does not implement this behavior

### PR DESCRIPTION
**Pull request by ifbyol**
Signed-off-by: Nacho Fuertes <nacho@okteto.com>

Fixes #1633

## Proposed changes

- Look for stack manifest into `.okteto` folder in the current working directory

### CODE REVIEW

**Review by pchico83 — APPROVED** [review]

**Review by jLopezbarb — APPROVED** [review]

File: pkg/model/utils.go [hunk 1]
```diff
@@ -70,6 +70,8 @@ func GetValidNameFromFolder(folder string) (string, error) {
 	name := filepath.Base(dir)
 	name = strings.ToLower(name)
 	name = ValidKubeNameRegex.ReplaceAllString(name, "-")
+	name = strings.TrimPrefix(name, "-")
+	name = strings.TrimSuffix(name, "-")
```
Comment (ifbyol) [inline pkg/model/utils.go:74]: @pchico83 @jLopezbarb I had to add this because in the case the folder holding the stack manifest starts or ends with a `.` (or any other invalid char for a k8s name) we were generating an invalid name like `-okteto`
