### PR TITLE
fail fast if inside a cluster

### LINKED ISSUE #287: Okteto up inside of a cloud environment enters an error loop
**Describe the bug**
I accidentally run okteto up in my dev environment. 

**Expected behavior**
Okteto up should just fail in this case

### PR DESCRIPTION
**Pull request by rberrelleza**
Fixes #287

## Proposed changes
Prevent up, namespace, login  from working on a remote dev environment

### CODE REVIEW

File: cmd/down.go [hunk 1]
```diff
@@ -42,6 +43,10 @@ func Down() *cobra.Command {
 		RunE: func(cmd *cobra.Command, args []string) error {
 			log.Info("starting down command")
 
+			if k8Client.InCluster() {
```
Comment (pchico83) [inline cmd/down.go]: `down` works if your dev environment is in Okteto Cloud... same for `exec`...
Maybe we shouldn't inject the `okteto` and `kubectl` binary if you are not in Okteto Cloud.

Comment (rberrelleza) [reply cmd/down.go]: yes, I think that's probably a better approach.

File: pkg/k8s/client/client.go [hunk 2]
```diff
@@ -51,3 +51,13 @@ func GetLocal() (*kubernetes.Clientset, *rest.Config, string, error) {
 	}
 	return client, config, namespace, nil
 }
+
+// InCluster returns true if Okteto is running on a Kubernetes cluster
+func InCluster() bool {
+	_, err := rest.InClusterConfig()
+	if err == nil {
```
Comment (golangcibot) [inline pkg/k8s/client/client.go]: S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (from `gosimple`)
