### PR TITLE
Fix preview list output

### LINKED ISSUE #3904: [Labels] Fix `okteto preview list` when using `--log-output json` + `--output json`
### Proposed changes
- command must show output in json if `--output json` enabled
- command must show logs in json if `--log-output json` enabled
- command must show output and logs if both enabled
### test scenarios
- unit test covering added code

### PR DESCRIPTION
**Pull request by teresaromero**
# Proposed changes

Fixes #3904 

When the flag `--output` was implemented in order to get the preview list in different formats (`yaml` or `json`) the function used to show this output was our custom logger `oktetoLog.Println()`.

The logger format is set as a global flag `--log-output`, which default is TTY, but it can change to json, plain, silent, etc...

The command `okteto preview list` by default shows a table with a list of preview environments, when we where setting the `--log-output` to `json` and the `--output` to `json`, the logger has a fixed setting to mrashall the log into specific fields (stage log) so it was not marshalling the previews list, and the output was empty.

To fix this:
- Change `oktetoLog.Println()` to` fmt.Println()` for both `json` and `yaml` outputs, the output flag was linked to the log output format, this dependency has been removed. https://github.com/okteto/okteto/pull/3970/commits/0e1f3cffcfd6a9819f96ad282a0285672d43def2
- Refactor the command `okteto preview list` in order to add unit-tests to all components of the command and extract the oktetoClient which retrieves the previews list at the top of the command.

## How to validate

1. Use okteto context to log into your okteto instance
2. Run `okteto preview deploy` with or without labels (its recommended with so all the fields of the list are filled). This will create a preview environment
3. Run `okteto preview list` check that a table is the output

```
❯ okteto preview list
 i  Using teresaromero @ cloud.okteto.com as context
Name                       Scope     Sleeping  Labels
goofy-leakey-teresaromero  personal  false     testing
```

4. Run `okteto preview --log-output json` shows the default view, as there are only info and debug logs we should change the log level to see the logs in json format running `okteto preview list --log-output json --log-level debug`. This does not conflict with `--output` as the print function to show the table is not tied to `oktetoLog`

```
{"level":"debug","stage":"","message":"server name override: \"\"","timestamp":1693921450}
{"level":"info","stage":"","message":"started okteto preview list --log-output json --log-level debug","timestamp":1693921450}
{"level":"info","stage":"","message":"Using teresaromero @ cloud.okteto.com as context","timestamp":1693921451}
Name                       Scope     Sleeping  Labels
goofy-leakey-teresaromero  personal  false     testing
{"level":"info","stage":"","message":"finished okteto preview list --log-output json --log-level debug","timestamp":1693921451}
```

5. Running `okteto preview list --log-output json --log-level debug --output json` we see that the logs are shown but the preview list is not shown in any format

```
❯ okteto preview list --log-output json --log-level debug --output json
{"level":"debug","stage":"","message":"server name override: \"\"","timestamp":1693921590}
{"level":"info","stage":"","message":"started okteto preview list --log-output json --log-level debug --output json","timestamp":1693921590}
{"level":"info","stage":"","message":"finished okteto preview list --log-output json --log-level debug --output json","timestamp":1693921591}
```

When fixed:

```
❯ ok preview list --log-output json --log-level debug --output json
{"level":"debug","stage":"","message":"server name override: \"\"","timestamp":1694065981}
{"level":"info","stage":"","message":"started /Users/teresaromero/github.com/okteto/okteto/bin/okteto preview list --log-output json --log-level debug --output json","timestamp":1694065981}
[
 {
  "name": "goofy-leakey-teresaromero",
  "scope": "personal",
  "sleeping": true,
  "labels": [
   "testing"
  ]
 }
]
{"level":"info","stage":"","message":"finished /Users/teresaromero/github.com/okteto/okteto/bin/okteto preview list --log-output json --log-level debug --output json","timestamp":1694065982}
```

6. Run `okteto preview list --log-output json --log-level debug --output yaml` and check is fixed

## CLI Quality Reminders 🔧

For both authors and reviewers:

- Scrutinize for potential regressions
- Ensure key automated tests are in place
- Build the CLI and test using the validation steps
- Assess Developer Experience impact (log messages, performances, etc)
- If too broad, consider breaking into smaller PRs
- Adhere to our [code style](https://github.com/okteto/okteto/blob/master/docs/code-style.md) and [code review](https://github.com/okteto/okteto/blob/master/docs/code-review.md) guidelines

### CODE REVIEW

File: cmd/preview/list.go [hunk 1]
```diff
@@ -78,32 +91,29 @@ func List(ctx context.Context) *cobra.Command {
...
-	oktetoClient, err := okteto.NewOktetoClient()
-	if err != nil {
-		return err
-	}
-	previewListOutput, err := getPreviewOutput(ctx, opts, oktetoClient)
-	if err != nil {
-		return err
+// executeListPreviews prints the list of previews
+func executeListPreviews(previews []previewOutput, outputFormat string) error {
+	if len(previews) == 0 {
```
Comment (andreafalzetti) [inline cmd/preview/list.go:96]: I think we need to log this only for plaintext format because if I use `-o json` or `yaml` this will cause a parsing error. For JSON/YAML returning empty array should be okay

Comment (teresaromero) [reply cmd/preview/list.go]: I've changed the approach, so now only the default view (table) is showing the message instead of the headers with empty table.

Yaml marshal returns `[]` for empty object, but for json i added a condition to show `[]` as the returned value of the marshal for empty object is null

**Review by AdrianPedriza — APPROVED** [review]
LGTM, just minor comments 👍

File: cmd/preview/list.go [hunk 2]
```diff
@@ -78,32 +91,34 @@ func List(ctx context.Context) *cobra.Command {
...
-	if err != nil {
-		return err
-	}
-	previewListOutput, err := getPreviewOutput(ctx, opts, oktetoClient)
-	if err != nil {
-		return err
-	}
-	switch opts.output {
+// executeListPreviews prints the list of previews
+func executeListPreviews(previews []previewOutput, outputFormat string) error {
```
[the remark this answers is not in the document]
Comment (teresaromero) [reply cmd/preview/list.go]: make sense

**Review by andreafalzetti — APPROVED** [review]
