### PR TITLE
Skip build if volume mount is already mounted

### LINKED ISSUE #2096: `okteto stack deploy` building image on every deploy
**Describe the bug**
If I have a docker-compose like this one:

```
services:
  vote:
    build: vote
    ports:
      - 8080:8080
    volumes:
      - vote:/src

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data
```

The `vote` image is built on every `okteto stack deploy` because there is a mount volume, but it should only be built the first time.

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #2096

## Proposed changes
- Skip build if the volume mount is already mounted and built 
-

### CODE REVIEW

**Review by jmacelroy — APPROVED** [review]

File: pkg/cmd/stack/translate.go [hunk 1]
```diff
@@ -208,6 +204,17 @@ func addVolumeMountsToBuiltImage(ctx context.Context, s *model.Stack, options *S
 			if okteto.IsOkteto() && !registry.IsOktetoRegistry(svc.Image) {
 				svc.Image = fmt.Sprintf("okteto.dev/%s-%s:okteto-with-volume-mounts", s.Name, name)
 			}
+			if !options.ForceBuild {
+				if _, err := registry.GetImageTagWithDigest(svc.Image); err != errors.ErrNotFound {
```
Comment (ifbyol) [inline pkg/cmd/stack/translate.go:208]: I see that if there is an error getting the image tag, but that error is not a NotFound, we are also skipping the build. Should we fail in that case or just build the image to avoid to break the execution for an experience improvement?

**Review by pchico83 — APPROVED** [review]
