### PR TITLE
Interpolate "OKTETO_USERNAME" in preview cmd

### LINKED ISSUE #1689: Interpolate "OKTETO_USERNAME" in the name of the preview environment
**Describe the bug**
I'd like to be able to create a preview env like this: `okteto preview deploy review-mybranch-$OKTETO_USERNAME` and have okteto automatically fill in $OKTETO_USERNAME

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #1689

## Proposed changes

- Adds the option to use OKTETO_USERNAME variable in command
-

### CODE REVIEW

**Review by ifbyol — APPROVED** [review]

File: cmd/preview/deploy.go [hunk 1]
```diff
@@ -263,3 +263,13 @@ func waitForResourcesToBeRunning(ctx context.Context, name, namespace string, t
 	}
 	return nil
 }
+
+func getExpandedName(name string) string {
+	username := okteto.GetUsername()
+	os.Setenv("OKTETO_USERNAME", username)
```
Comment (rberrelleza) [inline cmd/preview/deploy.go:269]: this will set OKTETO_USERNAME in the env for the entire execution. Is that what we want? (if so, then I'd suggest we do that earlier, on a separate function, so we can use it in other places as well). 

IF not,  maybe we can use a library that only does the expansion for a string, without requiring it in the global env? (I think we use envsubst somewhere else?)

Comment (pchico83) [reply cmd/preview/deploy.go:269]: I would go with option a)

File: cmd/preview/deploy.go [hunk 2]
```diff
@@ -57,6 +57,10 @@ func Deploy(ctx context.Context) *cobra.Command {
 				return okErrors.ErrNotLogged
 			}
 
+			if err := utils.SetOktetoUsernameEnv(); err != nil {
```
Comment (pchico83) [inline cmd/preview/deploy.go:60]: I would do it as part of the global init function:
https://github.com/okteto/okteto/blob/master/main.go#L45

File: cmd/utils/okteto.go [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+import (
+	"os"
+
+	"github.com/okteto/okteto/pkg/okteto"
+)
+
+func SetOktetoUsernameEnv() error {
+	username := okteto.GetUsername()
+	if err := os.Setenv("OKTETO_USERNAME", username); err != nil {
```
Comment (pchico83) [inline cmd/utils/okteto.go:24]: Let's check if `OKTETO_USERNAME` has a value. If so, I wouldn't overwrite it

**Review by pchico83 — APPROVED** [review]

**Review by pchico83 — APPROVED** [review]
