### PR TITLE
fix: if image is set, we should return the image

### LINKED ISSUE #2995: Okteto rebuilds image always without specifying `--build`
**Describe the bug**
Okteto rebuilds the image always without specifying the `--build` flag if the image tag specified by the user is not using the default okteto tag. 

**To Reproduce**

1. Create this okteto stack:
```yaml
services:
  test:
    image: okteto.dev/test:dev
    build:
      context: .
```
2. Create this okteto manifest:
```yaml
deploy:
  compose: okteto-stack.yml

dev:
  test:
    command: ["bash"]
    sync:
      - .:/app
```
3. Run `okteto up` and see that is building image
4. Run `okteto up` again and see that rebuilds the image

**Expected behavior**
Second execution should be skipped due to image being built previously

**Desktop (please complete the following information):**
- OS: macOS
- Version 2.6

**Additional context**
Introduced in https://github.com/okteto/okteto/pull/2939

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #2995 

## Proposed changes
- Return the proper image to fix the scenario
- Add new test to cover the scenario proposed

### CODE REVIEW

**Review by teresaromero — APPROVED** [review]

File: cmd/build/v2/services.go [hunk 1]
```diff
@@ -107,6 +107,8 @@ func getToBuildTag(manifestName, svcName string, b *model.BuildInfo) string {
 		return b.Image
 	case (shouldBuildFromDockerfile(b) && shouldAddVolumeMounts(b)) || shouldAddVolumeMounts(b):
 		return fmt.Sprintf("%s/%s-%s:%s", targetRegistry, manifestName, svcName, model.OktetoImageTagWithVolumes)
+	case shouldBuildFromDockerfile(b) && b.Image != "":
```
Comment (ifbyol) [inline cmd/build/v2/services.go:110]: Sounds weird having to check if it has to be built from a dockerfile but then, return the Image from b. Would it make sense to switch the case clauses?
