### PR TITLE
fix: panic on pipeline fallback to preview

### LINKED ISSUE #3167: Error: panic when pipeline deploy `--wait`fallback to previews
**Describe the bug**
If I run `okteto pipeline --wait --namespace test-{YOUR_USERNAMe}` pointing to an Okteto preview environment. The CLI panics 

**To Reproduce**

1. Run `okteto preview deploy --branch cli-e2e --repository https://github.com/okteto/movies --wait`
1. Get the preview name - it should be something like `distracted-wiles-jlopezbarb`
1. Run `okteto pipeline deploy --branch cli-e2e --repository https://github.com/okteto/movies --wait --namespace distracted-wiles-jlopezbarb `
1. See panic error

**Expected behavior**
CLI should fallback correctly to previews and retrieve the correct information

**Desktop (please complete the following information):**

- Version master

**Additional context**
We should also fix https://github.com/okteto/okteto/blob/master/integration/okteto/preview_test.go#L28 making it fail first [here](https://github.com/okteto/okteto/blob/master/integration/okteto/preview_test.go#L58) and fixing it later.

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

# Proposed changes

Fixes #3167

- Fix e2e tests to fallback correctly to previews. We were deploying on personal namespace
- Add a fix to the test

### CODE REVIEW

**Review by mnevadom — APPROVED** [review]

**Review by pchico83 — APPROVED** [review]

File: pkg/okteto/pipeline.go [hunk 1]
```diff
@@ -34,12 +34,16 @@ import (
 type pipelineClient struct {
 	client    *graphql.Client
 	sseClient *http.Client
+
+	url string
 }
 
-func newPipelineClient(client *graphql.Client, sseClient *http.Client) *pipelineClient {
+func newPipelineClient(url string, client *graphql.Client, sseClient *http.Client) *pipelineClient {
```
Comment (teresaromero) [inline pkg/okteto/pipeline.go:41]: nit: could we add the url as last param with the clients first?

**Review by teresaromero — APPROVED** [review]
