### PR TITLE
fix deploy when field notes not given to external

### LINKED ISSUE #3342: Panic reading external resources
**Describe the bug**
Okteto CLI panics when I don't specify a notes field with the following trace:

``` bash
goroutine 41 [running]:
github.com/okteto/okteto/pkg/externalresource.(*ERFilesystemManager).LoadMarkdownContent(0xc0006cd760, {0xc001502280?, 0x8f7?})
	github.com/okteto/okteto/pkg/externalresource/external_resource.go:58 +0x67
github.com/okteto/okteto/pkg/model.getOktetoManifest({0xc001502280, 0x32})
	github.com/okteto/okteto/pkg/model/manifest.go:599 +0x398
github.com/okteto/okteto/pkg/model.getManifestFromFile({0xc000060004, 0x27}, {0xc001502280, 0x32})
	github.com/okteto/okteto/pkg/model/manifest.go:361 +0x54
github.com/okteto/okteto/pkg/model.getManifestFromOktetoFile({0xc000060004, 0x27})
	github.com/okteto/okteto/pkg/model/manifest.go:232 +0x1b0
github.com/okteto/okteto/pkg/model.GetManifestV2({0x0, 0x0})
	github.com/okteto/okteto/pkg/model/manifest.go:303 +0xe5
github.com/okteto/okteto/cmd/deploy.(*DeployCommand).RunDeploy(0xc0003db180, {0x102d802a8, 0xc00005c0c0}, 0xc000ae32b0)
	github.com/okteto/okteto/cmd/deploy/deploy.go:308 +0x29f
github.com/okteto/okteto/cmd/deploy.Deploy.func1.1()
	github.com/okteto/okteto/cmd/deploy/deploy.go:212 +0x7b
created by github.com/okteto/okteto/cmd/deploy.Deploy.func1
	github.com/okteto/okteto/cmd/deploy/deploy.go:211 +0xd3d
```

**To Reproduce**

1. Create the following manifest:
```yaml
deploy:
  - echo hello
external:
  db:
    endpoints:
    - name: db
       url: https://localhost:3306
```
1. Run okteto deploy
1. See error

**Expected behavior**
It must not fail

**Desktop (please complete the following information):**

- Version: master build

### PR DESCRIPTION
**Pull request by AdrianPedriza**
Signed-off-by: adripedriza <adripedriza@gmail.com>

# Proposed changes
- check that `notes` is not nil (has not been included in the manifest) before try to read its value
- add test covering scenario

Fixes #3342

### CODE REVIEW

File: pkg/externalresource/external_resource_test.go [hunk 1]
```diff
@@ -95,12 +110,15 @@ func TestExternalResource_LoadMarkdownContent(t *testing.T) {
 				assert.Error(t, tt.externalResourceFSM.LoadMarkdownContent(manifestPath))
 			} else {
 				assert.NoError(t, tt.externalResourceFSM.LoadMarkdownContent(manifestPath))
-				sDec, err := b64.StdEncoding.DecodeString(tt.externalResourceFSM.ExternalResource.Notes.Markdown)
-				if err != nil {
-					t.Fatal(err)
+				if tt.externalResourceFSM.ExternalResource.Notes != nil {
```
Comment (AdrianPedriza) [inline pkg/externalresource/external_resource_test.go:113]: I am not sure if it is appropriate to do this check or to directly compare the expected object vs the one we get

Comment (jLopezbarb) [reply pkg/externalresource/external_resource_test.go:113]: If the function reads and set the value, I'd assert that the complete object is in the state that we want

**Review by ifbyol — APPROVED** [review]

**Review by jLopezbarb — APPROVED** [review]
