### PR TITLE
Show error if deploying services with persistentVolume as `disabled`

### LINKED ISSUE #3437: Return and error if using `services` and disabling the okteto persistent volume
**Describe the bug**
[services](https://www.okteto.com/docs/reference/manifest/#services-object-optional) requires the persistent volume to be enabled. We should return a clear error if using `services` and `persistentVolume.enabled: false`.

**To Reproduce**

1. Modify https://github.com/okteto/math to disable the persistent volume in the dev container
1. Run `okteto up`

**Expected behavior**
A clear error is returned stating that `persistentVolume.enabled` must be true to use `services`

### PR DESCRIPTION
**Pull request by nitishfy**
# Proposed changes

Fixes #3437

**Final Output**
_-  If using services with `persistentVolume` as **disabled**:_
Screenshot from 2023-06-10 13-38-49

_- If using services with `persistenVolume` as **enabled**:_
image

**Additional Information:** 
In the [blog](https://www.okteto.com/blog/develop-django-celery-app-in-kubernetes/) we're mentioning about to take a look at the `okteto.yml` file. However, the `okteto.yml` file doesn't match with the `okteto.yml` present [here](https://github.com/okteto/math). **Port Forwarding field is missing.** _We can raise a PR to add that change as well._ If the field will be missing, the user will have to use the endpoints from Okteto UI than directly from CLI.  Here's how it looks like _with/without_ Port forwarding mentioned:

**Port Forwarding included:**
image 
image

**Port Forwarding not included:**
image
image

### CODE REVIEW

File: cmd/up/activate.go [hunk 1]
```diff
@@ -310,6 +310,8 @@ func (up *upContext) waitUntilDevelopmentContainerIsRunning(ctx context.Context,
 		if err := config.UpdateStateFile(up.Dev.Name, up.Dev.Namespace, config.Attaching); err != nil {
 			oktetoLog.Infof("error updating state: %s", err.Error())
 		}
+	} else {
+		return fmt.Errorf("'persistentVolume.enabled' must be set to true to work with services")
```
Comment (pchico83) [inline cmd/up/activate.go:314]:
```suggestion
		return fmt.Errorf("'persistentVolume.enabled' must be true to use the 'services' field")
```

Comment (nitishfy) [reply cmd/up/activate.go]: Fixed!

**Comment by nitishfy** [comment]
@pchico83 Should we push the changes provided in the **Additional information**?

File: cmd/up/activate.go [hunk 2]
```diff
@@ -310,6 +310,8 @@ func (up *upContext) waitUntilDevelopmentContainerIsRunning(ctx context.Context,
 		if err := config.UpdateStateFile(up.Dev.Name, up.Dev.Namespace, config.Attaching); err != nil {
 			oktetoLog.Infof("error updating state: %s", err.Error())
 		}
+	} else {
+		return fmt.Errorf("'persistentVolume.enabled' must true to use the 'services' field")
```
Comment (pchico83) [inline cmd/up/activate.go:314]:
```suggestion
		return fmt.Errorf("'persistentVolume.enabled' must be true to use the 'services' field")
```

Comment (nitishfy) [reply cmd/up/activate.go]: Aah! Thanks, this is fixed!

**Comment by pchico83** [comment]
> @pchico83 Should we push the changes provided in the **Additional information** in the above Pull Request description?

@nitishfy we don't usually update blog posts, only okteto.com/docs

**Comment by nitishfy** [comment]
> > @pchico83 Should we push the changes provided in the **Additional information** in the above Pull Request description?
> 
> @nitishfy we don't usually update blog posts, only okteto.com/docs

We don't have to update the blog post. Instead, we can add minor details such as _Port forwarding_ in okteto.yml in the desired code rather than updating blog. WDYT?

**Comment by pchico83** [comment]
> > > @pchico83 Should we push the changes provided in the **Additional information** in the above Pull Request description?
> > 
> > 
> > @nitishfy we don't usually update blog posts, only okteto.com/docs
> 
> We don't have to update the blog post. Instead, we can add minor details such as _Port forwarding_ in okteto.yml in the [desired code](https://github.com/okteto/math) rather than updating blog. WDYT?

@nitishfy  yes, that makes sense, thanks!

**Review by pchico83 — APPROVED** [review]

**Comment by nitishfy** [comment]
> @nitishfy yes, that makes sense, thanks!

[PR](https://github.com/okteto/math/pull/5) raised!
