### PR TITLE
fix: translate stacks to compose ports when unmarshalling

### LINKED ISSUE #2747: Flexible Port Mapping Causes Incorrect Endpoint Creation.
**Describe the bug**
We are generating incorrect endpoints. We are generating an endpoint for the port 8080 and another one for the port 80 (including the port number in the endpoint) instead of just one endpoint. It was introduce with the fix for the property public in stacks.
This is a combination of a [change](https://github.com/okteto/okteto/issues/1584) we did in the past + the translations service -ingress is done in the CLI since 2.3.0 (this provoked the public property stopped working) and before it was done in the backend.

```
 movies:
    build: reverse-proxy
    ports:
      - 8080:80
```

**Expected behavior**
There should be one endpoint with a different local and remote port.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #2747

## Proposed changes
- Translates stacks ports to compose syntax when unmarshalling

### CODE REVIEW

File: pkg/cmd/stack/translate.go [hunk 1]
```diff
@@ -420,7 +420,7 @@ func translateService(svcName string, s *model.Stack) *apiv1.Service {
 func getSvcPublicPorts(svcName string, s *model.Stack) []model.Port {
 	result := []model.Port{}
 	for _, p := range s.Services[svcName].Ports {
-		if !model.IsSkippablePort(p.ContainerPort) && (p.HostPort != 0 || s.Services[svcName].Public) {
+		if !model.IsSkippablePort(p.ContainerPort) && p.HostPort != 0 {
```
Comment (jLopezbarb) [inline pkg/cmd/stack/translate.go:423]: This change was made in the `2.3.2` release and was causing the bug so we are reverting it

File: pkg/cmd/stack/translate_test.go [hunk 2]
```diff
@@ -1568,6 +1568,7 @@ func TestGetSvcPublicPorts(t *testing.T) {
 						Ports: []model.Port{
 							{
 								ContainerPort: 80,
+								HostPort:      80,
```
Comment (jLopezbarb) [inline pkg/cmd/stack/translate_test.go:1571]: Reached this point we always need to have both ports set, because we have translated to a compose syntax so we need to have HostPort field defined

File: pkg/model/stack.go [hunk 3]
```diff
@@ -90,6 +90,7 @@ type Service struct {
 	Healtcheck      *HealthCheck          `yaml:"healthcheck,omitempty"`
 	User            *StackSecurityContext `yaml:"user,omitempty"`
 
+	// Fields only for okteto stacks
```
Comment (AgustinRamiroDiaz) [inline pkg/model/stack.go:93]: What does this mean? 
If it means that these fields are only used for stacks, should we create 2 structs for this? one for the `Service`, and a wrapper `StackService` which has the `Service` and also this fields?

File: pkg/model/stack_serializer_test.go [hunk 4]
```diff
@@ -1853,3 +1853,84 @@ func Test_UnmarshalStackUser(t *testing.T) {
 		})
 	}
 }
+
+func Test_TranslateOktetoStackPortsToComposePorts(t *testing.T) {
```
Comment (AgustinRamiroDiaz) [inline pkg/model/stack_serializer_test.go:1857]: 🔥

File: pkg/cmd/stack/translate.go (hunk 1 above)
Comment (jmacelroy) [reply pkg/cmd/stack/translate.go:423]: Are we also reverting a fix? Can you link to what the associated issue was. I want to evaluate if we release without that fix or not.

File: pkg/model/stack.go (hunk 3 above)
Comment (jmacelroy) [reply pkg/model/stack.go:93]: I like the idea. It may change the way in which these fields are accessed.

**Review by jmacelroy — APPROVED** [review]
The only major comment is based around how reverting the public service code affects the release but still think we can go forward with this PR. I just need more info to make a release decision if you could link it or explain a bit.

File: pkg/model/stack_serializer.go [hunk 5]
```diff
@@ -597,6 +602,25 @@ func getSvcPorts(public bool, rawPorts, rawExpose []PortRaw) (bool, []Port, erro
 	return public, ports, nil
 }
 
+// translateOktetoStacksPortsIntoComposeSyntax translates okteto stack port syntax into compose ports syntax
+// We need this translation because we are using the same serializer for okteto stacks and docker compose syntax
+// Otherwise we don't know which ports should create an endpoint and which ones not
+// Example 1:
+// Stacks syntax  -> Compose syntax
+// ports:         | ports:
+//   - 5000       |   - 5000:5000
```
[the remark this answers is not in the document]
Comment (jLopezbarb) [reply pkg/model/stack_serializer.go:611]: only if the public is set to true. If public is set to true (by the user) it means that it has to create the endpoints, so we are converting it to a compose syntax.
If public is not set we don't convert any port so we can have a service with several ports and only one endpoint. For example:
```
services:
  api:
    ports:
    - 80:80
    - 5432
```
will create an endpoint for port 80 and will create a service (ClusterIP) with the ports 5432 and 80

File: pkg/model/stack_serializer.go [hunk 6]
```diff
@@ -566,6 +566,11 @@ func translateHealtcheckCurlToHTTP(healthcheck *HealthCheck) {
 func getSvcPorts(public bool, rawPorts, rawExpose []PortRaw) (bool, []Port, error) {
 	rawPorts = expandRangePorts(rawPorts)
 
+	// If public is set at this point it means that it comes from an okteto stacks and it's true
+	if public {
```
[the remark this answers is not in the document]
Comment (jLopezbarb) [reply pkg/model/stack_serializer.go:570]: public is a field on our okteto stacks manifest. It means to create an endpoint for a service. For example:
```
services:
  api:
    ports:
    - 80
    public: true
```
 is the way of creating an endpoint for the api service on okteto stacks.
 Full stacks reference is here: https://www.okteto.com/docs/0.10/reference/stacks/

File: pkg/model/stack_serializer.go [hunk 7]
```diff
@@ -597,6 +602,25 @@ func getSvcPorts(public bool, rawPorts, rawExpose []PortRaw) (bool, []Port, erro
...
+// translateOktetoStacksPortsIntoComposeSyntax translates okteto stack port syntax into compose ports syntax
+// We need this translation because we are using the same serializer for okteto stacks and docker compose syntax
+// Otherwise we don't know which ports should create an endpoint and which ones not
+// Example 1:
+// Stacks syntax  -> Compose syntax
+// ports:         | ports:
+//   - 5000       |   - 5000:5000
+//   - 3000       |   - 3000:3000
+// public: true   |
+func translateOktetoStacksPortsIntoComposeSyntax(ports []PortRaw) []PortRaw {
```
[the remark this answers is not in the document]
Comment (jLopezbarb) [reply pkg/model/stack_serializer.go:614]: I prefer to name it as translate, because we are not filling every port, we are just filling if is an okteto stack and the service is set to true, so we need to translate the ports to a compose syntax

File: pkg/model/stack.go (hunk 3 above)
Comment (jLopezbarb) [reply pkg/model/stack.go:93]: Yes, We should read each manifest (okteto stacks and compose) in a way that it doesn't collide with the other and translate them to a common struct to work afterward. I think that should be covered on  https://github.com/okteto/okteto/issues/2219

File: pkg/cmd/stack/translate.go (hunk 1 above)
Comment (jLopezbarb) [reply pkg/cmd/stack/translate.go:423]: We are reverting https://github.com/okteto/okteto/pull/2735 with this change

**Review by ifbyol — APPROVED** [review]

File: pkg/model/stack_serializer.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (AgustinRamiroDiaz) [reply pkg/model/stack_serializer.go:611]: @jLopezbarb I didn't understand. It's the same behavior whether the compose looks like this
```
services:
  api:
    ports:
    - 80:80
    - 5432
```

or this?
```
services:
  api:
    ports:
    - 80
    - 5432
```
