### PR TITLE
Fix global optimization when okteto deploy --build

### LINKED ISSUE #2529: The Global Registry optimization should be always active unless `--no-cache` is set
**Describe the bug**
The Global Registry optimization isn't working on pipelines.
Pipelines execute `okteto deploy --build`. This should use the Global Registry optimization.

The only way to disable the Global Registry optimization is `okteto build --no-cache`.

**Additional context**
This [repo](https://github.com/okteto/movies-with-compose/blob/main/.github/workflows/build-global.yaml) build global images on each merge to `main`, but if you deploy the repo, the Global Registry optimization isn't used.

### PR DESCRIPTION
**Pull request by teresaromero**
Fixes #2529 

## Proposed changes

- when running okteto deploy --build at a pipeline process, check images at registry

### CODE REVIEW

File: cmd/build/v2/build.go [hunk 1]
```diff
@@ -242,7 +242,18 @@ func (bc *OktetoBuilder) addVolumeMounts(ctx context.Context, manifest *model.Ma
 	if err != nil {
 		return "", err
 	}
-	buildOptions := build.OptsFromBuildInfo(manifest.Name, svcName, svcBuild, &types.BuildOptions{})
+	buildOptions := build.OptsFromBuildInfo(manifest.Name, svcName, svcBuild, options)
+
+	if build.ShouldOptimizeBuild(buildOptions) {
```
Comment (teresaromero) [inline cmd/build/v2/build.go:247]: Not sure we should also apply the optimization at the volume-mounts image when pipeline? this looks for a tag not the hash so i'm afraid the tag will be built but for other base image. maybe i'm having missunderstandings about the volumes here 🤷🏼‍♀️.

cc: @pchico83 , @jLopezbarb

Comment (jLopezbarb) [reply cmd/build/v2/build.go:247]: I don't think that the built image comes from another image, with checking that it is built I think it would be enough, because if the two images are built one after the other if there is an image and the other will also come from the last built image of the first image (I think I have explained myself terribly but I hope it is understood)😅

Comment (teresaromero) [reply cmd/build/v2/build.go:247]: understood :D
