### PR TITLE
fix: show warning msg when sanitize dev

### LINKED ISSUE #2888: `okteto up` doesn't work properly when the service name contains `_` and the deploy replaced that char by `-`
**Describe the bug**
If I have a service in a docker compose which contains a `_` and I deploy it, I get a warning saying that is being sanitized:

```
 !  Service 'functional_test' has been sanitized into 'functional-test'. This may affect discovery service.
```

But then, if my okteto manifest references that service using `_` too, when I execute `okteto up <service_name>` it fails with:

```
 x  Application 'functional_test' not found in namespace 'nacho'
```

The deployment it tries to set as dev is called `functional-test`.

If Okteto automatically translate the service name when deploying the service, it should do the same when setting the dev mode for one service

**To Reproduce**

1. Clone https://github.com/jmacelroy/go-getting-started/ repository and checkout branch `target-example`
2. From the root, execute `okteto deploy -f functional_tests/okteto.yml`
3. You will see a warning like the one exposed above
4. If you execute `okteto up -f functional_tests/okteto.yml`, you will get the error I pasted above

**Expected behavior**
If the service name specified in the manifest for dev envs is not a valid one, we should apply the same sanitization we do when deploying a service

**Desktop (please complete the following information):**

- Version: `2.4.1`

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by AdrianPedriza**
Fixes #2888

## Proposed changes

- sanitize dev section

### CODE REVIEW

File: pkg/model/manifest.go [hunk 1]
```diff
@@ -636,8 +640,18 @@ func Read(bytes []byte) (*Manifest, error) {
 	}
 
 	hasShownWarning := false
-	for _, d := range manifest.Dev {
-		if (d.Image.Context != "" || d.Image.Dockerfile != "") && !hasShownWarning {
+	for devKey, dev := range manifest.Dev {
+		if shouldBeSanitized(devKey) {
```
Comment (jLopezbarb) [inline pkg/model/manifest.go:644]: We should probably check if there is a `global forward`/`build` with the same unsanitised key

File: pkg/model/manifest.go [hunk 2]
```diff
@@ -98,11 +98,15 @@ type Manifest struct {
 	Build         ManifestBuild           `json:"build,omitempty" yaml:"build,omitempty"`
 	Dependencies  ManifestDependencies    `json:"dependencies,omitempty" yaml:"dependencies,omitempty"`
 	GlobalForward []forward.GlobalForward `json:"forward,omitempty" yaml:"forward,omitempty"`
+	DevWarnings   DevWarnings
 
 	Type     Archetype `json:"-" yaml:"-"`
 	Manifest []byte    `json:"-" yaml:"-"`
 	IsV2     bool      `json:"-" yaml:"-"`
 }
+type DevWarnings struct {
```
Comment (jLopezbarb) [inline pkg/model/manifest.go:107]: On compose we need to store this because the warnings are shown after the injecting ports from images, but since we only have to show the users which services has been sanitised I'd moved the `map[string]string` to the function itself

File: pkg/model/manifest.go [hunk 3]
```diff
@@ -636,8 +636,16 @@ func Read(bytes []byte) (*Manifest, error) {
 	}
 
 	hasShownWarning := false
-	for _, d := range manifest.Dev {
-		if (d.Image.Context != "" || d.Image.Dockerfile != "") && !hasShownWarning {
+	for devKey, dev := range manifest.Dev {
+		if shouldBeSanitized(devKey) {
+			newDevKey := sanitizeName(devKey)
+			manifest.Dev[newDevKey] = dev
```
Comment (jLopezbarb) [inline pkg/model/manifest.go:642]: Could we check that we are not overriding a previous key?

**Comment by AdrianPedriza** [comment]
> the main problem with the needed solution is to find a proper way to show the user all the sanitized warnings in a friendly manner.
> 
> Current display:
> 
> Captura de pantalla 2022-08-22 a las 9 27 54

after discussing with @jLopezbarb about what should be the proper way to show the user this type of warning, as a temporary solution before the manifest parsing refactor we agree to display the user two kinds of warnings: one for okteto manifest and another one for compose files.

**Review by teresaromero — APPROVED** [review]

**Comment by jLopezbarb** [comment]
@AdrianPedriza Could you post a screenshot of the final result?

**Comment by AdrianPedriza** [comment]
> @AdrianPedriza Could you post a screenshot of the final result?

sure.

for `okteto up`

Captura de pantalla 2022-08-22 a las 16 25 42

for `okteto deploy`

**Comment by jLopezbarb** [comment]
> > @AdrianPedriza Could you post a screenshot of the final result?
> 
> sure.
> 
> for `okteto up`
> 
> Captura de pantalla 2022-08-22 a las 16 25 42
> 
> for `okteto deploy`
> 
> Captura de pantalla 2022-08-22 a las 16 26 16

I'd mention in the `okteto deploy` that the second message is referencing a compose file, but other than that looks good to me

**Comment by AdrianPedriza** [comment]
> > > @AdrianPedriza Could you post a screenshot of the final result?
> > 
> > 
> > sure.
> > for `okteto up`
> > Captura de pantalla 2022-08-22 a las 16 25 42
> > for `okteto deploy`
> > Captura de pantalla 2022-08-22 a las 16 26 16
> 
> I'd mention in the `okteto deploy` that the second message is referencing a compose file, but other than that looks good to me

yes, sorry it was an old pic. Check it now, I have edited the pic!

File: pkg/cmd/stack/deploy.go [hunk 4]
```diff
@@ -801,7 +801,7 @@ func DisplayVolumeMountWarnings(warnings []string) {
 
 func DisplaySanitizedServicesWarnings(previousToNewNameMap map[string]string) {
 	for previousName, newName := range previousToNewNameMap {
-		oktetoLog.Warning("Service '%s' has been sanitized into '%s'. This may affect discovery service.", previousName, newName)
+		oktetoLog.Warning("Service '%s' has been sanitized into '%s' for deployment. This may affect discovery service.", previousName, newName)
```
Comment (jLopezbarb) [inline pkg/cmd/stack/deploy.go:804]:
```suggestion
		oktetoLog.Warning("Service '%s' has been sanitized into '%s' in compose file. This may affect discovery service.", previousName, newName)
```

File: pkg/model/manifest.go [hunk 5]
```diff
@@ -655,9 +655,56 @@ func Read(bytes []byte) (*Manifest, error) {
...
+		if shouldBeSanitized(buildKey) {
+			sanitizedSvcName := sanitizeName(buildKey)
+			if _, ok := m.Build[sanitizedSvcName]; ok {
+				return fmt.Errorf("could not sanitize '%s'. Service with name '%s' already exists", buildKey, sanitizedSvcName)
+			}
+			m.Build[sanitizedSvcName] = build
+			sanitizedServicesNames[buildKey] = sanitizedSvcName
+			delete(m.Dev, buildKey)
+		}
+	}
```
Comment (ifbyol) [inline pkg/model/manifest.go:691]: We should be already doing this as we sanitize the build services to inject the environment variables. My feeling is that we spreading this into different places. Not sure if it makes sense or not, but doing this just when reading the manifest would avoid to have to do it in the rest of places

File: pkg/cmd/stack/deploy.go [hunk 6]
```diff
@@ -801,7 +801,7 @@ func DisplayVolumeMountWarnings(warnings []string) {
 
 func DisplaySanitizedServicesWarnings(previousToNewNameMap map[string]string) {
 	for previousName, newName := range previousToNewNameMap {
-		oktetoLog.Warning("Service '%s' has been sanitized into '%s'. This may affect discovery service.", previousName, newName)
+		oktetoLog.Warning("Service '%s' has been sanitized into '%s' in compose file. This may affect discovery service.", previousName, newName)
```
[the remark this answers is not in the document]
Comment (AdrianPedriza) [reply pkg/cmd/stack/deploy.go:804]: can you verify this? @jLopezbarb. LGTM the new err message

File: pkg/model/manifest.go [hunk 7]
```diff
@@ -655,9 +655,56 @@ func Read(bytes []byte) (*Manifest, error) {
 }
 
 func (m *Manifest) validate() error {
+	err := m.sanitizeSvcNames()
```
[the remark this answers is not in the document]
Comment (AdrianPedriza) [reply pkg/model/manifest.go:658]: yes, I will move it into our manifest `serializer.go`

File: pkg/cmd/stack/deploy.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (jLopezbarb) [reply pkg/cmd/stack/deploy.go:804]: This is just for compose and stack manifests. We are moving to always display compose instead of stack. I really like the new message!!

File: pkg/model/manifest.go (hunk 5 above)
Comment (AdrianPedriza) [reply pkg/model/manifest.go:691]: IIRC, at the moment the only place where we sanitize service names is when unmarshaling an stack. Any inconvenience to moving it to the manifest `serializer.go`?  @jLopezbarb

Comment (jLopezbarb) [reply pkg/model/manifest.go:691]: No, we should probably do it on serialisation

File: pkg/model/manifest.go [hunk 8]
```diff
@@ -658,6 +658,49 @@ func (m *Manifest) validate() error {
...
+	for _, gf := range m.GlobalForward {
+		if shouldBeSanitized(gf.ServiceName) {
+			sanitizedSvcName := sanitizeName(gf.ServiceName)
+			gf.ServiceName = sanitizedSvcName
+			sanitizedServicesNames[gf.ServiceName] = sanitizedSvcName
+		}
+	}
+
+	for previousName, newName := range sanitizedServicesNames {
+		oktetoLog.Warning("Service '%s' has been sanitized into '%s' in okteto manifest.", previousName, newName)
```
Comment (jLopezbarb) [inline pkg/model/manifest.go:698]:
```suggestion
		oktetoLog.Warning("Service '%s' in okteto manifest has been sanitized into '%s'.", previousName, newName)
```

**Review by jLopezbarb — APPROVED** [review]

**Comment by jLopezbarb** [comment]
I forgot to mention that this PR needs to update docs

**Comment by AdrianPedriza** [comment]
> I forgot to mention that this PR needs to update docs

where?

**Comment by jLopezbarb** [comment]
> > I forgot to mention that this PR needs to update docs
> 
> where?

https://github.com/okteto/docs

**Comment by AdrianPedriza** [comment]
> > > I forgot to mention that this PR needs to update docs
> > 
> > 
> > where?
> 
> https://github.com/okteto/docs

I mean, in which parts of docs we could talk about this kind of warnings?

**Comment by AdrianPedriza** [comment]
> > > > I forgot to mention that this PR needs to update docs
> > > 
> > > 
> > > where?
> > 
> > 
> > https://github.com/okteto/docs
> 
> I mean, in which parts of docs we could talk about this kind of warnings?

I know what you mean know. I have created this [issue](https://github.com/okteto/docs/issues/174) due to at the moment we need to wait for other PR to be integrated into docs.
