### PR TITLE
User Friendly Errors

### LINKED ISSUE #2690: User friendly errors when the yaml file can't be deserialized
**Describe the bug**
If I have a badly formatted okteto.yml, I get this error:

```
Invalid manifest:
    - line 2: cannot unmarshal !!str `todo-list` into model.ManifestBuild
    See https://okteto.com/docs/reference/manifest/ for details
```

`model.ManifestBuild` and `!!str`  are not concepts that a regular user would understand. Is it possible to parse that error and show something more user friendly? (e.g. " cannot unmarshal line 2 into a `build` object. See https://www.okteto.com/docs/reference/manifest/#build-object-optional for reference")

- OS: macOS
- Version okteto version 2.3.0-rc.1 

**Additional context**
This is the manifest:
``` 
build:
  todo-list
  
deploy:
  - cd manifest; kustomize edit set image okteto.dev/todo-list=okteto.dev/todo-list:${OKTETO_GIT_COMMIT}
  - kubectl apply -k manifest
dev:
  todo-list:
    image: okteto/golang:1
    command: bash
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    volumes:
    - /go/pkg/
    - /root/.cache/go-build/
    sync:
    - .:/app
    forward:
    - 2345:2345
```

### PR DESCRIPTION
**Pull request by andreafalzetti**
Fixes: LAKE-22
Also fixes #2690

# Proposed changes

- Add a new pkg responsible for suggesting user friendly errors
- Integrate new pkg with the `build` command

## How to validate

1. Build the CLI
2. Using any project, try breaking the manifest and run commands such as `build`, `deploy`, `up`, etc
3. Compare the output with the latest stable okteto version and see the improvements against this version

## CLI Quality Reminders 🔧

For both authors and reviewers:

- Scrutinize for potential regressions
- Ensure key automated tests are in place
- Build the CLI and test using the validation steps
- Assess Developer Experience impact (log messages, performances, etc)
- If too broad, consider breaking into smaller PRs
- Adhere to our [code style](https://github.com/okteto/okteto/blob/master/docs/code-style.md) and [code review](https://github.com/okteto/okteto/blob/master/docs/code-review.md) guidelines

### CODE REVIEW

File: cmd/build/command.go [hunk 1]
```diff
@@ -103,7 +103,12 @@ func Build(ctx context.Context) *cobra.Command {
 				}
 			}
 
-			return builder.Build(ctx, options)
+			err = builder.Build(ctx, options)
+			if err != nil {
+				return suggest.UserFriendlyError(err)
```
Comment (jLopezbarb) [inline cmd/build/command.go:108]: I find it odd to transform it here. There are many things that can go wrong in the middle to transform the error here. Maybe we should transform it on the serialization? and check if it's a userError like we do in other parts of the code like [preview list](https://github.com/okteto/okteto/blob/master/cmd/preview/list.go#L103)

File: go.sum [hunk 2]
```diff
@@ -457,6 +457,7 @@ github.com/fullsailor/pkcs7 v0.0.0-20190404230743-d7302db945fa/go.mod h1:KnogPXt
 github.com/fvbommel/sortorder v1.0.1 h1:dSnXLt4mJYH25uDDGa3biZNQsozaUWDSWeKJ0qqFfzE=
 github.com/fvbommel/sortorder v1.0.1/go.mod h1:uk88iVf1ovNn1iLfgUVU2F9o5eO30ui720w+kxuqRs0=
 github.com/garyburd/redigo v0.0.0-20150301180006-535138d7bcd7/go.mod h1:NR3MbYisc3/PwhQ00EMzDiPmrwpPxAn5GI05/YaO1SY=
+github.com/getkin/kin-openapi v0.76.0/go.mod h1:660oXbgy5JFMKreazJaQTw7o+X00qeSyhcnluiMv+Xg=
```
Comment (jLopezbarb) [inline go.sum:460]: Why do we change go.sum and not go.mod? Can you run go mod tidy in case any version is not sync?

File: pkg/suggest/rules.go [hunk 3]
```diff
@@ -0,0 +1,179 @@
+package suggest
```
Comment (jLopezbarb) [inline pkg/suggest/rules.go:1]: Missing copyright

File: pkg/suggest/rules.go [hunk 4]
```diff
@@ -0,0 +1,179 @@
...
+	"errors"
+	"fmt"
+	"github.com/agext/levenshtein"
+	"regexp"
+	"sigs.k8s.io/kustomize/kyaml/yaml"
+	"strings"
+)
+
+// NewStrReplaceRule creates a Rule that finds and replaces a string in the error message
+func NewStrReplaceRule(find, replace string) Rule {
```
Comment (jLopezbarb) [inline pkg/suggest/rules.go:13]: Do we need to export all the functions? I think the only one used outside the package is `UserFriendlyError`

**Review by jLopezbarb — COMMENTED** [review]
I haven't tested yet given that is a draft and probably will change but I put some concerns about the code that it's right now

File: pkg/suggest/rules.go (hunk 4 above)
Comment (andreafalzetti) [reply pkg/suggest/rules.go:13]: yes, I've refactored having `UserFriendlyError` so I will adjust before opening the PR :)

File: cmd/build/command.go (hunk 1 above)
Comment (andreafalzetti) [reply cmd/build/command.go]: this is a good topic to discuss, let me explain my idea: the function `suggest.UserFriendlyError` is responsible for improving all errors (not only manifest), in the near future we might need to improve error messages related to another aspect of the CLI.

I find very intruisive in the code to change literally every single file to wrap error return with a function specific for that error.

This approach is more generic and wrapping the whole CLI instead. I am sure it comes with a downside but from the positive side we have a single point of entrance for this logic.

File: go.sum (hunk 2 above)
Comment (andreafalzetti) [reply go.sum]: Fixed

File: pkg/suggest/rules.go [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+		replacedMessage := strings.ReplaceAll(e.Error(), find, replace)
+		return errors.New(replacedMessage)
+	}
+
+	return newRule(condition, transformation)
+}
+
+// newRegexRule creates a ruleInterface based on a regex pattern.
+func newRegexRule(pattern string, transform transformFunc) ruleInterface {
+	re := regexp.MustCompile(pattern)
```
Comment (maroshii) [inline pkg/suggest/rules.go:72]: We should be careful calling `regex.MustCompile` with a dynamic input since it panics if the regex is invalid. Not sure how we are providing `pattern` here as it seems to be a private function but mentioning just in case

File: pkg/suggest/suggest.go [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+func (es *errorSuggestion) suggest(err error) error {
+	newErr := err
+	for _, rule := range es.rules {
+		newErr = rule.apply(newErr)
+	}
+	return newErr
+}
+
+// UserFriendlyError generates a user-friendly suggestion for the given error.
+func UserFriendlyError(err error) error {
```
Comment (maroshii) [inline pkg/suggest/suggest.go:50]: An idea could be to have `UserFriendlyError` be a struct that implements the error interface instead of doing it in place which works but we lose all the context. This way it could be used as a regular error while also allowing to potentially expose extra functionality through type casting and enable the use of `error.Is`

File: pkg/suggest/rules.go (hunk 5 above)
Comment (ifbyol) [reply pkg/suggest/rules.go:72]: Agree, the purpose of this PR is to improve the user experience regarding the errors. This will potentially throw a panic which is not very descriptive usually. Couldn't we use `Compile` and handle the error gracefully?

Comment (andreafalzetti) [reply pkg/suggest/rules.go:72]: Thanks for the feedback, I will address it immediately

File: pkg/suggest/rules_yaml_test.go [hunk 7]
```diff
@@ -0,0 +1,185 @@
...
+					field2 string
+				}
+			}{},
+			expected: map[string][]string{"_": []string{"field1"}},
+		},
+		{
+			name:  "okteto manifest",
+			input: model.Manifest{},
+			expected: map[string][]string{
+				"forward.Forward":            []string{"localPort", "remotePort", "name", "labels"},
```
Comment (teresaromero) [inline pkg/suggest/rules_yaml_test.go:144]: nit: according to simplifycompositelit(default) redundant type from array, slice, or map composite literal

here and all the []string inside maps

```suggestion
				"forward.Forward":            {"localPort", "remotePort", "name", "labels"},
```

File: main.go [hunk 8]
```diff
@@ -170,7 +171,7 @@ func main() {
 	err = root.Execute()
 
 	if err != nil {
-		message := err.Error()
+		message := suggest.UserFriendlyError(err).Error()
```
Comment (teresaromero) [inline main.go:174]: not sure i agree on having this at the main, so all the error will go though the "suggestor", but not all would be...

Can we throw them from the origin? Related to frans suggestion i think we should raise a UserFriendlyError when is potentially triggered (serializer?) and then that goes around as error until is returned at the client.

File: pkg/suggest/suggest.go (hunk 6 above)
Comment (teresaromero) [reply pkg/suggest/suggest.go:50]: agree on the struct suggestion, minor comment i think the naming should be perhaps "SuggestionError" as we do have the "UserError" that involves a hint, this new type of error involves a suggestion that is being calculated

File: main.go (hunk 8 above)
Comment (andreafalzetti) [reply main.go:174]: @teresaromero This is a good point of dicussion. I look forward to hear more ideas. My point of view is that the "centralized" approach is looking at errors that now we don't want to modify but if in the future we want to extend the "content" we can easily add a new rule, if we change errors at the origin we would need to modify the code in N parts, making each new addition more complicated and in some occasions very intruisive. For example we might want to log "technical" errors inside, but to the user we want to present a different error. 

I also have the feeling that having it here could have an unwanted behaviour but on the other side the benefits above make me prefer the current approach.

File: pkg/suggest/suggest.go (hunk 6 above)
Comment (andreafalzetti) [reply pkg/suggest/suggest.go]: Change done ✅ Thanks @maroshii 🙇 

About renaming, I am not sure about `SuggestionError` because we have `newErrorSuggestion` too 🤔

File: pkg/suggest/rules_yaml_test.go (hunk 7 above)
Comment (andreafalzetti) [reply pkg/suggest/rules_yaml_test.go]: Updated, thanks ✅

File: pkg/suggest/rules_test.go [hunk 9]
```diff
@@ -0,0 +1,28 @@
...
+
+package suggest
+
+import (
+	"errors"
+	"github.com/stretchr/testify/assert"
+	"testing"
+)
+
+func TestNewLevenshteinRule_ErrWithoutPanic(t *testing.T) {
```
Comment (AdrianPedriza) [inline pkg/suggest/rules_test.go:22]: what is the purpose of this test? Does it assure us that there are no panics in all cases? asking it because there is only one test case

Comment (andreafalzetti) [reply pkg/suggest/rules_test.go:22]: It's to make sure we don't panic passing a broken regex

**Comment by andreafalzetti** [comment]
Moving to draft until I integrate the feedback.

File: pkg/suggest/rules.go [hunk 10]
```diff
@@ -0,0 +1,121 @@
...
+// apply executes the rule on the error.
+func (g *rule) apply(err error) error {
+	if g.condition(err) {
+		return g.transformation(err)
+	}
+	return err
+}
+
+// newStrReplaceRule creates a ruleInterface that finds and replaces a string in the error message
+func newStrReplaceRule(find, replace string) ruleInterface {
```
[the remark this answers is not in the document]
Comment (andreafalzetti) [reply pkg/suggest/rules.go]: done ✅

File: main.go (hunk 8 above)
Comment (andreafalzetti) [reply main.go]: After discussing offline we agreed to change this, the latest commits have this change, please have a look 🙏

File: pkg/suggest/suggest.go [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+	suggestion *errorSuggestion
+	err        error
+}
+
+// Error allows UserFriendlyError to satisfy the error interface
+func (u *UserFriendlyError) Error() string {
+	if err := u.suggestion.suggest(u.err); err != nil {
+		return err.Error()
+	}
+	return ""
```
[the remark this answers is not in the document]
Comment (andreafalzetti) [reply pkg/suggest/suggest.go]: I've changed this in the last commits, please have a look 🙏

File: pkg/suggest/rules.go [hunk 12]
```diff
@@ -0,0 +1,121 @@
...
+		threshold = 1
+	}
+
+	condition := func(e error) bool {
+		if err != nil {
+			return false
+		}
+		matchingErrors := re.FindAllStringSubmatch(e.Error(), -1)
+		for _, matchingError := range matchingErrors {
+			distance := levenshtein.Distance(target, matchingError[2], nil)
```
[the remark this answers is not in the document]
Comment (andreafalzetti) [reply pkg/suggest/rules.go]: I've changed this in the last commits, please have a look 🙏

File: pkg/suggest/rules.go [hunk 13]
```diff
@@ -0,0 +1,121 @@
...
+		}
+		return false
+	}
+
+	transformation := func(e error) error {
+		errorMsg := e.Error()
+		matchingErrors := re.FindAllStringSubmatch(e.Error(), -1)
+
+		for _, matchingError := range matchingErrors {
+			distance := levenshtein.Distance(target, matchingError[2], nil)
```
[the remark this answers is not in the document]
Comment (andreafalzetti) [reply pkg/suggest/rules.go]: I've changed this in the last commits, please have a look 🙏

File: pkg/suggest/rules_yaml.go [hunk 14]
```diff
@@ -0,0 +1,247 @@
...
+// hasLinkToDocs checks if the error already contains a link to our docs
+func hasLinkToDocs(err error) bool {
+	return strings.Contains(err.Error(), "https://www.okteto.com/docs")
+}
+
+// isYamlError check if the error is related to YAML unmarshalling
+func isYamlError(err error) bool {
+	if err == nil {
+		return false
+	}
```
[the remark this answers is not in the document]
Comment (andreafalzetti) [reply pkg/suggest/rules_yaml.go]: this is to make sure we don't apply the rule if the pattern provides creates an invalid regex, which returns that `err`

[the remark this answers is not in the document]
Comment (andreafalzetti) [reply pkg/suggest/rules_yaml.go]: it's a defensive way to prevent from interrupting the execution or returning any error to the user considered that this is supposed to be transparent for the user

File: pkg/suggest/rules.go [hunk 15]
```diff
@@ -0,0 +1,121 @@
...
+func newLevenshteinRule(pattern string, target string) ruleInterface {
+	re, err := regexp.Compile("(.*?)" + pattern + "(.*)") // Capture everything before and after the pattern
+
+	threshold := 3
+	if len(target) <= threshold {
+		threshold = 1
+	}
+
+	condition := func(e error) bool {
+		if err != nil {
```
[the remark this answers is not in the document]
Comment (andreafalzetti) [reply pkg/suggest/rules.go:78]: we could check if the pattern is valid outside of this fn? But then we still want to be defensive inside in my opinion

File: pkg/suggest/rules.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (andreafalzetti) [reply pkg/suggest/rules.go]: > so if distance is < 3 (can we use a const to add more context to this value?)

✅  done!

> should we calculate this rule using go routines and first matching return it? in order to not calculate distance for every key sequently

this could be a performance optimization, not sure if it's worth it, to be sure I've tried comparing execution time between okteto stable and this branch, but I cannot see any difference. Perhaps if we had hundreds of rules like this it would be beneficial to refactor. WHYT? 

Happy to give it a try together if you like

**Review by teresaromero — APPROVED** [review]
tested ✅ 

only to comment that also in stable, when running okteto build and the manifest has some kind of invalid key, the build is done and no error is returned.
perhaps to follow along we could open a task to fix this if we want to return an error while running okteto build

File: pkg/model/manifest_friendly_err.go [hunk 16]
```diff
@@ -0,0 +1,165 @@
...
+		return errors.New(newErr)
+	}
+
+	return suggest.NewRule(condition, transformation)
+}
+
+// fieldsNotExistingRule replaces "not found" fields which are unknown to the Okteto manifest specification
+func fieldsNotExistingRule() *suggest.Rule {
+	pattern := `field (\w+) not found`
+	re := regexp.MustCompile(pattern)
```
Comment (AdrianPedriza) [inline pkg/model/manifest_friendly_err.go:153]: https://github.com/okteto/okteto/pull/4009#discussion_r1361118090 this was already addressed before I think

File: pkg/model/manifest_friendly_err.go [hunk 17]
```diff
@@ -0,0 +1,165 @@
...
+		errorWithUrlToDocs := fmt.Sprintf("%s\n    Check out the okteto manifest docs at: %s", e.Error(), docsURL)
+		return errors.New(errorWithUrlToDocs)
+	}
+
+	return suggest.NewRule(isYamlErrorWithoutLinkToDocs, addUrl)
+}
+
+func indentNumLines() *suggest.Rule {
+	pattern := `(?:yaml: )?line (\d+):`
+	re := regexp.MustCompile(pattern)
```
Comment (AdrianPedriza) [inline pkg/model/manifest_friendly_err.go:136]: https://github.com/okteto/okteto/pull/4009#discussion_r1361118090 this will panic if expresion cannot be parsed

File: pkg/model/manifest_friendly_err.go [hunk 18]
```diff
@@ -0,0 +1,165 @@
...
+	}
+
+	return suggest.NewRule(isYamlErrorWithoutLinkToDocs, addUrl)
+}
+
+// addUrlToManifestDocs appends to the error the URL to the Okteto manifest ref docs
+func addUrlToManifestDocs() *suggest.Rule {
+	addUrl := func(e error) error {
+		docsURL := "https://www.okteto.com/docs/reference/manifest"
+		errorWithUrlToDocs := fmt.Sprintf("%s\n    Check out the okteto manifest docs at: %s", e.Error(), docsURL)
```
Comment (AdrianPedriza) [inline pkg/model/manifest_friendly_err.go:127]: should we wrap all errors that dont need an string modification? That way we can check error type unwrapping error chain

File: pkg/model/manifest_friendly_err.go [hunk 19]
```diff
@@ -0,0 +1,165 @@
...
+	}
+	// detect yaml errors by prefix
+	if strings.Contains(err.Error(), "yaml:") {
+		return true
+	}
+	// detect yaml errors by type
+	var typeError *yaml.TypeError
+	return errors.As(err, &typeError)
+}
+
```
Comment (AdrianPedriza) [inline pkg/model/manifest_friendly_err.go:113]: can you add a description about the rule added in this func?

File: pkg/model/manifest_friendly_err.go [hunk 20]
```diff
@@ -0,0 +1,165 @@
...
+func addYamlParseErrorHeading() *suggest.Rule {
+	addUrl := func(e error) error {
+		errorWithUrlToDocs := fmt.Sprintf("Your okteto manifest is not valid, please check the following errors:\n%s", e.Error())
```
Comment (AdrianPedriza) [inline pkg/model/manifest_friendly_err.go:116]: should we wrap all manifest errors with `ErrInvalidManifest` ? If not, some checks for this error will never work. For example -> https://github.com/okteto/okteto/blob/master/cmd/build/command.go#L138

Comment (andreafalzetti) [reply pkg/model/manifest_friendly_err.go]: Good call @AdrianPedriza 👏 I've made the change here: https://github.com/okteto/okteto/pull/4009/commits/ffe965d4ae9d44b3bffa9161ee1ecf0ccb8f75a4

File: pkg/model/manifest_friendly_err.go (hunk 19 above)
Comment (andreafalzetti) [reply pkg/model/manifest_friendly_err.go:114]: Due to new commit: https://github.com/okteto/okteto/pull/4009/commits/ffe965d4ae9d44b3bffa9161ee1ecf0ccb8f75a4 

This func is no longer necessary so I've removed it 🎉

File: pkg/model/manifest_friendly_err.go (hunk 18 above)
Comment (andreafalzetti) [reply pkg/model/manifest_friendly_err.go:119]: Done in https://github.com/okteto/okteto/pull/4009/commits/ffe965d4ae9d44b3bffa9161ee1ecf0ccb8f75a4 👍

File: pkg/model/manifest_friendly_err.go (hunk 17 above)
Comment (andreafalzetti) [reply pkg/model/manifest_friendly_err.go:128]: as discussed offline the pattern is fixed so it cannot panic, we use this approach in other parts where the pattern is hardcoded

File: pkg/model/manifest_friendly_err.go (hunk 16 above)
Comment (andreafalzetti) [reply pkg/model/manifest_friendly_err.go:145]: as per the comment below about the fixed pattern

**Review by AdrianPedriza — APPROVED** [review]
code looks good. Tested e2e and works as expected. Excellent work! 👍
