### PR TITLE
Populate syncthing errors to the user

### LINKED ISSUE #1127: Syncthing errors not propagated properly
**Describe the bug**
I have an `insufficient space` error in syncthing, but I am getting `syncthing is unresponsive`.

**Expected behavior**
A clear error about the source of the issue.

### PR DESCRIPTION
**Pull request by pchico83**
Signed-off-by: Pablo Chico de Guzman <pchico83@gmail.com>

Fixes #1127 #1165 

## Proposed changes
- Return a custom error with a CTA for insufficient space errors

### CODE REVIEW

File: pkg/syncthing/monitor.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ func (s *Syncthing) Monitor(ctx context.Context, disconnect chan error) {
 
 // MonitorStatus will send a message to disconnected if there is a synchronization error
 func (s *Syncthing) MonitorStatus(ctx context.Context, disconnect chan error) {
-	ticker := time.NewTicker(300 * time.Second)
+	ticker := time.NewTicker(30 * time.Second)
```
Comment (pchico83) [inline pkg/syncthing/monitor.go:50]: Since we are not calling `status` API anymore, we can check for errors faster

File: cmd/up/up.go [hunk 2]
```diff
@@ -960,6 +974,24 @@ func (up *upContext) getInteractive() bool {
 	return false
 }
 
+func (up *upContext) getInsufficientSpaceError(err error) error {
+	if up.Dev.PersistentVolumeEnabled() {
+		return errors.UserError{
+			E: err,
+			Hint: `Okteto volume is full
+    Increase your persistent volume size, run 'okteto down -v' and try 'okteto up' again
```
Comment (rberrelleza) [inline cmd/up/up.go:982]: are we using punctuation in the multi-line error messages? I think we should, since they are more explanation that error message.

File: pkg/errors/errors.go [hunk 3]
```diff
@@ -52,15 +52,15 @@ var (
...
-	ErrUnknownSyncError = fmt.Errorf("Unknown syncthing error")
-
 	// ErrNotInDevContainer is returned when an unsupported command is invoked from a dev container (e.g. okteto up)
 	ErrNotInDevContainer = fmt.Errorf("this command is not supported from inside an development container")
 
 	// ErrResetSyncthing is raised when syncthing database must be reset
 	ErrResetSyncthing = fmt.Errorf("synchronization database corrupted")
 
+	// ErrInsufficientSpace is raised when syncthing fails with no space available
+	ErrInsufficientSpace = fmt.Errorf("synchronization failure with no space available")
```
Comment (rberrelleza) [inline pkg/errors/errors.go:62]:
```suggestion
	ErrInsufficientSpace = fmt.Errorf("there isn't enough disk space available to synchronize your files")
```

File: pkg/syncthing/syncthing.go [hunk 4]
```diff
@@ -394,7 +393,7 @@ func (s *Syncthing) ResetDatabase(ctx context.Context, dev *model.Dev, local boo
 		if err != nil {
 			log.Infof("error posting 'rest/system/reset' local=%t syncthing API: %s", local, err)
 			if strings.Contains(err.Error(), "Client.Timeout") {
-				return errors.ErrUnknownSyncError
+				return fmt.Errorf("error resetting syncthing database local=%t: %s", local, err.Error())
```
Comment (rberrelleza) [inline pkg/syncthing/syncthing.go:396]: the  'local=' makes parsing the error harder. can we instead have a function that returns a message with the "local" or "remote" as part of the message?
```suggestion
				return fmt.Errorf("failed to reset syncthing database local=%t: %s", local, err.Error())
```

File: cmd/up/up.go (hunk 2 above)
Comment (pchico83) [reply cmd/up/up.go:982]: We are using both, I am trying to unify that here. Would you add punctuation on every line?

Comment (rberrelleza) [reply cmd/up/up.go:982]: Yes.

Comment (rberrelleza) [reply cmd/up/up.go:982]: I'd use punctuation in the hint, and leave the error as is. specially in these cases where the hint is more of a paragraph.

File: cmd/up/up.go [hunk 5]
```diff
@@ -960,6 +974,24 @@ func (up *upContext) getInteractive() bool {
...
+    More information about configuring your persistent volume at https://okteto.com/docs/reference/manifest#persistentvolume-object-optional`,
+		}
+	}
+	return errors.UserError{
+		E: err,
+		Hint: `The synchrinzation service is running out of space
+    Enable persistent volumes in your okteto manifest and try again
```
[the remark this answers is not in the document]
Comment (pchico83) [reply cmd/up/up.go:989]: I think so. do you have anything in mind?

File: pkg/syncthing/syncthing.go (hunk 4 above)
Comment (pchico83) [reply pkg/syncthing/syncthing.go:396]: we follow this pattern in several places. would you mind opening an issue to track the change?
