### PR TITLE
fix: set stage not only on failures

### LINKED ISSUE #2338: Logs for destroy commands don't include the stage
**Describe the bug**
If a manifest contains commands to be executed while destroying the application, logs in json format don't include any stage, so they don't appear in the UI. 

In these screenshots you can see how the manifest contains some commands to be executed, but in the UI they don't appear

Captura de pantalla 2022-03-10 a las 12 45 04
Captura de pantalla 2022-03-10 a las 12 45 12

Checking the pod logs, the outout is there without any stage

```
{"level":"info","stage":"","message":"Destroying...","timestamp":1646912104}
{"level":"info","stage":"","message":"KUBERNETES_SERVICE_PORT_HTTPS=443","timestamp":1646912104}
{"level":"info","stage":"","message":"CERT_MANAGER_WEBHOOK_PORT=tcp://10.108.12.81:443","timestamp":1646912104}
{"level":"info","stage":"","message":"KUBERNETES_SERVICE_PORT=443","timestamp":1646912104}
{"level":"info","stage":"","message":"OKTETO_POD_NAME=installer-4270fee7-cacb-4074-85b6-0d53bd31c18c-pqwxq","timestamp":1646912104}
....
```

**To Reproduce**

1. Execute `okteto pipeline deploy -r https://github.com/ifbyol/movies.git -b ifbyol/several-pipeline-manifests -f .okteto/okteto-pipeline-test.yml`
2. Once the pipeline is deployed, delete it from the UI and check the logs

**Expected behavior**
All commands executed in the destroy operation should be displayed in the UI as they are shown when the pipeline is deployed

**Desktop (please complete the following information):**
-

**Additional context**
-

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #2338 

## Proposed changes
- Include stage for command output and not only for failures
-

### CODE REVIEW

**Review by pchico83 — APPROVED** [review]

File: cmd/destroy/destroy.go [hunk 1]
```diff
@@ -230,6 +230,7 @@ func (dc *destroyCommand) runDestroy(ctx context.Context, opts *Options) error {
 	go func() {
 		for _, command := range manifest.Destroy {
 			oktetoLog.Information("Running %s", command.Name)
+			oktetoLog.SetStage(command.Name)
 			if err := dc.executor.Execute(command, opts.Variables); err != nil {
 				oktetoLog.SetStage(command.Name)
```
Comment (ifbyol) [inline cmd/destroy/destroy.go:235]: This line would't be needed anymore, right?

**Review by ifbyol — APPROVED** [review]
