### PR TITLE
Set dockerfile path to work as compose do

### LINKED ISSUE #1767: Stack build context doesn't work the same than in docker compose
**Describe the bug**
I have a docker compose file with:
```
    build:
      context: ./folder
      dockerfile: Dockerfile
```

to make it work with okteto stacks, I had to update it:

```
    build:
      context: ./folder
      dockerfile: folder/Dockerfile
```

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #1767

## Proposed changes

- Work the same way as docker compose does
-

### CODE REVIEW

File: pkg/model/stack.go [hunk 1]
```diff
@@ -221,7 +221,7 @@ func GetStack(name, stackPath string, isCompose bool) (*Stack, error) {
 			svc.Build.Dockerfile = ""
 		} else {
 			svc.Build.Context = loadAbsPath(stackDir, svc.Build.Context)
-			svc.Build.Dockerfile = loadAbsPath(stackDir, svc.Build.Dockerfile)
+			svc.Build.Dockerfile = loadAbsPath(svc.Build.Context, svc.Build.Dockerfile)
```
Comment (pchico83) [inline pkg/model/stack.go:224]: Does docker compose work if you do:
```
    build:
      context: ./folder
      dockerfile: folder/Dockerfile
```

instead of?
```
    build:
      context: ./folder
      dockerfile: Dockerfile
 ```

Comment (jLopezbarb) [reply pkg/model/stack.go:224]: no, what docker does is concatenate docker file to context.
If you run your first example you will receive an error like:
```
could not find /Users/xxx/Projects/context-dockerfile/folder/folder: stat /Users/xxx/context-dockerfile/folder/folder: no such file or directory
```

**Review by pchico83 — APPROVED** [review]
