### PR TITLE
fix: context switch regression

### LINKED ISSUE #3334: Can't switch to previous context with non existent / deleted namespace
**Describe the bug**
When using `okteto context` or `okteto context use CONTEXT_NAME`, I can't switch back to an Okteto Cluster context that points to a non existent or deleted namespace.

That namespace may have been created from a CLI instance and deleted from somewhere else, such as a different CLI instance or Okteto UI.

I need to run `okteto context delete CONTEXT_NAME` to delete the context and `okteto context` or `okteto context use CONTEXT_NAME` to create it again.

**To Reproduce**

1. Use `okteto context` or `okteto context use CONTEXT_NAME` to switch to an Okteto Cluster context.
2. Create a namespace with `okteto namespace` or `okteto namespace create NAMESPACE_NAME`.
3. Switch to a different context (any type) with `okteto context` or `okteto context use CONTEXT_NAME`.
4. Delete the namespace created in the 2nd step from a different CLI instance or Okteto UI.
5. Try to switch back to the context used in the 1st step with `okteto context` or `okteto context use CONTEXT_NAME`
6. See the error (attached below).

**Expected behavior**
I expect a warning about the namespace not being found and switch by default to my personal namespace.

**Desktop (please complete the following information):**

- OS: macOS arm64
- Version 2.11.0

**Additional context**

Error:

```
% okteto context
 ✓  Context 'https://cloud.okteto.com' selected
 x  Namespace 'foo-jpf-okteto' not found on context 'https://cloud.okteto.com'
    Please verify that the namespace exists and that you have access to it.
```

### PR DESCRIPTION
**Pull request by jLopezbarb**
# Proposed changes

Fixes #3334 regression caused by #3343 introduced in [CLI release 2.16.0](https://github.com/okteto/okteto/releases/tag/2.16.0)

The bug was introduced as part of the multicluster fixes. We end up going with another approach but this part of the code was a nice to have (always send the namespace the user will be working on) regarding if the user was running in multicluster or single cluster.

I've tested it with different commands (context and namespace)

Also I've added an unit test for the code that part where we were not covering the errors that we could face and the scenario that we fixed. 

| Before | After |
|--------|-------|
|   Captura de Pantalla 2023-07-06 a las 18 23 53  |  Captura de Pantalla 2023-07-06 a las 18 24 25 |

### CODE REVIEW

File: cmd/context/create.go [hunk 1]
```diff
@@ -289,8 +289,12 @@ func getLoggedUserContext(ctx context.Context, c *ContextCommand, ctxOptions *Co
 	if ctxOptions.Namespace == "" {
 		ctxOptions.Namespace = user.Namespace
 	}
+
 	userContext, err := c.getUserContext(ctx, ctxOptions.Namespace)
 	if err != nil {
+		if oktetoErrors.IsNotFound(err) {
+
```
Comment (andreafalzetti) [inline cmd/context/create.go:296]: missing a return?

**Comment by AdrianPedriza** [comment]
why a fix of the use logic is not in the `use.go` file but in `create.go`? shouldn't we refactor to place the code where it makes more sense to locate it?

**Comment by AdrianPedriza** [comment]
> why a fix of the use logic is not in the `use.go` file but in `create.go`? shouldn't we refactor to place the code where it makes more sense to locate it?

maybe we could move [this function](https://github.com/okteto/okteto/blob/jlopezbarb/fix-context-switch-regression/cmd/context/create.go#L106) into `use.go`. WDYT?

File: cmd/context/create.go [hunk 2]
```diff
@@ -336,17 +340,28 @@ func (c ContextCommand) getUserContext(ctx context.Context, ns string) (*types.U
...
-		// If there is a TLS error, don't continue the loop and return the raw error
-		if err != nil && oktetoErrors.IsX509(err) {
-			return nil, err
+			// If there is a TLS error, don't continue the loop and return the raw error
+			if oktetoErrors.IsX509(err) {
+				return nil, err
+			}
+
+			if oktetoErrors.IsNotFound(err) {
+				userContext, err = client.User().GetContext(ctx, "")
```
Comment (teresaromero) [inline cmd/context/create.go:360]:
```suggestion
                                 // fallback to personal namesapce using empty string as param
				userContext, err = client.User().GetContext(ctx, "")
```

**Comment by jLopezbarb** [comment]
> > why a fix of the use logic is not in the `use.go` file but in `create.go`? shouldn't we refactor to place the code where it makes more sense to locate it?
> 
> maybe we could move [this function](https://github.com/okteto/okteto/blob/jlopezbarb/fix-context-switch-regression/cmd/context/create.go#L106) into `use.go`. WDYT?

I do think that we should refactor it, but I don't think that should be covered in this PR to keep it simple

**Review by teresaromero — APPROVED** [review]

**Review by andreafalzetti — APPROVED** [review]
Tested and works as expected, thanks for fixing this 🎖️
