### PR TITLE
Deploy command works even if only dependencies are specified in manifest

### LINKED ISSUE #3364: `okteto deploy` shouldn't fail if manifest has `dependencies` but not `deploy` commands
**Describe the bug**
It's a common use case to deploy an okteto manifest with only `dependencies` to schedule the deployment of several repos together.

**To Reproduce**

1. Create a manifest with only `dependencies` section
1. `okteto deploy`

**Expected behavior**
It should work.

### PR DESCRIPTION
**Pull request by AnshulAngaria**
# Proposed changes

Fixes #3364 

Okteto deploy fails if manifest only has dependencies section. This PR makes changes so that it does not fail.

### CODE REVIEW

**Review by andreafalzetti — APPROVED** [review]
I've reviewed the change and tested different scenarios, LGTM! Thanks for your valuable contribution @AnshulAngaria 🙏

**Review by AdrianPedriza — APPROVED** [review]
LGTM

File: cmd/deploy/deploy_test.go [hunk 1]
```diff
@@ -290,6 +309,45 @@ func TestDeployWithErrorReadingManifestFile(t *testing.T) {
 	assert.False(t, p.started)
 }
 
+func TestDeployWithNeitherDeployNorDependencyInManifestFile(t *testing.T) {
```
Comment (jLopezbarb) [inline cmd/deploy/deploy_test.go:312]: Really nice test 🚀

**Review by jLopezbarb — APPROVED** [review]
Code looks good and already tested!!
