### PR TITLE
Set env var if exists on local

### LINKED ISSUE #1399: Environment variables without the = sign are not getting populated
**Describe the bug**
When using the following okteto.yaml:
```
name: hello-world
image: nginx:alpine
environment:
- MY_VAR
```

The $MY_VAR env var is not getting populated when doing `okteto up`. The  `MY_VAR`  variable exists, but the value its empty.

**Expected behavior**
Based on our docs, the value should be populated if `MY_VAR` exists in my environment.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.12.5

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #1399 

## Proposed changes
- If there is no = on an environment variable declaration, set its value if it is declared locally.
- It was affecting `Okteto up` and `Okteto stack` commands

### CODE REVIEW

File: pkg/model/serializer.go [hunk 1]
```diff
@@ -73,7 +73,11 @@ func (e *EnvVar) UnmarshalYAML(unmarshal func(interface{}) error) error {
 	}
 
 	e.Name, err = ExpandEnv(parts[0])
-	return err
+	if err != nil {
```
Comment (pchico83) [inline pkg/model/serializer.go:76]: Could you add a test for this case?

**Review by pchico83 — APPROVED** [review]
