### PR TITLE
Discard reverse port if collision detected

### LINKED ISSUE #1902: okteto init adds both forward and remote with the same port
image

During okteto up, I get the following error:

```
 i  Using rberrelleza @ cloud.okteto.com as context
 ✓  Persistent volume successfully attached
 ✓  Images successfully pulled
 x  Couldn't connect to your development container: port 9000 is listed multiple times, please check your forwards configuration
```

### PR DESCRIPTION
**Pull request by AgustinRamiroDiaz**
Fixes #1902

## Proposed changes

- Discard reverse forwarded ports when collision is detected with forwarded ports

### CODE REVIEW

File: pkg/cmd/init/run.go [hunk 1]
```diff
@@ -161,6 +166,19 @@ func setForwardsFromPod(ctx context.Context, dev *model.Dev, pod *apiv1.Pod, c *
 	return nil
 }
 
+// discardReverseIfCollision discards the reverse forward port if there is a collision with a forwarded port
+func discardReverseIfCollision(dev *model.Dev) {
```
Comment (pchico83) [inline pkg/cmd/init/run.go:170]: could you add unit tests for this function?

**Review by pchico83 — APPROVED** [review]

**Review by jLopezbarb — APPROVED** [review]
